// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingDataAccess.DbContexts;

#nullable disable

namespace TrainingDataAccess.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20230305120607_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("TrainingDataAccess.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonsMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Description = "Děti se rozdělí do dvou družstev, děti se drží za pas, první v řadě je hlava draka, poslední je ocas draka, družstva stojí asi 10 metrů od sebe, na povel se snaží hlava draka chytit ocas draka protihráče",
                            DurationMax = 10,
                            DurationMin = 5,
                            Name = "Dračí zápasy",
                            PersonsMin = 4
                        },
                        new
                        {
                            ActivityId = 2,
                            Description = "Čert má z rozlišováku připevněný ocas a snaží se všechny ostatní hráče polapit. Pokud někoho chytne, jde mimo hřiště.Hráči se snaží vzít čertovy ocas a osvobodit tak již chycené hráče. Po osvobození hráčů hra končí a stává se čertem hráč, který vzal čertovy ocas.",
                            DurationMax = 15,
                            DurationMin = 5,
                            Name = "Čertovská honička",
                            PersonsMin = 5
                        },
                        new
                        {
                            ActivityId = 3,
                            Description = "",
                            DurationMax = 20,
                            DurationMin = 10,
                            Name = "Florbal 3x3",
                            PersonsMax = 12,
                            PersonsMin = 6
                        },
                        new
                        {
                            ActivityId = 4,
                            Description = "Všichni mají florbalky. Každá ovečka má míček. Vlk se postaví do základní pozice na druhé straně hřiště. Po zahájení hry se saží chytit ovečku tak, že ji vezme florbalově čistě míček. Nesmí se vracet ve směru pohybu. Ovečka , která přišla o míček se stává vlkem, Po chycení všech oveček hra končí.",
                            DurationMax = 15,
                            DurationMin = 5,
                            Name = "Na ovečky a vlky s florbalkou a míčkem",
                            PersonsMin = 5
                        },
                        new
                        {
                            ActivityId = 5,
                            Description = "",
                            DurationMax = 10,
                            DurationMin = 3,
                            Name = "Mírný klus",
                            PersonsMin = 1
                        },
                        new
                        {
                            ActivityId = 6,
                            Description = "Také nazývané jako protlačování, slouží k lepší práci a flexibilitě kotníků a pomáhá nám ve startovací fázi běhu.  Nejprve cvik provádíme na místě, posléze s nepatrným posunem vpřed. Špičky necháváme zcela na místě, pracuje pouze pata, a to střídavým rychlým a dynamickým pohybem směrem vzhůru. Při tomto pohybu se nám jedno koleno dostane do popředí a druhým se snažíme protlačovat vzad. Horní část těla a boky držíme zpevněné s přímým pohledem vpřed. Ruce pokrčíme jako při běhu a pomáháme si s nimi udávat rychlost celého pohybu.",
                            DurationMax = 3,
                            DurationMin = 1,
                            Name = "Běžecká abeceda - lifting - pata špička",
                            PersonsMin = 1
                        },
                        new
                        {
                            ActivityId = 7,
                            Description = "Skipping nazýváme stejně dynamický pohyb jako u liftingu s tím rozdílem, že se nám do pohybu zapojí kolena. Ty se snažíme dostat co nejvýše nejlépe tak, aby stehno bylo ve vodorovné poloze. Není to však nutností. Hlavním požadavkem u tohoto cviku je dynamika. Dbát musíme na držení horní části těla, která by se neměla dostat do záklonu, ale spíše do mírného předklonu.",
                            DurationMax = 3,
                            DurationMin = 1,
                            Name = "Běžecká abeceda - skiping - vysoká kolena",
                            PersonsMin = 1
                        },
                        new
                        {
                            ActivityId = 8,
                            Description = "Tento cvik řadíme mezi ty, díky kterým se náš běh zrychlí a zefektivní. A bude také dynamičtější a zlepší se rychlost našich reakci při případném nuceném neočekávaném zastavení. Lýtka zvedáme směrem nahoru až k horní části stehen a hýždím, jako bychom se chtěli sami nakopnout. Pohyb musí být dynamický a rytmický. Tělo se snažíme mít po celou dobu zpevněné a narovnané. Vyšší úroveň můžeme nasadit například kombinací skippingu a zakopávání po 4 opakováních.",
                            DurationMax = 3,
                            DurationMin = 1,
                            Name = "Běžecká abeceda - zakopávaní",
                            PersonsMin = 1
                        },
                        new
                        {
                            ActivityId = 9,
                            Description = "Koordinačně nejtěžší cvik, který je ve finále a dobrém provedení skvělou hrou. Malými krůčky do boku střídá vždy zadní noha tu přední a střídavě ji křižuje vždy dopředu a dozadu. Paže rozpažíme, hlavu otočíme ve směru běhu a při dobrém provedení cítíme, jak se nám trup krásně protahuje, zatímco nohy nám hrají hru na kočkovanou a honí jedna druhou. Nesmíme zapomenout směr běhu po nějakém čase vystřídat.",
                            DurationMax = 3,
                            DurationMin = 1,
                            Name = "Běžecká abeceda - běh stranou ",
                            PersonsMin = 1
                        },
                        new
                        {
                            ActivityId = 10,
                            Description = "Ruce dáme v bok, vybereme si pravou nebo levou stranu a krokujeme. Postupně zrychlujeme, až do úplných skoků kdy se naše kotníky sílou dynamiky skoro jakoby spojí. Po sérii 10 skoků opakujeme na druhou stranu. Získáme díky tomu lepší odrazovou sílu a procvičujeme také koordinaci.",
                            DurationMax = 3,
                            DurationMin = 1,
                            Name = "Běžecká abeceda - skoky stranou",
                            PersonsMin = 1
                        },
                        new
                        {
                            ActivityId = 11,
                            Description = "Jelení skoky jsou nedílnou součástí a po sérii dynamických cviků nám tento napomáhá ke zvýšení běžeckého rozsahu a prevenci proti natrhnutí svalů. Dlouhé kroky postupně zrychlete, skoro až na běh při kterém odrazovou nohu napněte v kolenou a neodrazovou naopak vystřelte kolenem dopředu. Tento cvik je pro začátečníky nejsložitější, proto dbejte na precizním provedení a raději začněte pomalu skoro kroky než hned úplnými jeleními skoky. Pažemi pohybujeme podobně jako u běhu s možností úplného natažení ruky před sebe.",
                            DurationMax = 3,
                            DurationMin = 1,
                            Name = "Běžecká abeceda - jelení skoky",
                            PersonsMin = 1
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.ActivityTag", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ActivityTags", (string)null);

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            TagId = 21
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 52
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 53
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 54
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 21
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 41
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 13
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 18
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 20
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 40
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 41
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 11
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 20
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 21
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 31
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 5,
                            TagId = 21
                        },
                        new
                        {
                            ActivityId = 5,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 5,
                            TagId = 24
                        },
                        new
                        {
                            ActivityId = 5,
                            TagId = 37
                        },
                        new
                        {
                            ActivityId = 5,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 5,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 5,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 6,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 6,
                            TagId = 32
                        },
                        new
                        {
                            ActivityId = 6,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 6,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 6,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 7,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 7,
                            TagId = 32
                        },
                        new
                        {
                            ActivityId = 7,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 7,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 7,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 8,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 8,
                            TagId = 32
                        },
                        new
                        {
                            ActivityId = 8,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 8,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 8,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 9,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 9,
                            TagId = 32
                        },
                        new
                        {
                            ActivityId = 9,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 9,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 9,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 10,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 10,
                            TagId = 32
                        },
                        new
                        {
                            ActivityId = 10,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 10,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 10,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 11,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 11,
                            TagId = 32
                        },
                        new
                        {
                            ActivityId = 11,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 11,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 11,
                            TagId = 51
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.Property<int?>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId");

                    b.HasIndex("ParentTagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Color = "#ffd254",
                            Name = "Florbalový dril"
                        },
                        new
                        {
                            TagId = 11,
                            Color = "#ffd254",
                            Name = "1 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 12,
                            Color = "#ffd254",
                            Name = "2 x 2",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 13,
                            Color = "#ffd254",
                            Name = "3 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 14,
                            Color = "#ffd254",
                            Name = "4 x 4",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 15,
                            Color = "#ffd254",
                            Name = "5 x 5",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 16,
                            Color = "#ffd254",
                            Name = "2 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 17,
                            Color = "#ffd254",
                            Name = "2 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 29,
                            Color = "#ffd254",
                            Name = "Střelba",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 30,
                            Color = "#ffd254",
                            Name = "Přihrávka",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 31,
                            Color = "#ffd254",
                            Name = "Vedení míčku",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 35,
                            Color = "#ffd254",
                            Name = "Uvolňování",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 5,
                            Color = "#d9980d",
                            Name = "Forma"
                        },
                        new
                        {
                            TagId = 25,
                            Color = "#d9980d",
                            Name = "Hra",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 26,
                            Color = "#d9980d",
                            Name = "Florbal",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 27,
                            Color = "#d9980d",
                            Name = "Test",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 28,
                            Color = "#d9980d",
                            Name = "Štafeta",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 3,
                            Color = "#27dbf5",
                            Name = "Hráč"
                        },
                        new
                        {
                            TagId = 18,
                            Color = "#27dbf5",
                            Name = "Brankář",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 19,
                            Color = "#27dbf5",
                            Name = "Útočník",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 20,
                            Color = "#27dbf5",
                            Name = "Obránce",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 9,
                            Color = "#2196f3",
                            Name = "Hráčská kategorie"
                        },
                        new
                        {
                            TagId = 47,
                            Color = "#2196f3",
                            Name = "U7 - předpřípravka",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 48,
                            Color = "#2196f3",
                            Name = "U9 - přípravka",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 49,
                            Color = "#2196f3",
                            Name = "U11 - elévi",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 50,
                            Color = "#2196f3",
                            Name = "U13 - ml. žáci",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 51,
                            Color = "#2196f3",
                            Name = "U15 - st. žáci",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 52,
                            Color = "#2196f3",
                            Name = "U17 - dorost",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 53,
                            Color = "#2196f3",
                            Name = "U21 - junioři ",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 54,
                            Color = "#2196f3",
                            Name = "Muži",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 6,
                            Color = "#17a258",
                            Name = "Tělesná průprava"
                        },
                        new
                        {
                            TagId = 32,
                            Color = "#17a258",
                            Name = "Ohebnost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 33,
                            Color = "#17a258",
                            Name = "Síla",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 34,
                            Color = "#17a258",
                            Name = "Výbušnost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 36,
                            Color = "#17a258",
                            Name = "Rychlost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 4,
                            Color = "#0989c2",
                            Name = "Tréninková část"
                        },
                        new
                        {
                            TagId = 21,
                            Color = "#0989c2",
                            Name = "Rozehřátí",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 22,
                            Color = "#0989c2",
                            Name = "Rozcvička",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 23,
                            Color = "#0989c2",
                            Name = "Dril",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 24,
                            Color = "#0989c2",
                            Name = "Protahování",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 8,
                            Color = "#ff9102",
                            Name = "Vybavení"
                        },
                        new
                        {
                            TagId = 39,
                            Color = "#ff9102",
                            Name = "Florbalové míčky",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 40,
                            Color = "#ff9102",
                            Name = "Florbalová branka",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 41,
                            Color = "#ff9102",
                            Name = "Rozlišovací dresy",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 42,
                            Color = "#ff9102",
                            Name = "Kužely",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 43,
                            Color = "#ff9102",
                            Name = "Skočky",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 44,
                            Color = "#ff9102",
                            Name = "Žebřík",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 45,
                            Color = "#ff9102",
                            Name = "Švihadlo",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 46,
                            Color = "#ff9102",
                            Name = "Fotbalový míč",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 7,
                            Color = "#e6e9eb",
                            Name = "Ostatní"
                        },
                        new
                        {
                            TagId = 37,
                            Color = "#e6e9eb",
                            Name = "Herní myšlení",
                            ParentTagId = 7
                        },
                        new
                        {
                            TagId = 38,
                            Color = "#e6e9eb",
                            Name = "Spolupráce v týmu",
                            ParentTagId = 7
                        },
                        new
                        {
                            TagId = 10,
                            Color = "#666666",
                            Name = "Vlastní"
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Persons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Place")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingPart", b =>
                {
                    b.Property<int>("TrainingPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingPartId");

                    b.ToTable("TrainingParts");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingPartActivity", b =>
                {
                    b.Property<int>("TrainingPartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainingPartId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("TrainingPartActivities", (string)null);
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingTrainingPart", b =>
                {
                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingPartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainingId", "TrainingPartId");

                    b.HasIndex("TrainingPartId");

                    b.ToTable("TrainingTrainingParts", (string)null);
                });

            modelBuilder.Entity("TrainingDataAccess.Models.ActivityTag", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Activity", "Activity")
                        .WithMany("ActivityTags")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingDataAccess.Models.Tag", "Tag")
                        .WithMany("ActivityTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Tag", "ParentTag")
                        .WithMany()
                        .HasForeignKey("ParentTagId");

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingPartActivity", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Activity", "Activity")
                        .WithMany("TrainingPartActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingDataAccess.Models.TrainingPart", "TrainingPart")
                        .WithMany("TrainingPartActivities")
                        .HasForeignKey("TrainingPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("TrainingPart");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingTrainingPart", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Training", "Training")
                        .WithMany("TrainingTrainingParts")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingDataAccess.Models.TrainingPart", "TrainingPart")
                        .WithMany("TrainingTrainingParts")
                        .HasForeignKey("TrainingPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("TrainingPart");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Activity", b =>
                {
                    b.Navigation("ActivityTags");

                    b.Navigation("TrainingPartActivities");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.Navigation("ActivityTags");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Training", b =>
                {
                    b.Navigation("TrainingTrainingParts");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingPart", b =>
                {
                    b.Navigation("TrainingPartActivities");

                    b.Navigation("TrainingTrainingParts");
                });
#pragma warning restore 612, 618
        }
    }
}
