using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace TrainingDataAccess.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Activities",
                columns: table => new
                {
                    ActivityId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    Description = table.Column<string>(type: "TEXT", nullable: true),
                    PersonsMin = table.Column<int>(type: "INTEGER", nullable: true),
                    PersonsMax = table.Column<int>(type: "INTEGER", nullable: true),
                    DurationMin = table.Column<int>(type: "INTEGER", nullable: true),
                    DurationMax = table.Column<int>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Activities", x => x.ActivityId);
                });

            migrationBuilder.CreateTable(
                name: "Tags",
                columns: table => new
                {
                    TagId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    ParentTagId = table.Column<int>(type: "INTEGER", nullable: true),
                    Color = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tags", x => x.TagId);
                    table.ForeignKey(
                        name: "FK_Tags_Tags_ParentTagId",
                        column: x => x.ParentTagId,
                        principalTable: "Tags",
                        principalColumn: "TagId");
                });

            migrationBuilder.CreateTable(
                name: "ActivityTags",
                columns: table => new
                {
                    ActivityId = table.Column<int>(type: "INTEGER", nullable: false),
                    TagId = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ActivityTags", x => new { x.ActivityId, x.TagId });
                    table.ForeignKey(
                        name: "FK_ActivityTags_Activities_ActivityId",
                        column: x => x.ActivityId,
                        principalTable: "Activities",
                        principalColumn: "ActivityId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ActivityTags_Tags_TagId",
                        column: x => x.TagId,
                        principalTable: "Tags",
                        principalColumn: "TagId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Activities",
                columns: new[] { "ActivityId", "Description", "DurationMax", "DurationMin", "Name", "PersonsMax", "PersonsMin" },
                values: new object[,]
                {
                    { 1, "Děti se rozdělí do dvou družstev, děti se drží za pas, první v řadě je hlava draka, poslední je ocas draka, družstva stojí asi 10 metrů od sebe, na povel se snaží hlava draka chytit ocas draka protihráče", null, 4, "Dračí zápasy", 10, 5 },
                    { 2, "Čert má z rozlišováku připevněný ocas a snaží se všechny ostatní hráče polapit. Pokud někoho chytne, jde mimo hřiště.Hráči se snaží vzít čertovy ocas a osvobodit tak již chycené hráče. Po osvobození hráčů hra končí a stává se čertem hráč, který vzal čertovy ocas.", null, 5, "Čertovská honička", 15, 5 },
                    { 3, "", 12, 6, "Florbal 3x3", 20, 10 },
                    { 4, "Všichni mají florbalky. Každá ovečka má míček. Vlk se postaví do základní pozice na druhé straně hřiště. Po zahájení hry se saží chytit ovečku tak, že ji vezme florbalově čistě míček. Nesmí se vracet ve směru pohybu. Ovečka , která přišla o míček se stává vlkem, Po chycení všech oveček hra končí.", null, 5, "Na ovečky a vlky s florbalkou a míčkem", 15, 5 },
                    { 5, "", null, 1, "Mírný klus", 10, 3 },
                    { 6, "Také nazývané jako protlačování, slouží k lepší práci a flexibilitě kotníků a pomáhá nám ve startovací fázi běhu.  Nejprve cvik provádíme na místě, posléze s nepatrným posunem vpřed. Špičky necháváme zcela na místě, pracuje pouze pata, a to střídavým rychlým a dynamickým pohybem směrem vzhůru. Při tomto pohybu se nám jedno koleno dostane do popředí a druhým se snažíme protlačovat vzad. Horní část těla a boky držíme zpevněné s přímým pohledem vpřed. Ruce pokrčíme jako při běhu a pomáháme si s nimi udávat rychlost celého pohybu.", null, 1, "Běžecká abeceda - lifting - pata špička", 3, 1 },
                    { 7, "Skipping nazýváme stejně dynamický pohyb jako u liftingu s tím rozdílem, že se nám do pohybu zapojí kolena. Ty se snažíme dostat co nejvýše nejlépe tak, aby stehno bylo ve vodorovné poloze. Není to však nutností. Hlavním požadavkem u tohoto cviku je dynamika. Dbát musíme na držení horní části těla, která by se neměla dostat do záklonu, ale spíše do mírného předklonu.", null, 1, "Běžecká abeceda - skiping - vysoká kolena", 3, 1 },
                    { 8, "Tento cvik řadíme mezi ty, díky kterým se náš běh zrychlí a zefektivní. A bude také dynamičtější a zlepší se rychlost našich reakci při případném nuceném neočekávaném zastavení. Lýtka zvedáme směrem nahoru až k horní části stehen a hýždím, jako bychom se chtěli sami nakopnout. Pohyb musí být dynamický a rytmický. Tělo se snažíme mít po celou dobu zpevněné a narovnané. Vyšší úroveň můžeme nasadit například kombinací skippingu a zakopávání po 4 opakováních.", null, 1, "Běžecká abeceda - zakopávaní", 3, 1 },
                    { 9, "Koordinačně nejtěžší cvik, který je ve finále a dobrém provedení skvělou hrou. Malými krůčky do boku střídá vždy zadní noha tu přední a střídavě ji křižuje vždy dopředu a dozadu. Paže rozpažíme, hlavu otočíme ve směru běhu a při dobrém provedení cítíme, jak se nám trup krásně protahuje, zatímco nohy nám hrají hru na kočkovanou a honí jedna druhou. Nesmíme zapomenout směr běhu po nějakém čase vystřídat.", null, 1, "Běžecká abeceda - běh stranou ", 3, 1 },
                    { 10, "Ruce dáme v bok, vybereme si pravou nebo levou stranu a krokujeme. Postupně zrychlujeme, až do úplných skoků kdy se naše kotníky sílou dynamiky skoro jakoby spojí. Po sérii 10 skoků opakujeme na druhou stranu. Získáme díky tomu lepší odrazovou sílu a procvičujeme také koordinaci.", null, 1, "Běžecká abeceda - skoky stranou", 3, 1 },
                    { 11, "Jelení skoky jsou nedílnou součástí a po sérii dynamických cviků nám tento napomáhá ke zvýšení běžeckého rozsahu a prevenci proti natrhnutí svalů. Dlouhé kroky postupně zrychlete, skoro až na běh při kterém odrazovou nohu napněte v kolenou a neodrazovou naopak vystřelte kolenem dopředu. Tento cvik je pro začátečníky nejsložitější, proto dbejte na precizním provedení a raději začněte pomalu skoro kroky než hned úplnými jeleními skoky. Pažemi pohybujeme podobně jako u běhu s možností úplného natažení ruky před sebe.", null, 1, "Běžecká abeceda - jelení skoky", 3, 1 },
                    { 12, "Jednoduše se otočte a začněte jen chůzí. Postupně tempo zvyšujte až do poloběhu. V žádném případě nedoporučuji se otáčet, jen by vás to zmátlo a dezorientovalo.", null, 1, "Běžecká abeceda - běh zpět", 3, 1 },
                    { 13, "náklon hlavy (do stran a dopředu)", null, 1, "protažení krku ", 3, 1 },
                    { 14, "kroužení (krouživým pohybem)", null, 1, "protažení paží", 3, 1 },
                    { 15, "úklony vpravo a vlevo", null, 1, "protažení trupu", 3, 1 },
                    { 16, "v předklonu střídavě hmitáme levou rukou k pravému chodidlu a opačně    ", null, 1, "protažení ramen a zad", 3, 1 },
                    { 17, "kroužení boky a pánví", null, 1, "protažení trupu", 3, 1 },
                    { 18, "kroužení v kyčli, koleni a kotníku", null, 1, "protažení kloubů na nahou  ", 3, 1 },
                    { 19, "opřeni rukama o zeď a střídavě pokládáme levou a pravou patu na podlahu ", null, 1, "protažení lýtek a achilovky", 3, 1 },
                    { 20, "S rukama za zády leh na zemi a vstát", null, 1, "Blboun", 5, 1 },
                    { 21, "Hraje se 2 na 2. Hráči si přihrávají míč házením. Vítězí tým, který má v daném časovém úseku více přihrávek za sebou", 4, 4, "Nahrávky házení míčem 2x2", 10, 3 },
                    { 22, "Hraje se 2 na 2. Hráči si přihrávají. Vítězí tým, který má v daném časovém úseku více přihrávek za sebou", 4, 4, "Nahrávky 2x2", 10, 3 },
                    { 23, "Jeden nebo více hráčů představuje Mrazíka, který/ří se snaží chytit ostatní. Koho se dotkne rukou, ten je zmražen a čeká na vysvobození. Chycený se rozkročí a jakmile ho někdo podleze, může pokračovat ve hře.", null, 4, "Mrazík", 15, 5 },
                    { 24, "2 týmy hrají proti sobě - bořiči proti stavitelům. Na určitém prostoru se rozhází velký počet kloboučků - půlka jich je postavena normálně, půlka je vzhůru nohama. Jeden tým obrací kloboučky vzhůru nohama - bořiči, druhý tým je obrací správně - stavitelé. Časový interval cca do 1min. vyhrává tým, kterých kloboučků je víc - zbořené x postavené.", null, 6, "Bořiči a stavitelé", 10, 5 },
                    { 25, "Hráči se rozdělí do družstev o stejném počtu a postaví se vždy dvě družstva naproti sobě. Po písknutí vyráží první v pořadí z obou družstev. Když se setkají, zahrají si hru: kámen, nůžky, papír. Ten, co prohraje, vrací se zpět do svého družstva, ten, co vyhrál pokračuje dál ve svém směru. To družstvo, co prohrálo, vysílá druhého z družstva. Když se setkají, opět si zahrají hru. A tak hra pokračuje dál. Hráč, který dorazí k družstvu protihrajících bez prohry, získává pro své družstvo 1 bod. Vyhrává to družstvo, které za určitý čas získá nejvíce bodů.", null, 6, "Kámen - nůžky - papír", 15, 5 },
                    { 26, "každý hráč má za trenkami vzadu zastrčený rozlišovák, který musí být dostatečně vytažen hráči se snaží odebrat si ocásek navzájem, bránt se mohou vhodným pohybem", null, 6, "Ocásky", 10, 5 },
                    { 27, "na vymezeném prostoru jsou rozmístěny 4 barvy kuželů po 4ks. hráč na zrakový či sluchový signál /barva kužele/ vbíhá mezi kužely do prostoru a postupně se co nejrychleji dotkne všech kuželů dané barvy a vybíhá z prostoru na druhé straně opět mezi kužely.", 10, 2, "Zahrádka", null, null },
                    { 28, "Všichni děti začínají jako kuřátka, jsou ve dřepu a pípají, přijdou k sobě dvě kuřata a zahrají si kámen, nůžky, papír, ten kdo, vyhraje, postupuje do další úrovně a stává se kočka, prohrané kuře zůstává kuřetem, takto se postupuje ve vývoji dál, vyhrává ten, kde se stane první člověkem -> kuře → kočka → slon → opice → člověk", null, 6, "Evoluce", 15, 5 },
                    { 29, "otočíme branky proti sobě v rozumné vzálenosti rozdělíme hráče na dva týmy. Do hry vhodíme tři florbalové míče. Vyhrává ten kdo dá více golů. ", 12, 6, "Florbalový fotbálek", 15, 10 },
                    { 30, "Čert má oháňku, koho se čert dotkne, ten zkamení na místě, kdo mu vytrhne oháňku, stane se čertem a všichni ostatní ožívají", null, 6, "Čertovská honička", 10, 5 },
                    { 31, "Dvě družstva, vždy první člověk, druhý kůň a třetí rak, na povel vybíhá jak první člověk, oběhne metu a vrací se zpátky, pak vybíhají koně, kteří jdou po čtyřech, pak raci, kteří jdou pozpátku, hru hrajeme 3x, aby se děti v rolích vystřídali – vždy posuneme o jednoho, člověk bude kůň, kůň bude rak a rak bude člověk", null, 6, "Člověk, kůň, rak", 15, 5 },
                    { 32, "Dvě stejně početná družstva se rozmístí proti sobě na vzdálenost 10–15 metrů. Skupina, která představuje želvy, zaujme podpor klečmo. Druhá skupina, která hraje lovce, se pohybuje chůzí. Po zahájení hry mají želvy za úkol přemístit se z pláže (jedna strana tělocvičny) do moře (druhá strana tělocvičny). Lovci se snaží želvy ulovit přetočením na záda. Želva přetočená na záda se nemůže bránit a vypadá ze hry. Hrajeme na dvě kola, ve kterých se úlohy družstev vymění.", null, 6, "Želvy a lovci", 15, 5 },
                    { 33, "Dvojice, jeden ve vzporu ležmo, druhý mu drží nohy. Všichni proti všem se trakaři snaží donutit (tahem a tlakem) ostatní trakaře ke změně polohy (dotek hrudníku země). Bojují jen cvičenci v poloze vzporu ležmo!!! Vítězí poslední trakař. V druhém kole si cvičenci role vymění.", null, 4, "Souboj trakařů", 10, 5 },
                    { 34, "Cvičenci se chytí za ruce a vytvoří kruh. Jeden cvičenec je uvnitř kruhu a snaží se proklouznout prostorem mezi cvičenci ven z kruhu. Ti mu v tom brání přisunutím se k sobě, nesmí však kruh zmenšovat, tudíž se na jiné straně kruhu musí mezery zvětšit. Pro přehlednost je kruh na videu pouze naznačen.", null, 6, "Únik z pevnosti", 10, 5 },
                    { 35, "Hráči se rozdělí na obránce a útočníky. Obránci zaujmou místo ve vytyčeném obdélníku, hradu. Útočníci se rozestaví po obvodu hradu, nesmí se ale žádnou částí svého těla dotknout hranice hradu. Přitom se snaží obránce z hradu vytáhnout. Obránci se tomu naopak brání tak, že vtahují útočníky dovnitř. Ten, kdo je vtažen do kruhu, stává se obráncem a naopak. Zvítězí to družstvo, které na svou stranu přetahá všechny protihráče.", null, 8, "Boj o hrad", 15, 5 },
                    { 36, "Když se někde v krajině vyskytne vyvýšené místo nebo kruh urostřed haly stačí aby na něj kdokoliv vylezl a zavolal Jsem král.Hned se jej snaží stáhnout z vyvýšeného místa a sami sebe tam dosadit na místo panovnické. Ctižádostí každého je, aby se dostal, alespoň na chvíli nahoru a mohl zvolat ono Jsem král.Upozorňuji, že zvláště při této hříčce je třeba dbát míry a nenechat hru přerůst ve rvačku, děti (i vedoucí) se potřebují vyblbnout, ale není třeba je hned zabíjet.", null, 5, "Na krále", 10, 5 },
                    { 37, "Dva hráči proti sobě s jedním míčem. Oba dva drží míč pevně oběma rukama. Na znamení se snaží vybojovat míč. Cvičení se provádí na stanovený počet vítězství nebo na co nejvíce vítězství po stanovený čas.", null, 2, "Souboj o míč", 10, 3 },
                    { 38, "Hráči ve dvojici k sobě stojí zády, ruce mají vzájemně zaklesnuté v loktech. Na povel se snaží druhého dostat na svoje záda, tak aby se nedotýkal země.", null, 2, "Vážení cibule", 10, 3 },
                    { 39, "dvojice zápasí na žíněnkách začíná se v kleku a po celou dobu nesmí zápasníci na nohy do stoje jeden druhého se snaží položit na záda.", null, 2, "Sumo", 10, 3 },
                    { 40, "Hřiště se rozdělí na třetiny. V prostřední třetině je kočka a má kolem sebe spoustu sýrů (míčků). Myši přebíhají z krajní třetiny přes území se sýry a snaží se ukořistit sýr a přeběhnout na druhou stranu hřiště aniž by je kočka lapila. Myš, která je chycena se státá kočkou. Myši přebíhají dokud neposbírají všechny sýry nebo nejsou všechny lapeny.", null, 5, "Kočka a myš", 10, 5 },
                    { 41, "čtyřmi kužely vymezíme hřištěna honičku a stranou připravíme čtyři posilovací stanoviště. Vybereme čtyři hráče (honiče), a každému dáme rozlišovací dres s jinou barvou (zelený, žlutý, bílý, červený). Ke každé barvě přiřadíme jedno stanoviště a určíme co jak dlouho se bude provádět. Hráči, kteří jsou chyceni odchází na posilovací stanoviště podle barvy, kterou byl chycen. Po provedí se vrací zpět a zapojuje se do honičky. ", null, 6, "Fitness honička", 10, 5 },
                    { 42, "Děti rozdělíme do dvou týmů a s menším gumovým balonem hrajeme házenou. Hrač může s balonem pouze 3 kroky (nebo žádný) a gól je do branky. Průběh hry můžeme měnit i během pozadu.", null, 6, "Házená", 10, 5 },
                    { 43, "V prostoru rozmístěné lavičky,kruhy,kostky cokoliv. Děti běží po obvodu haly, na písknutí: Bomba - lehnou do tří na zem, kdo nestíhá vypadává Povodeň - musí být do tří na lavičkách, v kruhu, ve čtverci z kuželů (nikdo nesmí stát na podlaze) jinak vypadává Počet 3,4,5 atd. - dětí musí do tří vytvořit předem určenou skupinu, nadpočetní vypadávají", null, 10, "Bomba", 10, 5 },
                    { 44, "Hrací plochu rozdělíme na polovinu. Do každé poloviny se postaví jedno družstvo a 30 míčů (papírových koulí). Na povel trenéra začnou obě družstva házet míče ze své poloviny hrací plochy na polovinu soupeře. Hra končí po uplynutí časového limitu. Vyhrává to družstvo, které má na své polovině méně míčů.", null, 8, "Míčkovaná", 10, 3 },
                    { 45, "Vytvoříme dvě družstva  V každém družstvu přidělíme dětem čísla. Mezi družstva přesně doprostřed položíme velký a malý míč. Trenér vyvolá nějaké číslo. Z každého družstva vyběhne hráč s tímto číslem a běží k míčům. Hráč, který doběhne první, vezme větší míč a snaží se s ním doběhnout ke svému družstvu. Hráč, který doběhne jako druhý, vezme menší míč a snaží se vybít hráče s větším míčem. Když ho vybije, získává pro své družstvo bod, a když ne, získává bod družstvo soupeře. Vybití platí jen do doby, než se hráč s větším míčem vrátí zpět ke svému družstvu.", null, 10, "Číslovaná", null, null },
                    { 46, "Dvě družstva stojí vedle sebe (děti v jednotlivých družstvech v zástupu za sebou). První v každém družstvu na povel trenéra začne podávat míč nad hlavou dítěti, které stojí hned za ním, a takto hra pokračuje až k poslednímu dítěti. Poslední dítě pak běží na začátek řady a pokračuje stejným způsobem. Hra končí v momentě, kdy se vystřídají v podávání všichni členové družstva. Vítězí družstvo, které bylo rychlejší. ", null, 8, "Předávaná", 5, 3 },
                    { 47, "Trenér vytvoří z florbalek trojúhelníková prostor a určí 3 hráče, kteří budou představovat 3 kuny a budou ve vymezeném prostoru hnízda. Ostatní hráči budou veverky mimo ohraničené území. V hnízdě veverek, kde jsou kuny, jsou míče představující oříšky. Na povel začnou kuny vyhazovat oříšky z hnízda ven. Veverky vyhozené oříšky sbírají a rychle je nosí zpět do hnízda, kam je polokládají. Nesmí je do hnízda házet, smí je nosit jen po jednom. Hodnotí se, kolik míčů po skončení časového intervalu hry zůstalo v hnízdě.", null, 6, "Veverky a kuny", 10, 3 },
                    { 48, "Dvě družstva stojí vedle sebe (děti v jednotlivých družstvech v zástupu za sebou). Poslední v každém družstvu na povel trenéra začne podlézat mezi nohama hráčů před ní. Jakmile se dostane na začátek šatfety předá hráči míč za sebou a pak dále až poslednímu hráči. ", null, 6, "Předávaná s podlézáním", 5, 3 },
                    { 49, "Dvě družstva stojí vedle sebe (děti v jednotlivých družstvech v zástupu za sebou). První v každém družstvu na povel trenéra začne podávat míč do strany vlevo dalšímu dítěti, které stojí hned za ním, a ten podá opět do strany ale vpravo takto hra pokračuje až k poslednímu dítěti. Poslední dítě pak běží na začátek řady a pokračuje stejným způsobem. Hra končí v momentě, kdy se vystřídají v podávání všichni členové družstva. Vítězí družstvo, které bylo rychlejší. Způsobů podávání míče je celá řada, například podávání pod nohama, bokem, kutálení pod nohama apod.", null, 6, "Předávání do boku", 5, 3 },
                    { 50, "Dítě (honič), které má babu, pronásleduje ostatní a snaží se je chytit (předat babu). Když se mu to podaří, plácne rukou některého z honěných, předá mu dotykem babu i svoji funkci honiče. Vracení role, tzv. oplátka, není dovolena. Nový honič nesmí dát babu tomu, od koho ji dostal. Pokud hraje více než deset dětí, je dobré, když dětí (honičů) je více.", null, 4, "Jednoduchá honička", 5, 3 },
                    { 51, "Začíná jedno dítě (honič) a snaží se někoho chytit. Koho chytne, ten se stává také honičem a chytne se prvního honiče za ruku. A pak honí ve dvojici. Další, koho chytí, se k nim opět přidá. Takto hra pokračuje do té doby, dokud nezbude ve hře poslední dítě. ", null, 6, "Hadí honička", 5, 3 },
                    { 52, "Děti rozdělíme do dvojic a každou dvojici svážeme švihadlem vždy jednou nohou k sobě. Jedna dvojice má babu a jejím úkolem je chůzí nebo během předat babu jiné dvojici. Stačí, když ti, co mají babu, „plácnou“ jen jednoho z dvojice a celá dvojice má pak babu.", null, 6, "Honička dvojic", 5, 3 },
                    { 53, "Po hrací ploše rozmístíme jednu nebo více žíněnek podle toho, kolik hráčů bude hrát. Zvolíme jednoho či dva honiče, závisí na počtu hráčů. Honič začne honit. Pokud se dotkne honěného rukou, znehybní ho a ten si lehne na záda na zem. Nechycení hráči zachraňují znehybněné tím způsobem, že je dva, tři nebo čtyři zachránci přenesou (nejčastěji zvednutím za končetiny) na žíněnku. Zde chycení obživnou a hrají dále.", null, 6, "Honička se záchranou", 5, 3 },
                    { 54, "Děti rozdělíme do dvou stejně početných družstev. První družstvo se rozestaví na jednom konci tělocvičny v přesně vymezeném prostoru a druhé družstvo ve stejně velkém prostoru na druhé straně tělocvičny. Každé družstvo vyšle na území soupeřů jednoho honiče. Na povel vyučujícího začnou honiči honit soupeře a stočenou roličkou z novin se je snažit vyřadit ze hry tím, že je udeří. Každý vyřazený hráč odchází na předem určené místo. Honění nesmějí překračovat hranice vymezeného prostoru, překročení znamená automatické vyřazení ze hry. Honička končí, když je celé jedno družstvo vyřazeno.", null, 6, "Vyřazovací honička", 5, 3 },
                    { 55, "Ve vymezeném prostoru s různě rozmístěnýmy kužely hrajeme babu. Předáváme babu pomocí dotyku míče (nemusí být) dotykem (ne házením). Pokud někdo shodí kužel má trestný bod. Po uplynutí časového limitu spočítáme body. Vítězí ten, kdo jich má nejméně.", null, 6, "Hra na babu mezi kužely", 5, 3 },
                    { 56, "Ve vymezeném prostoru hrajeme babu tak, že hráči vytvoří dvojice chycením se za ruce.", null, 6, "Hra na babu ve dvojicích", 5, 3 },
                    { 57, "Hráči = atomy se pohybují na vymezeném prostoru a na signál trenéra, který řekne číslo se musí spojit dané množství atomů v molekulu.", null, 6, "Molekuly", 5, 3 },
                    { 58, "Vybijená s florbalovým úkolem - vybitý hráč provede florbalový úkol a zařadí se zpět do hry", null, 6, "Vybijená s florbalovým úkolem", 10, 5 },
                    { 59, "Ve vymezeném prostoru s různě rozmístěnýmy kužely hrajeme babu. Předáváme babu pomocí dotyku míče (nemusí být) dotykem (ne házením). Pokud někdo shodí kužel jde mimo herní hřiště a jde splnit nějaký florbalový úkol - slalom, zakončení do branky a pod.", null, 6, "Hra na babu mezi kužely s florbalovým úkolem", 10, 5 },
                    { 60, "Jeden hráč je vlk, ostatní jsou ovečky. Vlk se postaví do základní pozice na druhé straně hřiště. Po zahájení hry se snaží chytit ovečku. Nesmí se vracet ve směru pohybu. Chycená ovečka se stává vlkem. Po chycení všech oveček hra končí.", null, 5, "Na ovečky a vlky", 15, 5 },
                    { 61, "Hráče rozdělíme do družstev. Na hřišti vymezíme různě do prostoru základnu pro každé družstvo např. kruh, do kterého dáme kužely jedné barvy. Každé družstvo má svou barvu. Hráči mají za úkol přenést co nejvíce kuželů z cizích základen do té své. Vyhrává družstvo, které má po ukončení časového limitu nejvíce kuželů ve své základně.", null, 6, "Přenášení předmětů ze stanovišť", 10, 5 },
                    { 62, "Klek sedmo proti sobě předpažit pokrčmo. Cvičenci se chytí za ruce (neproplétají prsty). Tahem a tlakem do různých směrů se snaží vychýlit partnera a donutit ho k pádu.", null, 2, "Medvědí souboj", 10, 3 },
                    { 63, "Cvičenci se postaví souhlasnou nohou vpřed proti sobě na jednu čáru a chytí se přední rukou za háčky. Tahem a tlakem do různých směrů se snaží donutit partnera opustit čáru. Možnost hrát na jedné noze.", null, 2, "Vychýlení z čáry", 10, 3 },
                    { 64, "Dvojice proti sobě, stoj na jedné, ruce zkříží na prsou. Kontaktem a úhyby za současného poskakování na stojné noze se cvičenci snaží druhého donutit k opuštění žíněnky. Místo žíněnky mohou posloužit čáry na zemi nebo kužely.", null, 2, "Boj o žíněnku", 10, 3 },
                    { 65, "Klek obounož, zvednout bérce od země, ruce spojit za tělem. Kontaktem a úhyby se každý snaží, aby druhý položil bérce (špičky) na zem nebo ztrátou rovnováhy změnil pozici.", null, 2, "Souboj Eskymáků", 10, 3 },
                    { 66, "Sed pokrčmo zády k sobě, ruce na kolena. Na povel se cvičenci snaží přetlačit partnera o určitý úsek.", null, 2, "Přetlak v sedu pokrčmo", 10, 3 },
                    { 67, "Sed pokrčmo, chodidla k sobě, ruce drží spojená chodidla. Cvičenci provádí v této poloze převal přes pravou nohu, záda a přes levou nohu se zvedají opět do sedu", null, 1, "Medvídek", 5, 2 },
                    { 68, "Sed pokrčmo proti sobě se vzporem vzadu, přednožit pokrčmo pravou a spojit chodidla. Soustavným tlakem se snaží partnera posunout nebo ho donutit pokrčit nohu v koleni.", null, 2, "Předtlačování nohama", 10, 3 },
                    { 69, "Hráči se rozestaví do kruhu. Hráč s míčkem přihraje spoluhráči a hned běží tam, kde nahrál. Hráč, který přijmul přihrávku se snaží hned přihrát dalšímu.", null, 3, "Kam dáš tam jdeš", 10, 3 },
                    { 70, "Ve skupině hráčů driblujících na malém prostoru je několik hráčů bez míčku a ti se snaží obrat někoho o jeho míček.", null, 4, "Obírání o míček", 5, 3 },
                    { 71, "1. hráč běží a snaží se měnit směry, naznačovat, provádět otočky a jiné cviky, 2. hráč běží za ním a snaží se reagovat a co nejrychleji kopírovat prvního hráče", null, 2, "Kopírování", 10, 5 },
                    { 72, "kužely vyznačen pro každého hráče čtverec /jedna hrana společná/ začátek na středu čtverce. úkol - jeden hráč určuje pohyb ke kuželu, druhý se pohybuje podle prvního hráče. možnosti: 1. míček se vede k tomu samému kuželu, 2.míček se vede k protilehlému kuželu,3. míček se vede tak, aby vzdálenost mezi hráči byla stále stejná", null, 2, "Zrcadlo", 10, 5 },
                    { 73, "HRACI JSOU PO 4 V TYMU A MAJI STEJNOU BARVU DRESU.   NA PRVNÍ SIGNAL SE ZACNOU POHYBOVAT S MICKEM.NA DRUHY SIGNAL MUSI VYTVORIT TVAR DLE POKYNU TRENERA.", null, 4, "Tvary", 10, 5 },
                    { 74, "štafeta s překokem skočky nebo jiné překážky vše stejně vysoké", null, 6, "Přeskoky - jednoduché", 10, 5 },
                    { 75, "štafeta s překokem skočky nebo jiné překážky, výška se s každou další zvyšuje", null, 6, "Přeskoky - zvyšující", 10, 5 },
                    { 76, "štafeta s překokem skočky nebo jiné překážky vše stejně vysoké, dvě i více řad překážek, po přeskoku přesun na přeskok v jiné řadě", null, 6, "Přeskoky - s přesunem do stran", 10, 5 },
                    { 77, "Dvě štafety, první hráči obou štafet se postaví proti době. Hráč z určené štafety určuje kdy vyběhne. Druhý hráč se ho snaží dohonit.", null, 6, "Souboj v postřehu 1", 10, 5 },
                    { 78, "Dvě štafety, první hráči obou štafet se postaví zády sobě. Na tlesknutí se snaží co nejrychleji otočit a doběhnout k metě a zpět", null, 6, "Souboj v postřehu 2", 10, 5 },
                    { 79, "Na útočné polovině se hráči rozmístí v pravém rohu (1), vpravo na půlící čáře (2) a vlevo na půlící čáře (3). Hráč (1)  nahraje hráči podél hrazení (2) a vybíhá do středu. Hráč (2) předá míček hráči (3) a ten nahrává na střed hráči (1), který zakončuje střelbou na branku. Hráč (1) zaujme pozici (3), hráč (2) jde na původní (1) a hráč tři jde na (2).", null, 3, "Trojúhelník zakončený střelbou", 10, 5 },
                    { 80, "Na útočné polovině se hráči rozmístí v pravém rohu (1), vpravo na půlící čáře (2) a vlevo na půlící čáře (3). Hráč (1)  nahraje hráči podél hrazení (2) a vybíhá do středu. Hráč (2) předá míček hráči (3) a ten nahrává na střed hráči (1), který nahraje hráči na stanovišti (1). Hráč (1) zaujme pozici (3), hráč (2) jde na původní (1) a hráč tři jde na (2).", null, 3, "Přihrávky v trojúhelníku ", 10, 5 },
                    { 81, "Na útočné polovině se hráči rozmístí na středu vlevo u hrazení(1), uprostřed před bránou (2) na středu na půlící čáře (3). Hráč (1)  si narazí s hráčem (2) a ten jde do pravé kapsy. Hráč (1) si narazí s hráčem (3) a přebíhá do středu kde si narazí s hráčem (2) čekajícím v pravé kapse a nakonec střílí na branku.", null, 3, "3 narážečky", 10, 5 },
                    { 82, "Připravíme několik stanovišť s různou formou překážek. Hráče rozdělíme do družstev a necháme každého alespoň 3x projít stanovistě. Pak dojde ke změně stanoviště.", null, 6, "Vedení míčku na stanovištích se zakončením", 15, 10 },
                    { 83, "Hráči stojí u své branky. S míčkem se začnou pohybovat směrem kupředu a nahrávájí si. Před brankou soupeře zakončuji střelbou.", null, 2, "Přihrávky do běhu", 10, 5 },
                    { 84, "Bago pro 3. Dva hráči si nahrávají. Třetí hráč se snaží míček získat. Když jej získá, hráč, který měl jako poslední míček se stává třetím.", null, 3, "Na třetího", 10, 5 },
                    { 85, "Skok přes skočku - dopředu a zpět, bokem, skočka mezi nohama, cupitat na špičkách, po jedné noze vpřed a vzad,po jedné noze bokem, dopředu a zpět zeširoka cupitáním po špičkách", null, 1, "Skoky přes skočku", 10, 5 },
                    { 86, "První nahraje podél kůželů, druhý provede slalom – jen forhandem nebo jen backhandem, na konci provede opět přihrávku – dojde tak k obrácení rolí", null, 2, "Vedení míčku slalom", 10, 5 },
                    { 87, "Dvojice se postaví naproti sobě a každý má svůj míček. Přihrávají si s oběma míčky najednou.", null, 2, "Přihrávky 2 hráči 2 míče", 10, 5 },
                    { 88, "4 hráči se rozmístí do čtverce. První hráč přihraje diagonálně třetímu a hned běží za míčkem na pozici třetího. Hráč 3 přihrává 2 a beží na 2. Hráč 2 přihrává na 4 a běží na 4. Hráč 4 přihrává na 1 a běží na 1.", null, 5, "X-ka", 10, 5 },
                    { 89, "Hrajeme florbal 1:1", null, 2, "Miniflorbal 1:1", 15, 5 },
                    { 90, "Fotbal", null, 6, "Fotbálek", 20, 10 },
                    { 91, "Střídáme kloboučky a hráči vykonávají domluvené úkony podle významu barev. Kloboučky několika barev, kde každá barva má svůj význam. Např. červená stůj, zelená běž, oražová jdi do polohy pro start sprintu, žlutá sedni si... ", null, 6, "Semafor", 10, 5 },
                    { 92, "Florbalové dovednosti na připravené trase. Trasa a náročnost vždy stejná!", null, 1, "Test - florbal - rychlost", 20, 15 },
                    { 93, "Skok daleký, dřep, hod do dálky, hod na cíl, kotoul vpřed/vzad, přeskok překážky, šplh, předklon", null, 1, "Test - tělesná průprava", 60, 15 },
                    { 94, "Počet kliků, dřepů, přítahů do maxima", null, 1, "Test - síla", 60, 15 },
                    { 95, "Hráči rozděleni do týmů hrají vybíjenou tak, že vybíjejí jen hráče druhého týmu a to jen po alespoň 2 přihrávkách tj. 3 hráči jednotho týmu budou mít míč", null, 8, "Týmová vybíjená", 20, 10 },
                    { 96, "Hráči rozdělení do 4 týmů. Každý tým má své hnízdo v rohu čtverce. Uprostřed je líheň, ve které jsou míčky. Hráči na povel začnou po jednom z každého družstva běhat pro 1 vajíčko a donáší jej do svého hnízda. Varianta: Mohou brát všíchni i z hnízd soupeřů. Hra pak musí být na čas.", null, 12, "Souboj o vajíčka", 15, 10 },
                    { 97, "Hráči se rozdělí do 2 týmů. Jeden tým si vybere svého jednoho hráče a tomu dá rozlišovák jako ocásek a chytnou se všichni kolem ramen do kruhu. Druhý tým vyšle jednoho chytače a ten se snaží chyti ocásek hráči v bránícím družstvu. Bránící družstvo se snaží pohybem celého družstva zamezit chycení ocásku.", null, 8, "Ocásky v týmu", 15, 10 },
                    { 98, "Hráči se rozdělí na dva týmy. Z jednoho družstva se někdo vrhne mezi své protivníky. Snaží se jich co nejvíce plácnout a pak se dostat zpátky na svou polovinu. Soupeři se jej snaží chytit a nepustit zpět. Pokud se mu to přece jen povede, všichni, kterých se dotkl, jsou teď v jeho týmu.", 30, 8, "Hutututu", 20, 10 },
                    { 99, "Hráči jsou rozděleni do dvojic. Podél hřiště jsou na obou stranách připravené slalomy. Hráči vybíhají a provedou slalom na své straně. Po provedení slalomu ten rychlejší vystřelí na branku a hnd začne bránit druhého hráče. Počítají se góly.", null, 2, "Hra 1:1 po slalomech", 15, 10 },
                    { 100, "Tři skupiny hráčů, kde 1. skupina je od brankáře vpravo od mantinelů, 2. skupina je vlevo a 3. skupina je uprostřed. Hráči střílejí na brankáře ve sledu 1-2-3-2-1-3. Dbáme na správný postoj a přesuny brankáře ", null, 4, "Střídačka", 10, 5 },
                    { 101, "Střelci střílejí na branku. Před brankou jsou dorážeči. Pokud brankář nechytne míček, dorážeči se snaží co nejrychleji dorazit míček do branky. Cílem je naučit brankáře neodrážet před branku, ale míček hned rozehrát.", null, 5, "Bez dorážky", 10, 5 },
                    { 102, "2 útočníci běží společně do útoku a 1 obránce se je snaží dohnat a zabránit jim ve střele. Útočníci si mohou ale nemusí přihrát. Snaha o co nejpřimočarejš útok ve sprintu.", null, 5, "2 na 1 ve sprintu", 15, 10 },
                    { 103, "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha podél mantinelu a sbíhá si do středu, kde dostane přihrávku od spoluhráče a střílí. Druhý hráč vybíha, dostane přihrávku a střílí.... Tým, který nejdříve dá předem určený počet gólů, vyhrává.", null, 7, "Střela po přihrávce z rohu", 15, 10 },
                    { 104, "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha podél mantinelu a sbíhá si do středu trošku dále od branky, kde dostane přihrávku od spoluhráče a střílí. Druhý hráč vybíha, dostane přihrávku a střílí.... Tým, který nejdříve dá předem určený počet gólů, vyhrává.", null, 7, "Samostatný nájezd po přihrávce z rohu", 15, 10 },
                    { 105, "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha před branku, kde dostane skákavou přihrávku - žabku od spoluhráče a snaží se dát gól volejem nebo bekendem. Tým, který nejdříve dá předem určený počet gólů, vyhrává.", null, 7, "Žabka", 15, 10 },
                    { 106, "Hráči rozděleni do dvojic na středové čáře.Hrají kámen-nůžky-papír. Kdo vyhraje, tak se snaží útéct ke své základní čáře za sebou. Kdo prohrál, tak se jej snaží chytit.", null, 10, "Kámen-nůžky-papír-uteč", 10, 5 },
                    { 107, "Jeden hráč háže míčky z vaku do hřiště a ostatní hráči míčky chytají nebo sbírají a nosí co nejrychleji zpět do vaku. Hraje se na interval 1 minuty. Spočítají se míčky v poli. Vyhazovači se střídají a pak se vyhlásí vítěz s největším počtem míčků v poli po ukončení časového limitu", null, 5, "Zahazovaná", 10, 5 },
                    { 108, "Na úvod sú v poli len dvaja alebo traja hráči. Záleží od množstva detí, ktoré máte na hodine. Neodporúča sa začať v poli len s jedným hráčom, pretože to spomalí úvod hry. Ostatní žiaci stoja v zázemí a snažia sa vybiť hráča v poli. Ak sa im to podarí, za odmenu sa hráč, ktorý vybil, môže presunúť do pola svojho družstva. Cieľom vybíjanej je dostať všetkých hráčov zo zázemia do svojho pola. Na vybitie je potrebne nabiť jednou prihrávkou. Platí pravidlo troch krokov s loptou. Vybiť môže aj hráč z pola do pola súpera. V takom prípade sa vracia vybitý hráč späť do zázemia. Z pola nie je možné vybiť posledného hráča, inak by hra skončila patom.Hráči musia pochopiť, že je pre nich výhodnejšie, ak vybíjajú zo zázemia do pola súpera. Sú však situácie, kedy je potrebné doplniť zázemie súpera. Napríklad ak už v zázemí súpera ostane posledný hráč, je len otázkou času, kedy sa mu tiež podarí vybiť hráča a hra skončí.Sú situácie, kedy vo vlastnom zázemí ostane menej šikovný spoluhráč, ktorému sa nedarí nikoho vybiť. Team musí pochopiť, že je dobré, ak sa skúsený hráč nechá z pola vybiť a vráti sa späť do svojho zázemia. Môže tak svojmu menej skúsenému spoluhráčovi pomáhať, zbierať mu lopty, učiť ho a podporovať. Rozvíja sa tak aj teamová spolupráca.", null, 10, "Obrácená vybíjená", 30, 12 }
                });

            migrationBuilder.InsertData(
                table: "Tags",
                columns: new[] { "TagId", "Color", "Name", "ParentTagId" },
                values: new object[,]
                {
                    { 1, "#ffd254", "Florbalový dril", null },
                    { 3, "#27dbf5", "Hráč", null },
                    { 4, "#0989c2", "Tréninková část", null },
                    { 5, "#d9980d", "Forma", null },
                    { 6, "#17a258", "Tělesná průprava", null },
                    { 7, "#e6e9eb", "Ostatní", null },
                    { 8, "#ff9102", "Vybavení", null },
                    { 9, "#2196f3", "Hráčská kategorie", null },
                    { 10, "#666666", "Vlastní", null },
                    { 11, "#ffd254", "1 x 1", 1 },
                    { 12, "#ffd254", "2 x 2", 1 },
                    { 13, "#ffd254", "3 x 3", 1 },
                    { 14, "#ffd254", "4 x 4", 1 },
                    { 15, "#ffd254", "5 x 5", 1 },
                    { 16, "#ffd254", "2 x 3", 1 },
                    { 17, "#ffd254", "2 x 1", 1 },
                    { 18, "#27dbf5", "Brankář", 3 },
                    { 19, "#27dbf5", "Útočník", 3 },
                    { 20, "#27dbf5", "Obránce", 3 },
                    { 21, "#0989c2", "Rozehřátí", 4 },
                    { 22, "#0989c2", "Rozcvička", 4 },
                    { 23, "#0989c2", "Dril", 4 },
                    { 24, "#0989c2", "Protahování", 4 },
                    { 25, "#d9980d", "Hra", 5 },
                    { 26, "#d9980d", "Florbal", 5 },
                    { 27, "#d9980d", "Test", 5 },
                    { 28, "#d9980d", "Štafeta", 5 },
                    { 29, "#ffd254", "Střelba", 1 },
                    { 30, "#ffd254", "Přihrávka", 1 },
                    { 31, "#ffd254", "Vedení míčku", 1 },
                    { 32, "#17a258", "Ohebnost", 6 },
                    { 33, "#17a258", "Síla", 6 },
                    { 34, "#17a258", "Výbušnost", 6 },
                    { 35, "#ffd254", "Uvolňování", 1 },
                    { 36, "#17a258", "Rychlost", 6 },
                    { 37, "#e6e9eb", "Herní myšlení", 7 },
                    { 38, "#e6e9eb", "Spolupráce v týmu", 7 },
                    { 39, "#ff9102", "Florbalové míčky", 8 },
                    { 40, "#ff9102", "Florbalová branka", 8 },
                    { 41, "#ff9102", "Rozlišovací dresy", 8 },
                    { 42, "#ff9102", "Kužely", 8 },
                    { 43, "#ff9102", "Skočky", 8 },
                    { 44, "#ff9102", "Žebřík", 8 },
                    { 45, "#ff9102", "Švihadlo", 8 },
                    { 46, "#ff9102", "Fotbalový míč", 8 },
                    { 47, "#2196f3", "U7 - předpřípravka", 9 },
                    { 48, "#2196f3", "U9 - přípravka", 9 },
                    { 49, "#2196f3", "U11 - elévi", 9 },
                    { 50, "#2196f3", "U13 - ml. žáci", 9 },
                    { 51, "#2196f3", "U15 - st. žáci", 9 },
                    { 52, "#2196f3", "U17 - dorost", 9 },
                    { 53, "#2196f3", "U21 - junioři ", 9 },
                    { 54, "#2196f3", "Muži", 9 }
                });

            migrationBuilder.InsertData(
                table: "ActivityTags",
                columns: new[] { "ActivityId", "TagId" },
                values: new object[,]
                {
                    { 1, 21 },
                    { 1, 23 },
                    { 1, 25 },
                    { 1, 38 },
                    { 1, 49 },
                    { 1, 50 },
                    { 1, 51 },
                    { 1, 52 },
                    { 1, 53 },
                    { 1, 54 },
                    { 2, 21 },
                    { 2, 25 },
                    { 2, 38 },
                    { 2, 41 },
                    { 2, 49 },
                    { 2, 50 },
                    { 2, 51 },
                    { 3, 13 },
                    { 3, 18 },
                    { 3, 19 },
                    { 3, 20 },
                    { 3, 23 },
                    { 3, 25 },
                    { 3, 26 },
                    { 3, 38 },
                    { 3, 39 },
                    { 3, 40 },
                    { 3, 41 },
                    { 3, 49 },
                    { 3, 50 },
                    { 3, 51 },
                    { 4, 11 },
                    { 4, 19 },
                    { 4, 20 },
                    { 4, 21 },
                    { 4, 23 },
                    { 4, 25 },
                    { 4, 26 },
                    { 4, 31 },
                    { 4, 39 },
                    { 4, 49 },
                    { 4, 50 },
                    { 4, 51 },
                    { 5, 21 },
                    { 5, 23 },
                    { 5, 24 },
                    { 5, 37 },
                    { 5, 49 },
                    { 5, 50 },
                    { 5, 51 },
                    { 6, 22 },
                    { 6, 32 },
                    { 6, 49 },
                    { 6, 50 },
                    { 6, 51 },
                    { 7, 22 },
                    { 7, 32 },
                    { 7, 49 },
                    { 7, 50 },
                    { 7, 51 },
                    { 8, 22 },
                    { 8, 32 },
                    { 8, 49 },
                    { 8, 50 },
                    { 8, 51 },
                    { 9, 22 },
                    { 9, 32 },
                    { 9, 49 },
                    { 9, 50 },
                    { 9, 51 },
                    { 10, 22 },
                    { 10, 32 },
                    { 10, 49 },
                    { 10, 50 },
                    { 10, 51 },
                    { 11, 22 },
                    { 11, 32 },
                    { 11, 49 },
                    { 11, 50 },
                    { 11, 51 },
                    { 12, 22 },
                    { 12, 32 },
                    { 12, 49 },
                    { 12, 50 },
                    { 12, 51 },
                    { 13, 22 },
                    { 13, 32 },
                    { 13, 49 },
                    { 13, 50 },
                    { 13, 51 },
                    { 14, 22 },
                    { 14, 32 },
                    { 14, 49 },
                    { 14, 50 },
                    { 14, 51 },
                    { 15, 22 },
                    { 15, 32 },
                    { 15, 49 },
                    { 15, 50 },
                    { 15, 51 },
                    { 16, 22 },
                    { 16, 32 },
                    { 16, 49 },
                    { 16, 50 },
                    { 16, 51 },
                    { 17, 22 },
                    { 17, 32 },
                    { 17, 49 },
                    { 17, 50 },
                    { 17, 51 },
                    { 18, 22 },
                    { 18, 32 },
                    { 18, 49 },
                    { 18, 50 },
                    { 18, 51 },
                    { 19, 22 },
                    { 19, 32 },
                    { 19, 49 },
                    { 19, 50 },
                    { 19, 51 },
                    { 20, 22 },
                    { 20, 23 },
                    { 20, 32 },
                    { 20, 49 },
                    { 20, 50 },
                    { 20, 51 },
                    { 21, 12 },
                    { 21, 19 },
                    { 21, 21 },
                    { 21, 23 },
                    { 21, 25 },
                    { 21, 30 },
                    { 21, 38 },
                    { 21, 46 },
                    { 21, 49 },
                    { 21, 50 },
                    { 21, 51 },
                    { 22, 12 },
                    { 22, 19 },
                    { 22, 21 },
                    { 22, 23 },
                    { 22, 25 },
                    { 22, 30 },
                    { 22, 36 },
                    { 22, 38 },
                    { 22, 39 },
                    { 22, 49 },
                    { 22, 50 },
                    { 22, 51 },
                    { 23, 21 },
                    { 23, 25 },
                    { 23, 36 },
                    { 23, 49 },
                    { 23, 50 },
                    { 23, 51 },
                    { 24, 21 },
                    { 24, 23 },
                    { 24, 25 },
                    { 24, 36 },
                    { 24, 38 },
                    { 24, 42 },
                    { 24, 49 },
                    { 24, 50 },
                    { 24, 51 },
                    { 25, 21 },
                    { 25, 23 },
                    { 25, 25 },
                    { 25, 34 },
                    { 25, 36 },
                    { 25, 49 },
                    { 25, 50 },
                    { 25, 51 },
                    { 26, 11 },
                    { 26, 25 },
                    { 26, 35 },
                    { 26, 36 },
                    { 26, 39 },
                    { 26, 49 },
                    { 26, 50 },
                    { 26, 51 },
                    { 27, 42 },
                    { 27, 49 },
                    { 27, 50 },
                    { 27, 51 },
                    { 28, 21 },
                    { 28, 23 },
                    { 28, 25 },
                    { 28, 32 },
                    { 28, 49 },
                    { 28, 50 },
                    { 28, 51 },
                    { 29, 13 },
                    { 29, 14 },
                    { 29, 15 },
                    { 29, 21 },
                    { 29, 23 },
                    { 29, 25 },
                    { 29, 34 },
                    { 29, 36 },
                    { 29, 38 },
                    { 29, 39 },
                    { 29, 40 },
                    { 29, 41 },
                    { 29, 49 },
                    { 29, 50 },
                    { 29, 51 },
                    { 30, 21 },
                    { 30, 23 },
                    { 30, 25 },
                    { 30, 49 },
                    { 30, 50 },
                    { 30, 51 },
                    { 31, 23 },
                    { 31, 25 },
                    { 31, 28 },
                    { 31, 32 },
                    { 31, 49 },
                    { 31, 50 },
                    { 31, 51 },
                    { 32, 23 },
                    { 32, 25 },
                    { 32, 32 },
                    { 32, 33 },
                    { 32, 49 },
                    { 32, 50 },
                    { 32, 51 },
                    { 33, 23 },
                    { 33, 25 },
                    { 33, 38 },
                    { 33, 49 },
                    { 33, 50 },
                    { 33, 51 },
                    { 34, 23 },
                    { 34, 25 },
                    { 34, 38 },
                    { 34, 49 },
                    { 34, 50 },
                    { 34, 51 },
                    { 35, 23 },
                    { 35, 25 },
                    { 35, 33 },
                    { 35, 34 },
                    { 35, 36 },
                    { 35, 38 },
                    { 35, 49 },
                    { 35, 50 },
                    { 35, 51 },
                    { 36, 23 },
                    { 36, 25 },
                    { 36, 33 },
                    { 36, 49 },
                    { 36, 50 },
                    { 36, 51 },
                    { 37, 25 },
                    { 37, 33 },
                    { 37, 46 },
                    { 37, 49 },
                    { 37, 50 },
                    { 37, 51 },
                    { 38, 25 },
                    { 38, 33 },
                    { 38, 49 },
                    { 38, 50 },
                    { 38, 51 },
                    { 39, 25 },
                    { 39, 33 },
                    { 39, 49 },
                    { 39, 50 },
                    { 39, 51 },
                    { 40, 25 },
                    { 40, 49 },
                    { 40, 50 },
                    { 40, 51 },
                    { 41, 25 },
                    { 41, 49 },
                    { 41, 50 },
                    { 41, 51 },
                    { 42, 25 },
                    { 42, 49 },
                    { 42, 50 },
                    { 42, 51 },
                    { 43, 25 },
                    { 43, 49 },
                    { 43, 50 },
                    { 43, 51 },
                    { 44, 21 },
                    { 44, 23 },
                    { 44, 25 },
                    { 44, 26 },
                    { 44, 32 },
                    { 44, 36 },
                    { 44, 39 },
                    { 44, 49 },
                    { 44, 50 },
                    { 44, 51 },
                    { 45, 23 },
                    { 45, 25 },
                    { 45, 49 },
                    { 45, 50 },
                    { 45, 51 },
                    { 46, 23 },
                    { 46, 25 },
                    { 46, 28 },
                    { 46, 36 },
                    { 46, 38 },
                    { 46, 46 },
                    { 46, 49 },
                    { 46, 50 },
                    { 46, 51 },
                    { 47, 21 },
                    { 47, 23 },
                    { 47, 25 },
                    { 47, 36 },
                    { 47, 39 },
                    { 47, 49 },
                    { 47, 50 },
                    { 47, 51 },
                    { 48, 23 },
                    { 48, 25 },
                    { 48, 28 },
                    { 48, 36 },
                    { 48, 38 },
                    { 48, 46 },
                    { 48, 49 },
                    { 48, 50 },
                    { 48, 51 },
                    { 49, 23 },
                    { 49, 25 },
                    { 49, 28 },
                    { 49, 36 },
                    { 49, 49 },
                    { 49, 50 },
                    { 49, 51 },
                    { 50, 21 },
                    { 50, 25 },
                    { 50, 36 },
                    { 50, 49 },
                    { 50, 50 },
                    { 50, 51 },
                    { 51, 21 },
                    { 51, 23 },
                    { 51, 25 },
                    { 51, 36 },
                    { 51, 38 },
                    { 51, 49 },
                    { 51, 50 },
                    { 51, 51 },
                    { 52, 21 },
                    { 52, 23 },
                    { 52, 25 },
                    { 52, 36 },
                    { 52, 38 },
                    { 52, 49 },
                    { 52, 50 },
                    { 52, 51 },
                    { 53, 21 },
                    { 53, 23 },
                    { 53, 25 },
                    { 53, 36 },
                    { 53, 38 },
                    { 53, 49 },
                    { 53, 50 },
                    { 53, 51 },
                    { 54, 25 },
                    { 54, 49 },
                    { 54, 50 },
                    { 54, 51 },
                    { 55, 25 },
                    { 55, 49 },
                    { 55, 50 },
                    { 55, 51 },
                    { 56, 25 },
                    { 56, 49 },
                    { 56, 50 },
                    { 56, 51 },
                    { 57, 25 },
                    { 57, 49 },
                    { 57, 50 },
                    { 57, 51 },
                    { 58, 21 },
                    { 58, 23 },
                    { 58, 25 },
                    { 58, 26 },
                    { 58, 36 },
                    { 58, 39 },
                    { 58, 40 },
                    { 58, 42 },
                    { 58, 49 },
                    { 58, 50 },
                    { 58, 51 },
                    { 59, 25 },
                    { 59, 49 },
                    { 59, 50 },
                    { 59, 51 },
                    { 60, 11 },
                    { 60, 19 },
                    { 60, 20 },
                    { 60, 21 },
                    { 60, 23 },
                    { 60, 25 },
                    { 60, 31 },
                    { 60, 49 },
                    { 60, 50 },
                    { 60, 51 },
                    { 61, 49 },
                    { 61, 50 },
                    { 61, 51 },
                    { 62, 11 },
                    { 62, 25 },
                    { 62, 32 },
                    { 62, 33 },
                    { 62, 49 },
                    { 62, 50 },
                    { 62, 51 },
                    { 63, 11 },
                    { 63, 25 },
                    { 63, 32 },
                    { 63, 33 },
                    { 63, 49 },
                    { 63, 50 },
                    { 63, 51 },
                    { 65, 11 },
                    { 65, 25 },
                    { 65, 32 },
                    { 65, 33 },
                    { 65, 49 },
                    { 65, 50 },
                    { 65, 51 },
                    { 66, 11 },
                    { 66, 25 },
                    { 66, 32 },
                    { 66, 33 },
                    { 66, 49 },
                    { 66, 50 },
                    { 66, 51 },
                    { 67, 32 },
                    { 67, 33 },
                    { 67, 49 },
                    { 67, 50 },
                    { 67, 51 },
                    { 68, 11 },
                    { 68, 25 },
                    { 68, 32 },
                    { 68, 33 },
                    { 68, 49 },
                    { 68, 50 },
                    { 68, 51 },
                    { 69, 19 },
                    { 69, 20 },
                    { 69, 23 },
                    { 69, 25 },
                    { 69, 26 },
                    { 69, 30 },
                    { 69, 36 },
                    { 69, 38 },
                    { 69, 39 },
                    { 69, 49 },
                    { 69, 50 },
                    { 69, 51 },
                    { 70, 11 },
                    { 70, 19 },
                    { 70, 20 },
                    { 70, 21 },
                    { 70, 23 },
                    { 70, 25 },
                    { 70, 26 },
                    { 70, 31 },
                    { 70, 39 },
                    { 70, 49 },
                    { 70, 50 },
                    { 70, 51 },
                    { 71, 11 },
                    { 71, 23 },
                    { 71, 26 },
                    { 71, 35 },
                    { 71, 39 },
                    { 71, 49 },
                    { 71, 50 },
                    { 71, 51 },
                    { 72, 11 },
                    { 72, 19 },
                    { 72, 20 },
                    { 72, 23 },
                    { 72, 26 },
                    { 72, 31 },
                    { 72, 49 },
                    { 72, 50 },
                    { 72, 51 },
                    { 73, 19 },
                    { 73, 20 },
                    { 73, 23 },
                    { 73, 26 },
                    { 73, 31 },
                    { 73, 39 },
                    { 73, 49 },
                    { 73, 50 },
                    { 73, 51 },
                    { 74, 28 },
                    { 74, 34 },
                    { 74, 43 },
                    { 74, 49 },
                    { 74, 50 },
                    { 74, 51 },
                    { 75, 28 },
                    { 75, 34 },
                    { 75, 43 },
                    { 75, 49 },
                    { 75, 50 },
                    { 75, 51 },
                    { 76, 28 },
                    { 76, 34 },
                    { 76, 43 },
                    { 76, 49 },
                    { 76, 50 },
                    { 76, 51 },
                    { 77, 28 },
                    { 77, 34 },
                    { 77, 35 },
                    { 77, 36 },
                    { 77, 49 },
                    { 77, 50 },
                    { 77, 51 },
                    { 78, 28 },
                    { 78, 34 },
                    { 78, 35 },
                    { 78, 36 },
                    { 78, 49 },
                    { 78, 50 },
                    { 78, 51 },
                    { 79, 19 },
                    { 79, 23 },
                    { 79, 26 },
                    { 79, 29 },
                    { 79, 30 },
                    { 79, 36 },
                    { 79, 38 },
                    { 79, 39 },
                    { 79, 40 },
                    { 79, 49 },
                    { 79, 50 },
                    { 79, 51 },
                    { 80, 19 },
                    { 80, 23 },
                    { 80, 26 },
                    { 80, 29 },
                    { 80, 30 },
                    { 80, 36 },
                    { 80, 38 },
                    { 80, 39 },
                    { 80, 40 },
                    { 80, 49 },
                    { 80, 50 },
                    { 80, 51 },
                    { 81, 19 },
                    { 81, 23 },
                    { 81, 26 },
                    { 81, 29 },
                    { 81, 30 },
                    { 81, 36 },
                    { 81, 38 },
                    { 81, 39 },
                    { 81, 40 },
                    { 81, 49 },
                    { 81, 50 },
                    { 81, 51 },
                    { 82, 18 },
                    { 82, 19 },
                    { 82, 20 },
                    { 82, 23 },
                    { 82, 26 },
                    { 82, 28 },
                    { 82, 29 },
                    { 82, 30 },
                    { 82, 31 },
                    { 82, 36 },
                    { 82, 39 },
                    { 82, 40 },
                    { 82, 42 },
                    { 82, 43 },
                    { 82, 44 },
                    { 82, 49 },
                    { 82, 50 },
                    { 82, 51 },
                    { 83, 19 },
                    { 83, 23 },
                    { 83, 26 },
                    { 83, 29 },
                    { 83, 30 },
                    { 83, 31 },
                    { 83, 36 },
                    { 83, 39 },
                    { 83, 40 },
                    { 83, 49 },
                    { 83, 50 },
                    { 83, 51 },
                    { 84, 11 },
                    { 84, 19 },
                    { 84, 20 },
                    { 84, 21 },
                    { 84, 25 },
                    { 84, 26 },
                    { 84, 30 },
                    { 84, 35 },
                    { 84, 36 },
                    { 84, 38 },
                    { 84, 39 },
                    { 84, 49 },
                    { 84, 50 },
                    { 84, 51 },
                    { 85, 23 },
                    { 85, 32 },
                    { 85, 34 },
                    { 85, 43 },
                    { 85, 49 },
                    { 85, 50 },
                    { 85, 51 },
                    { 86, 19 },
                    { 86, 20 },
                    { 86, 23 },
                    { 86, 26 },
                    { 86, 28 },
                    { 86, 30 },
                    { 86, 31 },
                    { 86, 39 },
                    { 86, 42 },
                    { 86, 49 },
                    { 86, 50 },
                    { 86, 51 },
                    { 87, 19 },
                    { 87, 20 },
                    { 87, 23 },
                    { 87, 26 },
                    { 87, 38 },
                    { 87, 39 },
                    { 87, 49 },
                    { 87, 50 },
                    { 87, 51 },
                    { 88, 19 },
                    { 88, 20 },
                    { 88, 23 },
                    { 88, 26 },
                    { 88, 30 },
                    { 88, 36 },
                    { 88, 38 },
                    { 88, 39 },
                    { 88, 49 },
                    { 88, 50 },
                    { 88, 51 },
                    { 89, 11 },
                    { 89, 19 },
                    { 89, 20 },
                    { 89, 23 },
                    { 89, 25 },
                    { 89, 26 },
                    { 89, 29 },
                    { 89, 31 },
                    { 89, 36 },
                    { 89, 37 },
                    { 89, 39 },
                    { 89, 40 },
                    { 89, 49 },
                    { 89, 50 },
                    { 89, 51 },
                    { 90, 21 },
                    { 90, 23 },
                    { 90, 25 },
                    { 90, 36 },
                    { 90, 37 },
                    { 90, 38 },
                    { 90, 40 },
                    { 90, 41 },
                    { 90, 46 },
                    { 90, 49 },
                    { 90, 50 },
                    { 90, 51 },
                    { 91, 23 },
                    { 91, 49 },
                    { 91, 50 },
                    { 91, 51 },
                    { 92, 23 },
                    { 92, 26 },
                    { 92, 27 },
                    { 92, 29 },
                    { 92, 30 },
                    { 92, 31 },
                    { 92, 36 },
                    { 92, 39 },
                    { 92, 40 },
                    { 92, 42 },
                    { 92, 49 },
                    { 92, 50 },
                    { 92, 51 },
                    { 93, 23 },
                    { 93, 27 },
                    { 93, 35 },
                    { 93, 39 },
                    { 93, 40 },
                    { 93, 42 },
                    { 93, 43 },
                    { 93, 44 },
                    { 93, 45 },
                    { 93, 46 },
                    { 93, 49 },
                    { 93, 50 },
                    { 93, 51 },
                    { 94, 23 },
                    { 94, 27 },
                    { 94, 33 },
                    { 94, 37 },
                    { 94, 49 },
                    { 94, 50 },
                    { 94, 51 },
                    { 95, 13 },
                    { 95, 14 },
                    { 95, 15 },
                    { 95, 16 },
                    { 95, 17 },
                    { 95, 21 },
                    { 95, 23 },
                    { 95, 25 },
                    { 95, 30 },
                    { 95, 35 },
                    { 95, 36 },
                    { 95, 38 },
                    { 95, 41 },
                    { 95, 46 },
                    { 95, 47 },
                    { 95, 48 },
                    { 95, 49 },
                    { 95, 50 },
                    { 95, 51 },
                    { 95, 52 },
                    { 95, 53 },
                    { 95, 54 },
                    { 96, 21 },
                    { 96, 22 },
                    { 96, 23 },
                    { 96, 25 },
                    { 96, 28 },
                    { 96, 36 },
                    { 96, 38 },
                    { 96, 39 },
                    { 96, 47 },
                    { 96, 48 },
                    { 96, 49 },
                    { 96, 50 },
                    { 96, 51 },
                    { 96, 52 },
                    { 96, 53 },
                    { 96, 54 },
                    { 97, 21 },
                    { 97, 23 },
                    { 97, 25 },
                    { 97, 36 },
                    { 97, 38 },
                    { 97, 41 },
                    { 97, 49 },
                    { 97, 50 },
                    { 97, 51 },
                    { 97, 52 },
                    { 97, 53 },
                    { 97, 54 },
                    { 98, 23 },
                    { 98, 25 },
                    { 98, 33 },
                    { 98, 34 },
                    { 98, 35 },
                    { 98, 36 },
                    { 98, 38 },
                    { 99, 11 },
                    { 99, 18 },
                    { 99, 19 },
                    { 99, 20 },
                    { 99, 23 },
                    { 99, 26 },
                    { 99, 29 },
                    { 99, 31 },
                    { 99, 34 },
                    { 99, 35 },
                    { 99, 36 },
                    { 99, 39 },
                    { 99, 40 },
                    { 99, 42 },
                    { 99, 48 },
                    { 99, 49 },
                    { 99, 50 },
                    { 99, 51 },
                    { 99, 52 },
                    { 99, 53 },
                    { 99, 54 },
                    { 100, 18 },
                    { 100, 19 },
                    { 100, 22 },
                    { 100, 23 },
                    { 100, 26 },
                    { 100, 29 },
                    { 100, 36 },
                    { 100, 39 },
                    { 100, 40 },
                    { 100, 49 },
                    { 100, 50 },
                    { 100, 51 },
                    { 100, 52 },
                    { 100, 53 },
                    { 100, 54 },
                    { 101, 18 },
                    { 101, 19 },
                    { 101, 23 },
                    { 101, 26 },
                    { 101, 29 },
                    { 101, 34 },
                    { 101, 36 },
                    { 101, 39 },
                    { 101, 40 },
                    { 101, 49 },
                    { 101, 50 },
                    { 101, 51 },
                    { 101, 52 },
                    { 101, 53 },
                    { 101, 54 },
                    { 102, 11 },
                    { 102, 16 },
                    { 102, 18 },
                    { 102, 19 },
                    { 102, 20 },
                    { 102, 23 },
                    { 102, 26 },
                    { 102, 29 },
                    { 102, 30 },
                    { 102, 31 },
                    { 102, 34 },
                    { 102, 36 },
                    { 102, 37 },
                    { 102, 38 },
                    { 102, 39 },
                    { 102, 40 },
                    { 102, 46 },
                    { 102, 49 },
                    { 102, 50 },
                    { 102, 51 },
                    { 102, 52 },
                    { 102, 53 },
                    { 102, 54 },
                    { 103, 18 },
                    { 103, 19 },
                    { 103, 22 },
                    { 103, 23 },
                    { 103, 25 },
                    { 103, 26 },
                    { 103, 29 },
                    { 103, 30 },
                    { 103, 34 },
                    { 103, 36 },
                    { 103, 38 },
                    { 103, 39 },
                    { 103, 40 },
                    { 103, 49 },
                    { 103, 50 },
                    { 103, 51 },
                    { 103, 52 },
                    { 103, 53 },
                    { 103, 54 },
                    { 104, 18 },
                    { 104, 19 },
                    { 104, 22 },
                    { 104, 23 },
                    { 104, 25 },
                    { 104, 26 },
                    { 104, 29 },
                    { 104, 30 },
                    { 104, 34 },
                    { 104, 36 },
                    { 104, 38 },
                    { 104, 39 },
                    { 104, 40 },
                    { 104, 49 },
                    { 104, 50 },
                    { 104, 51 },
                    { 104, 52 },
                    { 104, 53 },
                    { 104, 54 },
                    { 105, 18 },
                    { 105, 19 },
                    { 105, 22 },
                    { 105, 23 },
                    { 105, 25 },
                    { 105, 26 },
                    { 105, 29 },
                    { 105, 30 },
                    { 105, 34 },
                    { 105, 36 },
                    { 105, 38 },
                    { 105, 39 },
                    { 105, 40 },
                    { 105, 49 },
                    { 105, 50 },
                    { 105, 51 },
                    { 105, 52 },
                    { 105, 53 },
                    { 105, 54 },
                    { 106, 11 },
                    { 106, 21 },
                    { 106, 22 },
                    { 106, 23 },
                    { 106, 25 },
                    { 106, 36 },
                    { 106, 47 },
                    { 106, 48 },
                    { 106, 49 },
                    { 106, 50 },
                    { 106, 51 },
                    { 106, 52 },
                    { 106, 53 },
                    { 106, 54 },
                    { 107, 21 },
                    { 107, 22 },
                    { 107, 25 },
                    { 107, 26 },
                    { 107, 31 },
                    { 107, 36 },
                    { 107, 38 },
                    { 107, 39 },
                    { 107, 47 },
                    { 107, 48 },
                    { 107, 49 },
                    { 107, 50 },
                    { 107, 51 },
                    { 107, 52 },
                    { 107, 53 },
                    { 107, 54 },
                    { 108, 21 },
                    { 108, 25 },
                    { 108, 36 },
                    { 108, 38 },
                    { 108, 46 },
                    { 108, 48 },
                    { 108, 49 },
                    { 108, 50 },
                    { 108, 51 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_ActivityTags_TagId",
                table: "ActivityTags",
                column: "TagId");

            migrationBuilder.CreateIndex(
                name: "IX_Tags_ParentTagId",
                table: "Tags",
                column: "ParentTagId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ActivityTags");

            migrationBuilder.DropTable(
                name: "Activities");

            migrationBuilder.DropTable(
                name: "Tags");
        }
    }
}
