// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingDataAccess.DbContexts;

#nullable disable

namespace TrainingDataAccess.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20230317073756_Foreig")]
    partial class Foreig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("TrainingDataAccess.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonsMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Description = "Děti se rozdělí do dvou družstev, děti se drží za pas, první v řadě je hlava draka, poslední je ocas draka, družstva stojí asi 10 metrů od sebe, na povel se snaží hlava draka chytit ocas draka protihráče",
                            DurationMin = 4,
                            Name = "Dračí zápasy",
                            PersonsMax = 10,
                            PersonsMin = 5
                        },
                        new
                        {
                            ActivityId = 2,
                            Description = "Čert má z rozlišováku připevněný ocas a snaží se všechny ostatní hráče polapit. Pokud někoho chytne, jde mimo hřiště.Hráči se snaží vzít čertovy ocas a osvobodit tak již chycené hráče. Po osvobození hráčů hra končí a stává se čertem hráč, který vzal čertovy ocas.",
                            DurationMin = 5,
                            Name = "Čertovská honička",
                            PersonsMax = 15,
                            PersonsMin = 5
                        },
                        new
                        {
                            ActivityId = 3,
                            Description = "",
                            DurationMax = 12,
                            DurationMin = 6,
                            Name = "Florbal 3x3",
                            PersonsMax = 20,
                            PersonsMin = 10
                        },
                        new
                        {
                            ActivityId = 4,
                            Description = "Všichni mají florbalky. Každá ovečka má míček. Vlk se postaví do základní pozice na druhé straně hřiště. Po zahájení hry se saží chytit ovečku tak, že ji vezme florbalově čistě míček. Nesmí se vracet ve směru pohybu. Ovečka , která přišla o míček se stává vlkem, Po chycení všech oveček hra končí.",
                            DurationMin = 5,
                            Name = "Na ovečky a vlky s florbalkou a míčkem",
                            PersonsMax = 15,
                            PersonsMin = 5
                        },
                        new
                        {
                            ActivityId = 101,
                            Description = "Střelci střílejí na branku. Před brankou jsou dorážeči. Pokud brankář nechytne míček, dorážeči se snaží co nejrychleji dorazit míček do branky. Cílem je naučit brankáře neodrážet před branku, ale míček hned rozehrát.",
                            DurationMin = 5,
                            Name = "Bez dorážky",
                            PersonsMax = 10,
                            PersonsMin = 5
                        },
                        new
                        {
                            ActivityId = 102,
                            Description = "2 útočníci běží společně do útoku a 1 obránce se je snaží dohnat a zabránit jim ve střele. Útočníci si mohou ale nemusí přihrát. Snaha o co nejpřimočarejš útok ve sprintu.",
                            DurationMin = 5,
                            Name = "2 na 1 ve sprintu",
                            PersonsMax = 15,
                            PersonsMin = 10
                        },
                        new
                        {
                            ActivityId = 103,
                            Description = "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha podél mantinelu a sbíhá si do středu, kde dostane přihrávku od spoluhráče a střílí. Druhý hráč vybíha, dostane přihrávku a střílí.... Tým, který nejdříve dá předem určený počet gólů, vyhrává.",
                            DurationMin = 7,
                            Name = "Střela po přihrávce z rohu",
                            PersonsMax = 15,
                            PersonsMin = 10
                        },
                        new
                        {
                            ActivityId = 104,
                            Description = "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha podél mantinelu a sbíhá si do středu trošku dále od branky, kde dostane přihrávku od spoluhráče a střílí. Druhý hráč vybíha, dostane přihrávku a střílí.... Tým, který nejdříve dá předem určený počet gólů, vyhrává.",
                            DurationMin = 7,
                            Name = "Samostatný nájezd po přihrávce z rohu",
                            PersonsMax = 15,
                            PersonsMin = 10
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.ActivityTag", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ActivityTags", (string)null);

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            TagId = 21
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 52
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 53
                        },
                        new
                        {
                            ActivityId = 1,
                            TagId = 54
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 21
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 41
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 2,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 13
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 18
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 20
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 40
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 41
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 3,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 11
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 20
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 21
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 31
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 4,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 18
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 29
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 34
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 36
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 40
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 52
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 53
                        },
                        new
                        {
                            ActivityId = 101,
                            TagId = 54
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 11
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 16
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 18
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 20
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 29
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 30
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 31
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 34
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 36
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 37
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 40
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 46
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 52
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 53
                        },
                        new
                        {
                            ActivityId = 102,
                            TagId = 54
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 18
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 29
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 30
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 34
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 36
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 40
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 52
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 53
                        },
                        new
                        {
                            ActivityId = 103,
                            TagId = 54
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 18
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 19
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 22
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 23
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 25
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 26
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 29
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 30
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 34
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 36
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 38
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 39
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 40
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 49
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 50
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 51
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 52
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 53
                        },
                        new
                        {
                            ActivityId = 104,
                            TagId = 54
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId");

                    b.HasIndex("ParentTagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Color = "#ffd254",
                            Name = "Florbalový dril"
                        },
                        new
                        {
                            TagId = 11,
                            Color = "#ffd254",
                            Name = "1 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 12,
                            Color = "#ffd254",
                            Name = "2 x 2",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 13,
                            Color = "#ffd254",
                            Name = "3 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 14,
                            Color = "#ffd254",
                            Name = "4 x 4",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 15,
                            Color = "#ffd254",
                            Name = "5 x 5",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 16,
                            Color = "#ffd254",
                            Name = "2 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 17,
                            Color = "#ffd254",
                            Name = "2 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 29,
                            Color = "#ffd254",
                            Name = "Střelba",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 30,
                            Color = "#ffd254",
                            Name = "Přihrávka",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 31,
                            Color = "#ffd254",
                            Name = "Vedení míčku",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 35,
                            Color = "#ffd254",
                            Name = "Uvolňování",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 5,
                            Color = "#d9980d",
                            Name = "Forma"
                        },
                        new
                        {
                            TagId = 25,
                            Color = "#d9980d",
                            Name = "Hra",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 26,
                            Color = "#d9980d",
                            Name = "Florbal",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 27,
                            Color = "#d9980d",
                            Name = "Test",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 28,
                            Color = "#d9980d",
                            Name = "Štafeta",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 3,
                            Color = "#27dbf5",
                            Name = "Hráč"
                        },
                        new
                        {
                            TagId = 18,
                            Color = "#27dbf5",
                            Name = "Brankář",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 19,
                            Color = "#27dbf5",
                            Name = "Útočník",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 20,
                            Color = "#27dbf5",
                            Name = "Obránce",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 9,
                            Color = "#2196f3",
                            Name = "Hráčská kategorie"
                        },
                        new
                        {
                            TagId = 47,
                            Color = "#2196f3",
                            Name = "U7 - předpřípravka",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 48,
                            Color = "#2196f3",
                            Name = "U9 - přípravka",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 49,
                            Color = "#2196f3",
                            Name = "U11 - elévi",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 50,
                            Color = "#2196f3",
                            Name = "U13 - ml. žáci",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 51,
                            Color = "#2196f3",
                            Name = "U15 - st. žáci",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 52,
                            Color = "#2196f3",
                            Name = "U17 - dorost",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 53,
                            Color = "#2196f3",
                            Name = "U21 - junioři ",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 54,
                            Color = "#2196f3",
                            Name = "Muži",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 6,
                            Color = "#17a258",
                            Name = "Tělesná průprava"
                        },
                        new
                        {
                            TagId = 32,
                            Color = "#17a258",
                            Name = "Ohebnost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 33,
                            Color = "#17a258",
                            Name = "Síla",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 34,
                            Color = "#17a258",
                            Name = "Výbušnost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 36,
                            Color = "#17a258",
                            Name = "Rychlost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 4,
                            Color = "#0989c2",
                            Name = "Tréninková část"
                        },
                        new
                        {
                            TagId = 21,
                            Color = "#0989c2",
                            Name = "Rozehřátí",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 22,
                            Color = "#0989c2",
                            Name = "Rozcvička",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 23,
                            Color = "#0989c2",
                            Name = "Dril",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 24,
                            Color = "#0989c2",
                            Name = "Protahování",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 8,
                            Color = "#ff9102",
                            Name = "Vybavení"
                        },
                        new
                        {
                            TagId = 39,
                            Color = "#ff9102",
                            Name = "Florbalové míčky",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 40,
                            Color = "#ff9102",
                            Name = "Florbalová branka",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 41,
                            Color = "#ff9102",
                            Name = "Rozlišovací dresy",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 42,
                            Color = "#ff9102",
                            Name = "Kužely",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 43,
                            Color = "#ff9102",
                            Name = "Skočky",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 44,
                            Color = "#ff9102",
                            Name = "Žebřík",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 45,
                            Color = "#ff9102",
                            Name = "Švihadlo",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 46,
                            Color = "#ff9102",
                            Name = "Fotbalový míč",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 7,
                            Color = "#e6e9eb",
                            Name = "Ostatní"
                        },
                        new
                        {
                            TagId = 37,
                            Color = "#e6e9eb",
                            Name = "Herní myšlení",
                            ParentTagId = 7
                        },
                        new
                        {
                            TagId = 38,
                            Color = "#e6e9eb",
                            Name = "Spolupráce v týmu",
                            ParentTagId = 7
                        },
                        new
                        {
                            TagId = 10,
                            Color = "#666666",
                            Name = "Vlastní"
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Persons")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            TrainingId = 1,
                            Description = "Pohyb a hra",
                            Duration = 90,
                            Name = "Pondělí",
                            Persons = 20
                        },
                        new
                        {
                            TrainingId = 2,
                            Description = "Dril",
                            Duration = 90,
                            Name = "Druhý",
                            Persons = 30
                        },
                        new
                        {
                            TrainingId = 3,
                            Description = "Hra",
                            Duration = 60,
                            Name = "Třetí",
                            Persons = 30
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingPart", b =>
                {
                    b.Property<int>("TrainingPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainingPartId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingParts");

                    b.HasData(
                        new
                        {
                            TrainingPartId = 1,
                            Description = "",
                            Duration = 10,
                            Name = "Part1",
                            Order = 0,
                            TrainingId = 1
                        },
                        new
                        {
                            TrainingPartId = 2,
                            Description = "",
                            Duration = 20,
                            Name = "Part2",
                            Order = 1,
                            TrainingId = 1
                        });
                });

            modelBuilder.Entity("TrainingDataAccess.Models.ActivityTag", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Activity", "Activity")
                        .WithMany("ActivityTags")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingDataAccess.Models.Tag", "Tag")
                        .WithMany("ActivityTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Tag", "ParentTag")
                        .WithMany()
                        .HasForeignKey("ParentTagId");

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.TrainingPart", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Training", "Training")
                        .WithMany("TrainingParts")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Activity", b =>
                {
                    b.Navigation("ActivityTags");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.Navigation("ActivityTags");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Training", b =>
                {
                    b.Navigation("TrainingParts");
                });
#pragma warning restore 612, 618
        }
    }
}
