// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingDataAccess.DbContexts;

#nullable disable

namespace TrainingDataAccess.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20230122204805_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("ActivityTag", b =>
                {
                    b.Property<int>("ActivitiesActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivitiesActivityId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("ActivityTag");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonsMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.Property<int?>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId");

                    b.HasIndex("ParentTagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Color = "#ffd254",
                            Name = "Florbalový dril"
                        },
                        new
                        {
                            TagId = 11,
                            Color = "#ffd254",
                            Name = "1 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 12,
                            Color = "#ffd254",
                            Name = "2 x 2",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 13,
                            Color = "#ffd254",
                            Name = "3 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 14,
                            Color = "#ffd254",
                            Name = "4 x 4",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 15,
                            Color = "#ffd254",
                            Name = "5 x 5",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 16,
                            Color = "#ffd254",
                            Name = "2 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 17,
                            Color = "#ffd254",
                            Name = "2 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 29,
                            Color = "#ffd254",
                            Name = "Střelba",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 30,
                            Color = "#ffd254",
                            Name = "Přihrávka",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 31,
                            Color = "#ffd254",
                            Name = "Vedení míčku",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 35,
                            Color = "#ffd254",
                            Name = "Uvolňování",
                            ParentTagId = 1
                        },
                        new
                        {
                            TagId = 5,
                            Color = "#d9980d",
                            Name = "Forma"
                        },
                        new
                        {
                            TagId = 25,
                            Color = "#d9980d",
                            Name = "Hra",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 26,
                            Color = "#d9980d",
                            Name = "Florbal",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 27,
                            Color = "#d9980d",
                            Name = "Test",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 28,
                            Color = "#d9980d",
                            Name = "Štafeta",
                            ParentTagId = 5
                        },
                        new
                        {
                            TagId = 3,
                            Color = "#27dbf5",
                            Name = "Hráč"
                        },
                        new
                        {
                            TagId = 18,
                            Color = "#27dbf5",
                            Name = "Brankář",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 19,
                            Color = "#27dbf5",
                            Name = "Útočník",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 20,
                            Color = "#27dbf5",
                            Name = "Obránce",
                            ParentTagId = 3
                        },
                        new
                        {
                            TagId = 9,
                            Color = "#2196f3",
                            Name = "Hráčská kategorie"
                        },
                        new
                        {
                            TagId = 47,
                            Color = "#2196f3",
                            Name = "U7 - předpřípravka",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 48,
                            Color = "#2196f3",
                            Name = "U9 - přípravka",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 49,
                            Color = "#2196f3",
                            Name = "U11 - elévi",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 50,
                            Color = "#2196f3",
                            Name = "U13 - ml. žáci",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 51,
                            Color = "#2196f3",
                            Name = "U15 - st. žáci",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 52,
                            Color = "#2196f3",
                            Name = "U17 - dorost",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 53,
                            Color = "#2196f3",
                            Name = "U21 - junioři ",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 54,
                            Color = "#2196f3",
                            Name = "Muži",
                            ParentTagId = 9
                        },
                        new
                        {
                            TagId = 6,
                            Color = "#17a258",
                            Name = "Tělesná průprava"
                        },
                        new
                        {
                            TagId = 32,
                            Color = "#17a258",
                            Name = "Ohebnost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 33,
                            Color = "#17a258",
                            Name = "Síla",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 34,
                            Color = "#17a258",
                            Name = "Výbušnost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 36,
                            Color = "#17a258",
                            Name = "Rychlost",
                            ParentTagId = 6
                        },
                        new
                        {
                            TagId = 4,
                            Color = "#0989c2",
                            Name = "Tréninková část"
                        },
                        new
                        {
                            TagId = 21,
                            Color = "#0989c2",
                            Name = "Rozehřátí",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 22,
                            Color = "#0989c2",
                            Name = "Rozcvička",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 23,
                            Color = "#0989c2",
                            Name = "Dril",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 24,
                            Color = "#0989c2",
                            Name = "Protahování",
                            ParentTagId = 4
                        },
                        new
                        {
                            TagId = 8,
                            Color = "#ff9102",
                            Name = "Vybavení"
                        },
                        new
                        {
                            TagId = 39,
                            Color = "#ff9102",
                            Name = "Florbalové míčky",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 40,
                            Color = "#ff9102",
                            Name = "Florbalová branka",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 41,
                            Color = "#ff9102",
                            Name = "Rozlišovací dresy",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 42,
                            Color = "#ff9102",
                            Name = "Kužely",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 43,
                            Color = "#ff9102",
                            Name = "Skočky",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 44,
                            Color = "#ff9102",
                            Name = "Žebřík",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 45,
                            Color = "#ff9102",
                            Name = "Švihadlo",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 46,
                            Color = "#ff9102",
                            Name = "Fotbalový míč",
                            ParentTagId = 8
                        },
                        new
                        {
                            TagId = 7,
                            Color = "#e6e9eb",
                            Name = "Ostatní"
                        },
                        new
                        {
                            TagId = 37,
                            Color = "#e6e9eb",
                            Name = "Herní myšlení",
                            ParentTagId = 7
                        },
                        new
                        {
                            TagId = 38,
                            Color = "#e6e9eb",
                            Name = "Spolupráce v týmu",
                            ParentTagId = 7
                        },
                        new
                        {
                            TagId = 10,
                            Color = "#666666",
                            Name = "Vlastní"
                        });
                });

            modelBuilder.Entity("ActivityTag", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingDataAccess.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingDataAccess.Models.Tag", b =>
                {
                    b.HasOne("TrainingDataAccess.Models.Tag", "ParentTag")
                        .WithMany()
                        .HasForeignKey("ParentTagId");

                    b.Navigation("ParentTag");
                });
#pragma warning restore 612, 618
        }
    }
}
