// <auto-generated />
using System;
using FloorballTraining.Plugins.EFCoreSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloorballTraining.Plugins.EFCoreSqlServer.Migrations
{
    [DbContext(typeof(FloorballTrainingContext))]
    [Migration("20240112192811_dtos")]
    partial class dtos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DurationMax")
                        .HasColumnType("int");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonsMax")
                        .HasColumnType("int");

                    b.Property<int>("PersonsMin")
                        .HasColumnType("int");

                    b.Property<int>("PlaceLength")
                        .HasColumnType("int");

                    b.Property<int>("PlaceWidth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Děti se rozdělí do dvou družstev, děti se drží za pas, první v řadě je hlava draka, poslední je ocas draka, družstva stojí asi 10 metrů od sebe, na povel se snaží hlava draka chytit ocas draka protihráče",
                            Difficulty = 0,
                            DurationMax = 10,
                            DurationMin = 5,
                            Environment = 0,
                            Intensity = 0,
                            Name = "Dračí zápasy",
                            PersonsMax = 30,
                            PersonsMin = 4,
                            PlaceLength = 1,
                            PlaceWidth = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Čert má z rozlišováku připevněný ocas a snaží se všechny ostatní hráče polapit. Pokud někoho chytne, jde mimo hřiště.Hráči se snaží vzít čertovy ocas a osvobodit tak již chycené hráče. Po osvobození hráčů hra končí a stává se čertem hráč, který vzal čertovy ocas.",
                            Difficulty = 0,
                            DurationMax = 15,
                            DurationMin = 5,
                            Environment = 0,
                            Intensity = 1,
                            Name = "Čertovská honička",
                            PersonsMax = 30,
                            PersonsMin = 5,
                            PlaceLength = 1,
                            PlaceWidth = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Difficulty = 2,
                            DurationMax = 20,
                            DurationMin = 10,
                            Environment = 0,
                            Intensity = 2,
                            Name = "Florbal 3x3",
                            PersonsMax = 12,
                            PersonsMin = 6,
                            PlaceLength = 1,
                            PlaceWidth = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Všichni mají florbalky. Každá ovečka má míček. Vlk se postaví do základní pozice na druhé straně hřiště. Po zahájení hry se saží chytit ovečku tak, že ji vezme florbalově čistě míček. Nesmí se vracet ve směru pohybu. Ovečka, která přišla o míček se stává vlkem, Po chycení všech oveček hra končí.",
                            Difficulty = 0,
                            DurationMax = 15,
                            DurationMin = 5,
                            Environment = 0,
                            Intensity = 1,
                            Name = "Na ovečky a vlky s florbalkou a míčkem",
                            PersonsMax = 30,
                            PersonsMin = 15,
                            PlaceLength = 1,
                            PlaceWidth = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Difficulty = 2,
                            DurationMax = 10,
                            DurationMin = 5,
                            Environment = 0,
                            Intensity = 2,
                            Name = "Florbal 1x1",
                            PersonsMax = 10,
                            PersonsMin = 2,
                            PlaceLength = 1,
                            PlaceWidth = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Difficulty = 2,
                            DurationMax = 20,
                            DurationMin = 10,
                            Environment = 0,
                            Intensity = 2,
                            Name = "Florbal 2x2",
                            PersonsMax = 10,
                            PersonsMin = 4,
                            PlaceLength = 1,
                            PlaceWidth = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Difficulty = 2,
                            DurationMax = 20,
                            DurationMin = 10,
                            Environment = 0,
                            Intensity = 2,
                            Name = "Florbal 5x5",
                            PersonsMax = 30,
                            PersonsMin = 10,
                            PlaceLength = 1,
                            PlaceWidth = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Hráč si udělá z kloboučků kruh. Mezera mezi kloboučky alespoň 30 cm. Hráč stojí s míčkem uprostřed a postupně provádí florbalový dribling stále dokola.",
                            Difficulty = 0,
                            DurationMax = 10,
                            DurationMin = 3,
                            Environment = 0,
                            Intensity = 0,
                            Name = "Florbalový dribling v kruhu",
                            PersonsMax = 30,
                            PersonsMin = 1,
                            PlaceLength = 2,
                            PlaceWidth = 2
                        });
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityAgeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("AgeGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AgeGroupId");

                    b.ToTable("ActivityAgeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityId = 1,
                            AgeGroupId = 11
                        },
                        new
                        {
                            Id = 2,
                            ActivityId = 1,
                            AgeGroupId = 7
                        },
                        new
                        {
                            Id = 3,
                            ActivityId = 3,
                            AgeGroupId = 11
                        },
                        new
                        {
                            Id = 4,
                            ActivityId = 3,
                            AgeGroupId = 7
                        },
                        new
                        {
                            Id = 5,
                            ActivityId = 20,
                            AgeGroupId = 11
                        });
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ActivityEquipments");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityMedium");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TagId");

                    b.ToTable("ActivityTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityId = 1,
                            TagId = 31
                        },
                        new
                        {
                            Id = 2,
                            ActivityId = 1,
                            TagId = 35
                        },
                        new
                        {
                            Id = 3,
                            ActivityId = 3,
                            TagId = 31
                        },
                        new
                        {
                            Id = 4,
                            ActivityId = 3,
                            TagId = 35
                        },
                        new
                        {
                            Id = 5,
                            ActivityId = 20,
                            TagId = 35
                        },
                        new
                        {
                            Id = 6,
                            ActivityId = 20,
                            TagId = 41
                        });
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.AgeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kdokoliv",
                            Name = "Kdokoliv"
                        },
                        new
                        {
                            Id = 7,
                            Description = "U7 - předpřípravka",
                            Name = "U7"
                        },
                        new
                        {
                            Id = 9,
                            Description = "U9 - přípravka",
                            Name = "U9"
                        },
                        new
                        {
                            Id = 11,
                            Description = "U11 - elévi",
                            Name = "U11"
                        },
                        new
                        {
                            Id = 13,
                            Description = "U13 - ml. žáci",
                            Name = "U13"
                        },
                        new
                        {
                            Id = 15,
                            Description = "U15 - st. žáci",
                            Name = "U15"
                        },
                        new
                        {
                            Id = 17,
                            Description = "U17 - dorost",
                            Name = "U17"
                        },
                        new
                        {
                            Id = 21,
                            Description = "U21 - junioři",
                            Name = "U21"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Dospělí",
                            Name = "Dospeli"
                        });
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rozlišovací dresy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kužely"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Skočky"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Žebřík"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Švihadlo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fotbalový míč"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Florbalové míčky"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Florbalová branka"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Florbalky"
                        });
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Environment = 1,
                            Length = 40,
                            Name = "GMK",
                            Width = 17
                        },
                        new
                        {
                            Id = 2,
                            Environment = 1,
                            Length = 60,
                            Name = "Komenda",
                            Width = 25
                        },
                        new
                        {
                            Id = 3,
                            Environment = 1,
                            Length = 20,
                            Name = "TGM",
                            Width = 10
                        },
                        new
                        {
                            Id = 4,
                            Environment = 2,
                            Length = 40,
                            Name = "Venkovní hřiště za Komendou",
                            Width = 20
                        },
                        new
                        {
                            Id = 5,
                            Environment = 1,
                            Length = 3,
                            Name = "Domov",
                            Width = 3
                        });
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrainingGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentTagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "Zaměření tréninku"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "1 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 12,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "2 x 2",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 13,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "3 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 14,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "4 x 4",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 15,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "5 x 5",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 16,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "2 x 3",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 17,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "2 x 1",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 29,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "Střelba",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 30,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "Přihrávka",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 31,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "Vedení míčku",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 35,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "Uvolňování",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 37,
                            Color = "#e6e9eb",
                            IsTrainingGoal = true,
                            Name = "Herní myšlení",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 38,
                            Color = "#e6e9eb",
                            IsTrainingGoal = true,
                            Name = "Spolupráce v týmu",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 18,
                            Color = "#27dbf5",
                            IsTrainingGoal = true,
                            Name = "Brankář",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 19,
                            Color = "#27dbf5",
                            IsTrainingGoal = true,
                            Name = "Útočník",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 20,
                            Color = "#27dbf5",
                            IsTrainingGoal = true,
                            Name = "Obránce",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 6,
                            Color = "#17a258",
                            IsTrainingGoal = true,
                            Name = "Tělesná průprava",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 32,
                            Color = "#17a258",
                            IsTrainingGoal = true,
                            Name = "Ohebnost",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 33,
                            Color = "#17a258",
                            IsTrainingGoal = true,
                            Name = "Síla",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 34,
                            Color = "#17a258",
                            IsTrainingGoal = true,
                            Name = "Výbušnost",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 36,
                            Color = "#17a258",
                            IsTrainingGoal = true,
                            Name = "Rychlost",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 40,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "Hokejový dribling",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 41,
                            Color = "#ffd254",
                            IsTrainingGoal = true,
                            Name = "Florbalový dribling",
                            ParentTagId = 1
                        },
                        new
                        {
                            Id = 5,
                            Color = "#d9980d",
                            IsTrainingGoal = false,
                            Name = "Forma"
                        },
                        new
                        {
                            Id = 25,
                            Color = "#d9980d",
                            IsTrainingGoal = false,
                            Name = "Hra",
                            ParentTagId = 5
                        },
                        new
                        {
                            Id = 27,
                            Color = "#d9980d",
                            IsTrainingGoal = false,
                            Name = "Test",
                            ParentTagId = 5
                        },
                        new
                        {
                            Id = 28,
                            Color = "#d9980d",
                            IsTrainingGoal = false,
                            Name = "Štafeta",
                            ParentTagId = 5
                        },
                        new
                        {
                            Id = 39,
                            Color = "#d9980d",
                            IsTrainingGoal = false,
                            Name = "Výzva",
                            ParentTagId = 5
                        },
                        new
                        {
                            Id = 4,
                            Color = "#0989c2",
                            IsTrainingGoal = false,
                            Name = "Tréninková část"
                        },
                        new
                        {
                            Id = 21,
                            Color = "#0989c2",
                            IsTrainingGoal = false,
                            Name = "Rozehřátí",
                            ParentTagId = 4
                        },
                        new
                        {
                            Id = 22,
                            Color = "#0989c2",
                            IsTrainingGoal = false,
                            Name = "Rozcvička",
                            ParentTagId = 4
                        },
                        new
                        {
                            Id = 23,
                            Color = "#0989c2",
                            IsTrainingGoal = false,
                            Name = "Hlavní část",
                            ParentTagId = 4
                        },
                        new
                        {
                            Id = 24,
                            Color = "#0989c2",
                            IsTrainingGoal = false,
                            Name = "Protahování",
                            ParentTagId = 4
                        },
                        new
                        {
                            Id = 10,
                            Color = "#666666",
                            IsTrainingGoal = false,
                            Name = "Vlastní"
                        });
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentAfter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonsMax")
                        .HasColumnType("int");

                    b.Property<int>("PersonsMin")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingGoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TrainingGoalId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.TrainingAgeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingAgeGroups");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.TrainingGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("PersonsMax")
                        .HasColumnType("int");

                    b.Property<int>("PersonsMin")
                        .HasColumnType("int");

                    b.Property<int>("TrainingPartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TrainingPartId");

                    b.ToTable("TrainingGroups");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.TrainingPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingParts");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityAgeGroup", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Activity", "Activity")
                        .WithMany("ActivityAgeGroups")
                        .HasForeignKey("ActivityId");

                    b.HasOne("FloorballTraining.CoreBusiness.AgeGroup", "AgeGroup")
                        .WithMany("ActivityAgeGroups")
                        .HasForeignKey("AgeGroupId");

                    b.Navigation("Activity");

                    b.Navigation("AgeGroup");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityEquipment", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Activity", "Activity")
                        .WithMany("ActivityEquipments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloorballTraining.CoreBusiness.Equipment", "Equipment")
                        .WithMany("ActivityEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityMedia", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Activity", "Activity")
                        .WithMany("ActivityMedium")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.ActivityTag", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Activity", "Activity")
                        .WithMany("ActivityTags")
                        .HasForeignKey("ActivityId");

                    b.HasOne("FloorballTraining.CoreBusiness.Tag", "Tag")
                        .WithMany("ActivityTags")
                        .HasForeignKey("TagId");

                    b.Navigation("Activity");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Tag", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Tag", "ParentTag")
                        .WithMany()
                        .HasForeignKey("ParentTagId");

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Training", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Place", "Place")
                        .WithMany("Trainings")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloorballTraining.CoreBusiness.Tag", "TrainingGoal")
                        .WithMany("Trainings")
                        .HasForeignKey("TrainingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("TrainingGoal");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.TrainingAgeGroup", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.AgeGroup", "AgeGroup")
                        .WithMany("TrainingAgeGroups")
                        .HasForeignKey("AgeGroupId");

                    b.HasOne("FloorballTraining.CoreBusiness.Training", "Training")
                        .WithMany("TrainingAgeGroups")
                        .HasForeignKey("TrainingId");

                    b.Navigation("AgeGroup");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.TrainingGroup", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Activity", "Activity")
                        .WithMany("TrainingGroups")
                        .HasForeignKey("ActivityId");

                    b.HasOne("FloorballTraining.CoreBusiness.TrainingPart", "TrainingPart")
                        .WithMany("TrainingGroups")
                        .HasForeignKey("TrainingPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("TrainingPart");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.TrainingPart", b =>
                {
                    b.HasOne("FloorballTraining.CoreBusiness.Training", "Training")
                        .WithMany("TrainingParts")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Activity", b =>
                {
                    b.Navigation("ActivityAgeGroups");

                    b.Navigation("ActivityEquipments");

                    b.Navigation("ActivityMedium");

                    b.Navigation("ActivityTags");

                    b.Navigation("TrainingGroups");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.AgeGroup", b =>
                {
                    b.Navigation("ActivityAgeGroups");

                    b.Navigation("TrainingAgeGroups");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Equipment", b =>
                {
                    b.Navigation("ActivityEquipments");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Place", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Tag", b =>
                {
                    b.Navigation("ActivityTags");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.Training", b =>
                {
                    b.Navigation("TrainingAgeGroups");

                    b.Navigation("TrainingParts");
                });

            modelBuilder.Entity("FloorballTraining.CoreBusiness.TrainingPart", b =>
                {
                    b.Navigation("TrainingGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
