using Microsoft.EntityFrameworkCore;
using TrainingDataAccess.Models;

namespace TrainingDataAccess.DbContexts
{
    public static class ModelBuilderExtensions
    {

        private static readonly List<Tag> Tags = new()
        {
            new Tag { TagId = 1, Name = "Florbalový dril", ParentTagId = null, Color = "#ffd254" },
            new Tag { TagId = 11, Name = "1 x 1", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 12, Name = "2 x 2", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 13, Name = "3 x 3", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 14, Name = "4 x 4", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 15, Name = "5 x 5", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 16, Name = "2 x 3", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 17, Name = "2 x 1", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 29, Name = "Střelba", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 30, Name = "Přihrávka", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 31, Name = "Vedení míčku", ParentTagId = 1, Color = "#ffd254" },
            new Tag { TagId = 35, Name = "Uvolňování", ParentTagId = 1, Color = "#ffd254" },

            new Tag { TagId = 5, Name = "Forma", ParentTagId = null, Color = "#d9980d" },
            new Tag { TagId = 25, Name = "Hra", ParentTagId = 5, Color = "#d9980d" },
            new Tag { TagId = 26, Name = "Florbal", ParentTagId = 5, Color = "#d9980d" },
            new Tag { TagId = 27, Name = "Test", ParentTagId = 5, Color = "#d9980d" },
            new Tag { TagId = 28, Name = "Štafeta", ParentTagId = 5, Color = "#d9980d" },

            new Tag { TagId = 3, Name = "Hráč", ParentTagId = null, Color = "#27dbf5" },
            new Tag { TagId = 18, Name = "Brankář", ParentTagId = 3, Color = "#27dbf5" },
            new Tag { TagId = 19, Name = "Útočník", ParentTagId = 3, Color = "#27dbf5" },
            new Tag { TagId = 20, Name = "Obránce", ParentTagId = 3, Color = "#27dbf5" },

            new Tag { TagId = 9, Name = "Hráčská kategorie", ParentTagId = null, Color = "#2196f3" },
            new Tag { TagId = 47, Name = "U7 - předpřípravka", ParentTagId = 9, Color = "#2196f3" },
            new Tag { TagId = 48, Name = "U9 - přípravka", ParentTagId = 9, Color = "#2196f3" },
            new Tag { TagId = 49, Name = "U11 - elévi", ParentTagId = 9, Color = "#2196f3" },
            new Tag { TagId = 50, Name = "U13 - ml. žáci", ParentTagId = 9, Color = "#2196f3" },
            new Tag { TagId = 51, Name = "U15 - st. žáci", ParentTagId = 9, Color = "#2196f3" },
            new Tag { TagId = 52, Name = "U17 - dorost", ParentTagId = 9, Color = "#2196f3" },
            new Tag { TagId = 53, Name = "U21 - junioři ", ParentTagId = 9, Color = "#2196f3" },
            new Tag { TagId = 54, Name = "Muži", ParentTagId = 9, Color = "#2196f3" },

            new Tag { TagId = 6, Name = "Tělesná průprava", ParentTagId = null, Color = "#17a258" },
            new Tag { TagId = 32, Name = "Ohebnost", ParentTagId = 6, Color = "#17a258" },
            new Tag { TagId = 33, Name = "Síla", ParentTagId = 6, Color = "#17a258" },
            new Tag { TagId = 34, Name = "Výbušnost", ParentTagId = 6, Color = "#17a258" },
            new Tag { TagId = 36, Name = "Rychlost", ParentTagId = 6, Color = "#17a258" },

            new Tag { TagId = 4, Name = "Tréninková část", ParentTagId = null, Color = "#0989c2" },
            new Tag { TagId = 21, Name = "Rozehřátí", ParentTagId = 4, Color = "#0989c2" },
            new Tag { TagId = 22, Name = "Rozcvička", ParentTagId = 4, Color = "#0989c2" },
            new Tag { TagId = 23, Name = "Dril", ParentTagId = 4, Color = "#0989c2" },
            new Tag { TagId = 24, Name = "Protahování", ParentTagId = 4, Color = "#0989c2" },

            new Tag { TagId = 8, Name = "Vybavení", ParentTagId = null, Color = "#ff9102" },
            new Tag { TagId = 39, Name = "Florbalové míčky", ParentTagId = 8, Color = "#ff9102" },
            new Tag { TagId = 40, Name = "Florbalová branka", ParentTagId = 8, Color = "#ff9102" },
            new Tag { TagId = 41, Name = "Rozlišovací dresy", ParentTagId = 8, Color = "#ff9102" },
            new Tag { TagId = 42, Name = "Kužely", ParentTagId = 8, Color = "#ff9102" },
            new Tag { TagId = 43, Name = "Skočky", ParentTagId = 8, Color = "#ff9102" },
            new Tag { TagId = 44, Name = "Žebřík", ParentTagId = 8, Color = "#ff9102" },
            new Tag { TagId = 45, Name = "Švihadlo", ParentTagId = 8, Color = "#ff9102" },
            new Tag { TagId = 46, Name = "Fotbalový míč", ParentTagId = 8, Color = "#ff9102" },

            new Tag { TagId = 7, Name = "Ostatní", ParentTagId = null, Color = "#e6e9eb" },
            new Tag { TagId = 37, Name = "Herní myšlení", ParentTagId = 7, Color = "#e6e9eb" },
            new Tag { TagId = 38, Name = "Spolupráce v týmu", ParentTagId = 7, Color = "#e6e9eb" },

            new Tag { TagId = 10, Name = "Vlastní", ParentTagId = null, Color = "#666666" }

        };


        private static readonly List<Activity> Activities = new()
        {
            new Activity{ ActivityId = 1, Name="Dračí zápasy", Description = "Děti se rozdělí do dvou družstev, děti se drží za pas, první v řadě je hlava draka, poslední je ocas draka, družstva stojí asi 10 metrů od sebe, na povel se snaží hlava draka chytit ocas draka protihráče", DurationMin = 5, DurationMax = 10 , PersonsMin =4 , PersonsMax =null},
new Activity{ ActivityId = 2, Name="Čertovská honička", Description = "Čert má z rozlišováku připevněný ocas a snaží se všechny ostatní hráče polapit. Pokud někoho chytne, jde mimo hřiště.Hráči se snaží vzít čertovy ocas a osvobodit tak již chycené hráče. Po osvobození hráčů hra končí a stává se čertem hráč, který vzal čertovy ocas.", DurationMin = 5, DurationMax = 15 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 3, Name="Florbal 3x3", Description = "", DurationMin = 10, DurationMax = 20 , PersonsMin =6 , PersonsMax =12},
new Activity{ ActivityId = 4, Name="Na ovečky a vlky s florbalkou a míčkem", Description = "Všichni mají florbalky. Každá ovečka má míček. Vlk se postaví do základní pozice na druhé straně hřiště. Po zahájení hry se saží chytit ovečku tak, že ji vezme florbalově čistě míček. Nesmí se vracet ve směru pohybu. Ovečka , která přišla o míček se stává vlkem, Po chycení všech oveček hra končí.", DurationMin = 5, DurationMax = 15 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 5, Name="Mírný klus", Description = "", DurationMin = 3, DurationMax = 10 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 6, Name="Běžecká abeceda - lifting - pata špička", Description = "Také nazývané jako protlačování, slouží k lepší práci a flexibilitě kotníků a pomáhá nám ve startovací fázi běhu.  Nejprve cvik provádíme na místě, posléze s nepatrným posunem vpřed. Špičky necháváme zcela na místě, pracuje pouze pata, a to střídavým rychlým a dynamickým pohybem směrem vzhůru. Při tomto pohybu se nám jedno koleno dostane do popředí a druhým se snažíme protlačovat vzad. Horní část těla a boky držíme zpevněné s přímým pohledem vpřed. Ruce pokrčíme jako při běhu a pomáháme si s nimi udávat rychlost celého pohybu.", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 7, Name="Běžecká abeceda - skiping - vysoká kolena", Description = "Skipping nazýváme stejně dynamický pohyb jako u liftingu s tím rozdílem, že se nám do pohybu zapojí kolena. Ty se snažíme dostat co nejvýše nejlépe tak, aby stehno bylo ve vodorovné poloze. Není to však nutností. Hlavním požadavkem u tohoto cviku je dynamika. Dbát musíme na držení horní části těla, která by se neměla dostat do záklonu, ale spíše do mírného předklonu.", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 8, Name="Běžecká abeceda - zakopávaní", Description = "Tento cvik řadíme mezi ty, díky kterým se náš běh zrychlí a zefektivní. A bude také dynamičtější a zlepší se rychlost našich reakci při případném nuceném neočekávaném zastavení. Lýtka zvedáme směrem nahoru až k horní části stehen a hýždím, jako bychom se chtěli sami nakopnout. Pohyb musí být dynamický a rytmický. Tělo se snažíme mít po celou dobu zpevněné a narovnané. Vyšší úroveň můžeme nasadit například kombinací skippingu a zakopávání po 4 opakováních.", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 9, Name="Běžecká abeceda - běh stranou ", Description = "Koordinačně nejtěžší cvik, který je ve finále a dobrém provedení skvělou hrou. Malými krůčky do boku střídá vždy zadní noha tu přední a střídavě ji křižuje vždy dopředu a dozadu. Paže rozpažíme, hlavu otočíme ve směru běhu a při dobrém provedení cítíme, jak se nám trup krásně protahuje, zatímco nohy nám hrají hru na kočkovanou a honí jedna druhou. Nesmíme zapomenout směr běhu po nějakém čase vystřídat.", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 10, Name="Běžecká abeceda - skoky stranou", Description = "Ruce dáme v bok, vybereme si pravou nebo levou stranu a krokujeme. Postupně zrychlujeme, až do úplných skoků kdy se naše kotníky sílou dynamiky skoro jakoby spojí. Po sérii 10 skoků opakujeme na druhou stranu. Získáme díky tomu lepší odrazovou sílu a procvičujeme také koordinaci.", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 11, Name="Běžecká abeceda - jelení skoky", Description = "Jelení skoky jsou nedílnou součástí a po sérii dynamických cviků nám tento napomáhá ke zvýšení běžeckého rozsahu a prevenci proti natrhnutí svalů. Dlouhé kroky postupně zrychlete, skoro až na běh při kterém odrazovou nohu napněte v kolenou a neodrazovou naopak vystřelte kolenem dopředu. Tento cvik je pro začátečníky nejsložitější, proto dbejte na precizním provedení a raději začněte pomalu skoro kroky než hned úplnými jeleními skoky. Pažemi pohybujeme podobně jako u běhu s možností úplného natažení ruky před sebe.", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 12, Name="Běžecká abeceda - běh zpět", Description = "Jednoduše se otočte a začněte jen chůzí. Postupně tempo zvyšujte až do poloběhu. V žádném případě nedoporučuji se otáčet, jen by vás to zmátlo a dezorientovalo.", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 13, Name="protažení krku ", Description = "náklon hlavy (do stran a dopředu)                                       ", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 14, Name="protažení paží             ", Description = "kroužení (krouživým pohybem)                                            ", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 15, Name="protažení trupu            ", Description = "úklony vpravo a vlevo                                                   ", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 16, Name="protažení ramen a zad      ", Description = "v předklonu střídavě hmitáme levou rukou k pravému chodidlu a opačně    ", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 17, Name="protažení trupu            ", Description = "kroužení boky a pánví                                                   ", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 18, Name="protažení kloubů na nahou  ", Description = "kroužení v kyčli, koleni a kotníku                                      ", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 19, Name="protažení lýtek a achilovky", Description = "opřeni rukama o zeď a střídavě pokládáme levou a pravou patu na podlahu ", DurationMin = 1, DurationMax = 3 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 20, Name="Blboun", Description = "S rukama za zády leh na zemi a vstát", DurationMin = 1, DurationMax = 5 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 21, Name="Nahrávky házení míčem 2x2", Description = "Hraje se 2 na 2. Hráči si přihrávají míč házením. Vítězí tým, který má v daném časovém úseku více přihrávek za sebou", DurationMin = 3, DurationMax = 10 , PersonsMin =4 , PersonsMax =4},
new Activity{ ActivityId = 22, Name="Nahrávky 2x2", Description = "Hraje se 2 na 2. Hráči si přihrávají. Vítězí tým, který má v daném časovém úseku více přihrávek za sebou", DurationMin = 3, DurationMax = 10 , PersonsMin =4 , PersonsMax =4},
new Activity{ ActivityId = 23, Name="Mrazík", Description = "Jeden nebo více hráčů představuje Mrazíka, který/ří se snaží chytit ostatní. Koho se dotkne rukou, ten je zmražen a čeká na vysvobození. Chycený se rozkročí a jakmile ho někdo podleze, může pokračovat ve hře.", DurationMin = 5, DurationMax = 15 , PersonsMin =4 , PersonsMax =null},
new Activity{ ActivityId = 24, Name="Bořiči a stavitelé", Description = "2 týmy hrají proti sobě - bořiči proti stavitelům. Na určitém prostoru se rozhází velký počet kloboučků - půlka jich je postavena normálně, půlka je vzhůru nohama. Jeden tým obrací kloboučky vzhůru nohama - bořiči, druhý tým je obrací správně - stavitelé. Časový interval cca do 1min. vyhrává tým, kterých kloboučků je víc - zbořené x postavené.", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 25, Name="Kámen - nůžky - papír", Description = "Hráči se rozdělí do družstev o stejném počtu a postaví se vždy dvě družstva naproti sobě. Po písknutí vyráží první v pořadí z obou družstev. Když se setkají, zahrají si hru: kámen, nůžky, papír. Ten, co prohraje, vrací se zpět do svého družstva, ten, co vyhrál pokračuje dál ve svém směru. To družstvo, co prohrálo, vysílá druhého z družstva. Když se setkají, opět si zahrají hru. A tak hra pokračuje dál. Hráč, který dorazí k družstvu protihrajících bez prohry, získává pro své družstvo 1 bod. Vyhrává to družstvo, které za určitý čas získá nejvíce bodů.", DurationMin = 5, DurationMax = 15 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 26, Name="Ocásky", Description = "každý hráč má za trenkami vzadu zastrčený rozlišovák, který musí být dostatečně vytažen hráči se snaží odebrat si ocásek navzájem, bránt se mohou vhodným pohybem", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 27, Name="Zahrádka", Description = "na vymezeném prostoru jsou rozmístěny 4 barvy kuželů po 4ks. hráč na zrakový či sluchový signál /barva kužele/ vbíhá mezi kužely do prostoru a postupně se co nejrychleji dotkne všech kuželů dané barvy a vybíhá z prostoru na druhé straně opět mezi kužely.", DurationMin = null, DurationMax = null , PersonsMin =2 , PersonsMax =10},
new Activity{ ActivityId = 28, Name="Evoluce", Description = "Všichni děti začínají jako kuřátka, jsou ve dřepu a pípají, přijdou k sobě dvě kuřata a zahrají si kámen, nůžky, papír, ten kdo, vyhraje, postupuje do další úrovně a stává se kočka, prohrané kuře zůstává kuřetem, takto se postupuje ve vývoji dál, vyhrává ten, kde se stane první člověkem -> kuře → kočka → slon → opice → člověk", DurationMin = 5, DurationMax = 15 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 29, Name="Florbalový fotbálek", Description = "otočíme branky proti sobě v rozumné vzálenosti rozdělíme hráče na dva týmy. Do hry vhodíme tři florbalové míče. Vyhrává ten kdo dá více golů. ", DurationMin = 10, DurationMax = 15 , PersonsMin =6 , PersonsMax =12},
new Activity{ ActivityId = 30, Name="Čertovská honička", Description = "Čert má oháňku, koho se čert dotkne, ten zkamení na místě, kdo mu vytrhne oháňku, stane se čertem a všichni ostatní ožívají", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 31, Name="Člověk, kůň, rak", Description = "Dvě družstva, vždy první člověk, druhý kůň a třetí rak, na povel vybíhá jak první člověk, oběhne metu a vrací se zpátky, pak vybíhají koně, kteří jdou po čtyřech, pak raci, kteří jdou pozpátku, hru hrajeme 3x, aby se děti v rolích vystřídali – vždy posuneme o jednoho, člověk bude kůň, kůň bude rak a rak bude člověk", DurationMin = 5, DurationMax = 15 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 32, Name="Želvy a lovci", Description = "Dvě stejně početná družstva se rozmístí proti sobě na vzdálenost 10–15 metrů. Skupina, která představuje želvy, zaujme podpor klečmo. Druhá skupina, která hraje lovce, se pohybuje chůzí. Po zahájení hry mají želvy za úkol přemístit se z pláže (jedna strana tělocvičny) do moře (druhá strana tělocvičny). Lovci se snaží želvy ulovit přetočením na záda. Želva přetočená na záda se nemůže bránit a vypadá ze hry. Hrajeme na dvě kola, ve kterých se úlohy družstev vymění.", DurationMin = 5, DurationMax = 15 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 33, Name="Souboj trakařů", Description = "Dvojice, jeden ve vzporu ležmo, druhý mu drží nohy. Všichni proti všem se trakaři snaží donutit (tahem a tlakem) ostatní trakaře ke změně polohy (dotek hrudníku země). Bojují jen cvičenci v poloze vzporu ležmo!!! Vítězí poslední trakař. V druhém kole si cvičenci role vymění.", DurationMin = 5, DurationMax = 10 , PersonsMin =4 , PersonsMax =null},
new Activity{ ActivityId = 34, Name="Únik z pevnosti", Description = "Cvičenci se chytí za ruce a vytvoří kruh. Jeden cvičenec je uvnitř kruhu a snaží se proklouznout prostorem mezi cvičenci ven z kruhu. Ti mu v tom brání přisunutím se k sobě, nesmí však kruh zmenšovat, tudíž se na jiné straně kruhu musí mezery zvětšit. Pro přehlednost je kruh na videu pouze naznačen.", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 35, Name="Boj o hrad", Description = "Hráči se rozdělí na obránce a útočníky. Obránci zaujmou místo ve vytyčeném obdélníku, hradu. Útočníci se rozestaví po obvodu hradu, nesmí se ale žádnou částí svého těla dotknout hranice hradu. Přitom se snaží obránce z hradu vytáhnout. Obránci se tomu naopak brání tak, že vtahují útočníky dovnitř. Ten, kdo je vtažen do kruhu, stává se obráncem a naopak. Zvítězí to družstvo, které na svou stranu přetahá všechny protihráče.", DurationMin = 5, DurationMax = 15 , PersonsMin =8 , PersonsMax =null},
new Activity{ ActivityId = 36, Name="Na krále", Description = "Když se někde v krajině vyskytne vyvýšené místo nebo kruh urostřed haly stačí aby na něj kdokoliv vylezl a zavolal Jsem král.Hned se jej snaží stáhnout z vyvýšeného místa a sami sebe tam dosadit na místo panovnické. Ctižádostí každého je, aby se dostal, alespoň na chvíli nahoru a mohl zvolat ono Jsem král.Upozorňuji, že zvláště při této hříčce je třeba dbát míry a nenechat hru přerůst ve rvačku, děti (i vedoucí) se potřebují vyblbnout, ale není třeba je hned zabíjet.", DurationMin = 5, DurationMax = 10 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 37, Name="Souboj o míč", Description = "Dva hráči proti sobě s jedním míčem. Oba dva drží míč pevně oběma rukama. Na znamení se snaží vybojovat míč. Cvičení se provádí na stanovený počet vítězství nebo na co nejvíce vítězství po stanovený čas.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 38, Name="Vážení cibule", Description = "Hráči ve dvojici k sobě stojí zády, ruce mají vzájemně zaklesnuté v loktech. Na povel se snaží druhého dostat na svoje záda, tak aby se nedotýkal země.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 39, Name="Sumo", Description = "dvojice zápasí na žíněnkách začíná se v kleku a po celou dobu nesmí zápasníci na nohy do stoje jeden druhého se snaží položit na záda.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 40, Name="Kočka a myš", Description = "Hřiště se rozdělí na třetiny. V prostřední třetině je kočka a má kolem sebe spoustu sýrů (míčků). Myši přebíhají z krajní třetiny přes území se sýry a snaží se ukořistit sýr a přeběhnout na druhou stranu hřiště aniž by je kočka lapila. Myš, která je chycena se státá kočkou. Myši přebíhají dokud neposbírají všechny sýry nebo nejsou všechny lapeny.", DurationMin = 5, DurationMax = 10 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 41, Name="Fitness honička", Description = "čtyřmi kužely vymezíme hřištěna honičku a stranou připravíme čtyři posilovací stanoviště. Vybereme čtyři hráče (honiče), a každému dáme rozlišovací dres s jinou barvou (zelený, žlutý, bílý, červený). Ke každé barvě přiřadíme jedno stanoviště a určíme co jak dlouho se bude provádět. Hráči, kteří jsou chyceni odchází na posilovací stanoviště podle barvy, kterou byl chycen. Po provedí se vrací zpět a zapojuje se do honičky. ", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 42, Name="Házená", Description = "Děti rozdělíme do dvou týmů a s menším gumovým balonem hrajeme házenou. Hrač může s balonem pouze 3 kroky (nebo žádný) a gól je do branky. Průběh hry můžeme měnit i během pozadu.", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 43, Name="Bomba", Description = "V prostoru rozmístěné lavičky,kruhy,kostky cokoliv. Děti běží po obvodu haly, na písknutí: Bomba - lehnou do tří na zem, kdo nestíhá vypadává Povodeň - musí být do tří na lavičkách, v kruhu, ve čtverci z kuželů (nikdo nesmí stát na podlaze) jinak vypadává Počet 3,4,5 atd. - dětí musí do tří vytvořit předem určenou skupinu, nadpočetní vypadávají", DurationMin = 5, DurationMax = 10 , PersonsMin =10 , PersonsMax =null},
new Activity{ ActivityId = 44, Name="Míčkovaná", Description = "Hrací plochu rozdělíme na polovinu. Do každé poloviny se postaví jedno družstvo a 30 míčů (papírových koulí). Na povel trenéra začnou obě družstva házet míče ze své poloviny hrací plochy na polovinu soupeře. Hra končí po uplynutí časového limitu. Vyhrává to družstvo, které má na své polovině méně míčů.", DurationMin = 3, DurationMax = 10 , PersonsMin =8 , PersonsMax =null},
new Activity{ ActivityId = 45, Name="Číslovaná", Description = "Vytvoříme dvě družstva  V každém družstvu přidělíme dětem čísla. Mezi družstva přesně doprostřed položíme velký a malý míč. Trenér vyvolá nějaké číslo. Z každého družstva vyběhne hráč s tímto číslem a běží k míčům. Hráč, který doběhne první, vezme větší míč a snaží se s ním doběhnout ke svému družstvu. Hráč, který doběhne jako druhý, vezme menší míč a snaží se vybít hráče s větším míčem. Když ho vybije, získává pro své družstvo bod, a když ne, získává bod družstvo soupeře. Vybití platí jen do doby, než se hráč s větším míčem vrátí zpět ke svému družstvu.", DurationMin = null, DurationMax = null , PersonsMin =10 , PersonsMax =null},
new Activity{ ActivityId = 46, Name="Předávaná", Description = "Dvě družstva stojí vedle sebe (děti v jednotlivých družstvech v zástupu za sebou). První v každém družstvu na povel trenéra začne podávat míč nad hlavou dítěti, které stojí hned za ním, a takto hra pokračuje až k poslednímu dítěti. Poslední dítě pak běží na začátek řady a pokračuje stejným způsobem. Hra končí v momentě, kdy se vystřídají v podávání všichni členové družstva. Vítězí družstvo, které bylo rychlejší. ", DurationMin = 3, DurationMax = 5 , PersonsMin =8 , PersonsMax =null},
new Activity{ ActivityId = 47, Name="Veverky a kuny", Description = "Trenér vytvoří z florbalek trojúhelníková prostor a určí 3 hráče, kteří budou představovat 3 kuny a budou ve vymezeném prostoru hnízda. Ostatní hráči budou veverky mimo ohraničené území. V hnízdě veverek, kde jsou kuny, jsou míče představující oříšky. Na povel začnou kuny vyhazovat oříšky z hnízda ven. Veverky vyhozené oříšky sbírají a rychle je nosí zpět do hnízda, kam je polokládají. Nesmí je do hnízda házet, smí je nosit jen po jednom. Hodnotí se, kolik míčů po skončení časového intervalu hry zůstalo v hnízdě.", DurationMin = 3, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 48, Name="Předávaná s podlézáním", Description = "Dvě družstva stojí vedle sebe (děti v jednotlivých družstvech v zástupu za sebou). Poslední v každém družstvu na povel trenéra začne podlézat mezi nohama hráčů před ní. Jakmile se dostane na začátek šatfety předá hráči míč za sebou a pak dále až poslednímu hráči. ", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 49, Name="Předávání do boku", Description = "Dvě družstva stojí vedle sebe (děti v jednotlivých družstvech v zástupu za sebou). První v každém družstvu na povel trenéra začne podávat míč do strany vlevo dalšímu dítěti, které stojí hned za ním, a ten podá opět do strany ale vpravo takto hra pokračuje až k poslednímu dítěti. Poslední dítě pak běží na začátek řady a pokračuje stejným způsobem. Hra končí v momentě, kdy se vystřídají v podávání všichni členové družstva. Vítězí družstvo, které bylo rychlejší. Způsobů podávání míče je celá řada, například podávání pod nohama, bokem, kutálení pod nohama apod.", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 50, Name="Jednoduchá honička", Description = "Dítě (honič), které má babu, pronásleduje ostatní a snaží se je chytit (předat babu). Když se mu to podaří, plácne rukou některého z honěných, předá mu dotykem babu i svoji funkci honiče. Vracení role, tzv. oplátka, není dovolena. Nový honič nesmí dát babu tomu, od koho ji dostal. Pokud hraje více než deset dětí, je dobré, když dětí (honičů) je více.", DurationMin = 3, DurationMax = 5 , PersonsMin =4 , PersonsMax =null},
new Activity{ ActivityId = 51, Name="Hadí honička", Description = "Začíná jedno dítě (honič) a snaží se někoho chytit. Koho chytne, ten se stává také honičem a chytne se prvního honiče za ruku. A pak honí ve dvojici. Další, koho chytí, se k nim opět přidá. Takto hra pokračuje do té doby, dokud nezbude ve hře poslední dítě. ", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 52, Name="Honička dvojic", Description = "Děti rozdělíme do dvojic a každou dvojici svážeme švihadlem vždy jednou nohou k sobě. Jedna dvojice má babu a jejím úkolem je chůzí nebo během předat babu jiné dvojici. Stačí, když ti, co mají babu, „plácnou“ jen jednoho z dvojice a celá dvojice má pak babu.", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 53, Name="Honička se záchranou", Description = "Po hrací ploše rozmístíme jednu nebo více žíněnek podle toho, kolik hráčů bude hrát. Zvolíme jednoho či dva honiče, závisí na počtu hráčů. Honič začne honit. Pokud se dotkne honěného rukou, znehybní ho a ten si lehne na záda na zem. Nechycení hráči zachraňují znehybněné tím způsobem, že je dva, tři nebo čtyři zachránci přenesou (nejčastěji zvednutím za končetiny) na žíněnku. Zde chycení obživnou a hrají dále.", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 54, Name="Vyřazovací honička", Description = "Děti rozdělíme do dvou stejně početných družstev. První družstvo se rozestaví na jednom konci tělocvičny v přesně vymezeném prostoru a druhé družstvo ve stejně velkém prostoru na druhé straně tělocvičny. Každé družstvo vyšle na území soupeřů jednoho honiče. Na povel vyučujícího začnou honiči honit soupeře a stočenou roličkou z novin se je snažit vyřadit ze hry tím, že je udeří. Každý vyřazený hráč odchází na předem určené místo. Honění nesmějí překračovat hranice vymezeného prostoru, překročení znamená automatické vyřazení ze hry. Honička končí, když je celé jedno družstvo vyřazeno.", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 55, Name="Hra na babu mezi kužely", Description = "Ve vymezeném prostoru s různě rozmístěnýmy kužely hrajeme babu. Předáváme babu pomocí dotyku míče (nemusí být) dotykem (ne házením). Pokud někdo shodí kužel má trestný bod. Po uplynutí časového limitu spočítáme body. Vítězí ten, kdo jich má nejméně.", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 56, Name="Hra na babu ve dvojicích", Description = "Ve vymezeném prostoru hrajeme babu tak, že hráči vytvoří dvojice chycením se za ruce.", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 57, Name="Molekuly", Description = "Hráči = atomy se pohybují na vymezeném prostoru a na signál trenéra, který řekne číslo se musí spojit dané množství atomů v molekulu.", DurationMin = 3, DurationMax = 5 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 58, Name="Vybijená s florbalovým úkolem", Description = "Vybijená s florbalovým úkolem - vybitý hráč provede florbalový úkol a zařadí se zpět do hry", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 59, Name="Hra na babu mezi kužely s florbalovým úkolem", Description = "Ve vymezeném prostoru s různě rozmístěnýmy kužely hrajeme babu. Předáváme babu pomocí dotyku míče (nemusí být) dotykem (ne házením). Pokud někdo shodí kužel jde mimo herní hřiště a jde splnit nějaký florbalový úkol - slalom, zakončení do branky a pod.", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 60, Name="Na ovečky a vlky", Description = "Jeden hráč je vlk, ostatní jsou ovečky. Vlk se postaví do základní pozice na druhé straně hřiště. Po zahájení hry se snaží chytit ovečku. Nesmí se vracet ve směru pohybu. Chycená ovečka se stává vlkem. Po chycení všech oveček hra končí.", DurationMin = 5, DurationMax = 15 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 61, Name="Přenášení předmětů ze stanovišť", Description = "Hráče rozdělíme do družstev. Na hřišti vymezíme různě do prostoru základnu pro každé družstvo např. kruh, do kterého dáme kužely jedné barvy. Každé družstvo má svou barvu. Hráči mají za úkol přenést co nejvíce kuželů z cizích základen do té své. Vyhrává družstvo, které má po ukončení časového limitu nejvíce kuželů ve své základně.", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 62, Name="Medvědí souboj", Description = "Klek sedmo proti sobě předpažit pokrčmo. Cvičenci se chytí za ruce (neproplétají prsty). Tahem a tlakem do různých směrů se snaží vychýlit partnera a donutit ho k pádu.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 63, Name="Vychýlení z čáry", Description = "Cvičenci se postaví souhlasnou nohou vpřed proti sobě na jednu čáru a chytí se přední rukou za háčky. Tahem a tlakem do různých směrů se snaží donutit partnera opustit čáru. Možnost hrát na jedné noze.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 64, Name="Boj o žíněnku", Description = "Dvojice proti sobě, stoj na jedné, ruce zkříží na prsou. Kontaktem a úhyby za současného poskakování na stojné noze se cvičenci snaží druhého donutit k opuštění žíněnky. Místo žíněnky mohou posloužit čáry na zemi nebo kužely.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 65, Name="Souboj Eskymáků", Description = "Klek obounož, zvednout bérce od země, ruce spojit za tělem. Kontaktem a úhyby se každý snaží, aby druhý položil bérce (špičky) na zem nebo ztrátou rovnováhy změnil pozici.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 66, Name="Přetlak v sedu pokrčmo", Description = "Sed pokrčmo zády k sobě, ruce na kolena. Na povel se cvičenci snaží přetlačit partnera o určitý úsek.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 67, Name="Medvídek", Description = "Sed pokrčmo, chodidla k sobě, ruce drží spojená chodidla. Cvičenci provádí v této poloze převal přes pravou nohu, záda a přes levou nohu se zvedají opět do sedu", DurationMin = 2, DurationMax = 5 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 68, Name="Předtlačování nohama", Description = "Sed pokrčmo proti sobě se vzporem vzadu, přednožit pokrčmo pravou a spojit chodidla. Soustavným tlakem se snaží partnera posunout nebo ho donutit pokrčit nohu v koleni.", DurationMin = 3, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 69, Name="Kam dáš tam jdeš", Description = "Hráči se rozestaví do kruhu. Hráč s míčkem přihraje spoluhráči a hned běží tam, kde nahrál. Hráč, který přijmul přihrávku se snaží hned přihrát dalšímu.", DurationMin = 3, DurationMax = 10 , PersonsMin =3 , PersonsMax =null},
new Activity{ ActivityId = 70, Name="Obírání o míček", Description = "Ve skupině hráčů driblujících na malém prostoru je několik hráčů bez míčku a ti se snaží obrat někoho o jeho míček.", DurationMin = 3, DurationMax = 5 , PersonsMin =4 , PersonsMax =null},
new Activity{ ActivityId = 71, Name="Kopírování", Description = "1. hráč běží a snaží se měnit směry, naznačovat, provádět otočky a jiné cviky, 2. hráč běží za ním a snaží se reagovat a co nejrychleji kopírovat prvního hráče", DurationMin = 5, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 72, Name="Zrcadlo", Description = "kužely vyznačen pro každého hráče čtverec /jedna hrana společná/ začátek na středu čtverce. úkol - jeden hráč určuje pohyb ke kuželu, druhý se pohybuje podle prvního hráče. možnosti: 1. míček se vede k tomu samému kuželu, 2.míček se vede k protilehlému kuželu,3. míček se vede tak, aby vzdálenost mezi hráči byla stále stejná", DurationMin = 5, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 73, Name="Tvary", Description = "HRACI JSOU PO 4 V TYMU A MAJI STEJNOU BARVU DRESU.   NA PRVNÍ SIGNAL SE ZACNOU POHYBOVAT S MICKEM.NA DRUHY SIGNAL MUSI VYTVORIT TVAR DLE POKYNU TRENERA.", DurationMin = 5, DurationMax = 10 , PersonsMin =4 , PersonsMax =null},
new Activity{ ActivityId = 74, Name="Přeskoky - jednoduché", Description = "štafeta s překokem skočky nebo jiné překážky vše stejně vysoké", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 75, Name="Přeskoky - zvyšující", Description = "štafeta s překokem skočky nebo jiné překážky, výška se s každou další zvyšuje", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 76, Name="Přeskoky - s přesunem do stran", Description = "štafeta s překokem skočky nebo jiné překážky vše stejně vysoké, dvě i více řad překážek, po přeskoku přesun na přeskok v jiné řadě", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 77, Name="Souboj v postřehu 1", Description = "Dvě štafety, první hráči obou štafet se postaví proti době. Hráč z určené štafety určuje kdy vyběhne. Druhý hráč se ho snaží dohonit.", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 78, Name="Souboj v postřehu 2", Description = "Dvě štafety, první hráči obou štafet se postaví zády sobě. Na tlesknutí se snaží co nejrychleji otočit a doběhnout k metě a zpět", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 79, Name="Trojúhelník zakončený střelbou", Description = "Na útočné polovině se hráči rozmístí v pravém rohu (1), vpravo na půlící čáře (2) a vlevo na půlící čáře (3). Hráč (1)  nahraje hráči podél hrazení (2) a vybíhá do středu. Hráč (2) předá míček hráči (3) a ten nahrává na střed hráči (1), který zakončuje střelbou na branku. Hráč (1) zaujme pozici (3), hráč (2) jde na původní (1) a hráč tři jde na (2).", DurationMin = 5, DurationMax = 10 , PersonsMin =3 , PersonsMax =null},
new Activity{ ActivityId = 80, Name="Přihrávky v trojúhelníku ", Description = "Na útočné polovině se hráči rozmístí v pravém rohu (1), vpravo na půlící čáře (2) a vlevo na půlící čáře (3). Hráč (1)  nahraje hráči podél hrazení (2) a vybíhá do středu. Hráč (2) předá míček hráči (3) a ten nahrává na střed hráči (1), který nahraje hráči na stanovišti (1). Hráč (1) zaujme pozici (3), hráč (2) jde na původní (1) a hráč tři jde na (2).", DurationMin = 5, DurationMax = 10 , PersonsMin =3 , PersonsMax =null},
new Activity{ ActivityId = 81, Name="3 narážečky", Description = "Na útočné polovině se hráči rozmístí na středu vlevo u hrazení(1), uprostřed před bránou (2) na středu na půlící čáře (3). Hráč (1)  si narazí s hráčem (2) a ten jde do pravé kapsy. Hráč (1) si narazí s hráčem (3) a přebíhá do středu kde si narazí s hráčem (2) čekajícím v pravé kapse a nakonec střílí na branku.", DurationMin = 5, DurationMax = 10 , PersonsMin =3 , PersonsMax =null},
new Activity{ ActivityId = 82, Name="Vedení míčku na stanovištích se zakončením", Description = "Připravíme několik stanovišť s různou formou překážek. Hráče rozdělíme do družstev a necháme každého alespoň 3x projít stanovistě. Pak dojde ke změně stanoviště.", DurationMin = 10, DurationMax = 15 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 83, Name="Přihrávky do běhu", Description = "Hráči stojí u své branky. S míčkem se začnou pohybovat směrem kupředu a nahrávájí si. Před brankou soupeře zakončuji střelbou.", DurationMin = 5, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 84, Name="Na třetího", Description = "Bago pro 3. Dva hráči si nahrávají. Třetí hráč se snaží míček získat. Když jej získá, hráč, který měl jako poslední míček se stává třetím.", DurationMin = 5, DurationMax = 10 , PersonsMin =3 , PersonsMax =null},
new Activity{ ActivityId = 85, Name="Skoky přes skočku", Description = "Skok přes skočku - dopředu a zpět, bokem, skočka mezi nohama, cupitat na špičkách, po jedné noze vpřed a vzad,po jedné noze bokem, dopředu a zpět zeširoka cupitáním po špičkách", DurationMin = 5, DurationMax = 10 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 86, Name="Vedení míčku slalom", Description = "První nahraje podél kůželů, druhý provede slalom – jen forhandem nebo jen backhandem, na konci provede opět přihrávku – dojde tak k obrácení rolí", DurationMin = 5, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 87, Name="Přihrávky 2 hráči 2 míče", Description = "Dvojice se postaví naproti sobě a každý má svůj míček. Přihrávají si s oběma míčky najednou.", DurationMin = 5, DurationMax = 10 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 88, Name="X-ka", Description = "4 hráči se rozmístí do čtverce. První hráč přihraje diagonálně třetímu a hned běží za míčkem na pozici třetího. Hráč 3 přihrává 2 a beží na 2. Hráč 2 přihrává na 4 a běží na 4. Hráč 4 přihrává na 1 a běží na 1.", DurationMin = 5, DurationMax = 10 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 89, Name="Miniflorbal 1:1", Description = "Hrajeme florbal 1:1", DurationMin = 5, DurationMax = 15 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 90, Name="Fotbálek", Description = "Fotbal", DurationMin = 10, DurationMax = 20 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 91, Name="Semafor", Description = "Střídáme kloboučky a hráči vykonávají domluvené úkony podle významu barev. Kloboučky několika barev, kde každá barva má svůj význam. Např. červená stůj, zelená běž, oražová jdi do polohy pro start sprintu, žlutá sedni si... ", DurationMin = 5, DurationMax = 10 , PersonsMin =6 , PersonsMax =null},
new Activity{ ActivityId = 92, Name="Test - florbal - rychlost", Description = "Florbalové dovednosti na připravené trase. Trasa a náročnost vždy stejná!", DurationMin = 15, DurationMax = 20 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 93, Name="Test - tělesná průprava", Description = "Skok daleký, dřep, hod do dálky, hod na cíl, kotoul vpřed/vzad, přeskok překážky, šplh, předklon", DurationMin = 15, DurationMax = 60 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 94, Name="Test - síla", Description = "Počet kliků, dřepů, přítahů do maxima", DurationMin = 15, DurationMax = 60 , PersonsMin =1 , PersonsMax =null},
new Activity{ ActivityId = 95, Name="Týmová vybíjená", Description = "Hráči rozděleni do týmů hrají vybíjenou tak, že vybíjejí jen hráče druhého týmu a to jen po alespoň 2 přihrávkách tj. 3 hráči jednotho týmu budou mít míč", DurationMin = 10, DurationMax = 20 , PersonsMin =8 , PersonsMax =null},
new Activity{ ActivityId = 96, Name="Souboj o vajíčka", Description = "Hráči rozdělení do 4 týmů. Každý tým má své hnízdo v rohu čtverce. Uprostřed je líheň, ve které jsou míčky. Hráči na povel začnou po jednom z každého družstva běhat pro 1 vajíčko a donáší jej do svého hnízda. Varianta: Mohou brát všíchni i z hnízd soupeřů. Hra pak musí být na čas.", DurationMin = 10, DurationMax = 15 , PersonsMin =12 , PersonsMax =null},
new Activity{ ActivityId = 97, Name="Ocásky v týmu", Description = "Hráči se rozdělí do 2 týmů. Jeden tým si vybere svého jednoho hráče a tomu dá rozlišovák jako ocásek a chytnou se všichni kolem ramen do kruhu. Druhý tým vyšle jednoho chytače a ten se snaží chyti ocásek hráči v bránícím družstvu. Bránící družstvo se snaží pohybem celého družstva zamezit chycení ocásku.", DurationMin = 10, DurationMax = 15 , PersonsMin =8 , PersonsMax =null},
new Activity{ ActivityId = 98, Name="Hutututu", Description = "Hráči se rozdělí na dva týmy. Z jednoho družstva se někdo vrhne mezi své protivníky. Snaží se jich co nejvíce plácnout a pak se dostat zpátky na svou polovinu. Soupeři se jej snaží chytit a nepustit zpět. Pokud se mu to přece jen povede, všichni, kterých se dotkl, jsou teď v jeho týmu.", DurationMin = 10, DurationMax = 20 , PersonsMin =8 , PersonsMax =30},
new Activity{ ActivityId = 99, Name="Hra 1:1 po slalomech", Description = "Hráči jsou rozděleni do dvojic. Podél hřiště jsou na obou stranách připravené slalomy. Hráči vybíhají a provedou slalom na své straně. Po provedení slalomu ten rychlejší vystřelí na branku a hnd začne bránit druhého hráče. Počítají se góly.", DurationMin = 10, DurationMax = 15 , PersonsMin =2 , PersonsMax =null},
new Activity{ ActivityId = 100, Name="Střídačka", Description = "Tři skupiny hráčů, kde 1. skupina je od brankáře vpravo od mantinelů, 2. skupina je vlevo a 3. skupina je uprostřed. Hráči střílejí na brankáře ve sledu 1-2-3-2-1-3. Dbáme na správný postoj a přesuny brankáře ", DurationMin = 5, DurationMax = 10 , PersonsMin =4 , PersonsMax =null},
new Activity{ ActivityId = 101, Name="Bez dorážky", Description = "Střelci střílejí na branku. Před brankou jsou dorážeči. Pokud brankář nechytne míček, dorážeči se snaží co nejrychleji dorazit míček do branky. Cílem je naučit brankáře neodrážet před branku, ale míček hned rozehrát.", DurationMin = 5, DurationMax = 10 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 102, Name="2 na 1 ve sprintu", Description = "2 útočníci běží společně do útoku a 1 obránce se je snaží dohnat a zabránit jim ve střele. Útočníci si mohou ale nemusí přihrát. Snaha o co nejpřimočarejš útok ve sprintu.", DurationMin = 10, DurationMax = 15 , PersonsMin =5 , PersonsMax =null},
new Activity{ ActivityId = 103, Name="Střela po přihrávce z rohu", Description = "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha podél mantinelu a sbíhá si do středu, kde dostane přihrávku od spoluhráče a střílí. Druhý hráč vybíha, dostane přihrávku a střílí.... Tým, který nejdříve dá předem určený počet gólů, vyhrává.", DurationMin = 10, DurationMax = 15 , PersonsMin =7 , PersonsMax =null},
new Activity{ ActivityId = 104, Name="Samostatný nájezd po přihrávce z rohu", Description = "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha podél mantinelu a sbíhá si do středu trošku dále od branky, kde dostane přihrávku od spoluhráče a střílí. Druhý hráč vybíha, dostane přihrávku a střílí.... Tým, který nejdříve dá předem určený počet gólů, vyhrává.", DurationMin = 10, DurationMax = 15 , PersonsMin =7 , PersonsMax =null},
new Activity{ ActivityId = 105, Name="Žabka", Description = "Dva týmy. Každý tým má svůj roh za brankou. První hráč vybíha před branku, kde dostane skákavou přihrávku - žabku od spoluhráče a snaží se dát gól volejem nebo bekendem. Tým, který nejdříve dá předem určený počet gólů, vyhrává.", DurationMin = 10, DurationMax = 15 , PersonsMin =7 , PersonsMax =null},
new Activity{ ActivityId = 106, Name="Kámen-nůžky-papír-uteč", Description = "Hráči rozděleni do dvojic na středové čáře.Hrají kámen-nůžky-papír. Kdo vyhraje, tak se snaží útéct ke své základní čáře za sebou. Kdo prohrál, tak se jej snaží chytit.", DurationMin = 5, DurationMax = 10 , PersonsMin =10 , PersonsMax =null},
new Activity{ ActivityId = 107, Name="Zahazovaná", Description = "Jeden hráč háže míčky z vaku do hřiště a ostatní hráči míčky chytají nebo sbírají a nosí co nejrychleji zpět do vaku. Hraje se na interval 1 minuty. Spočítají se míčky v poli. Vyhazovači se střídají a pak se vyhlásí vítěz s největším počtem míčků v poli po ukončení časového limitu", DurationMin = 5, DurationMax = 10 , PersonsMin =5 , PersonsMax =null}



        };

        private static readonly List<ActivityTag> ActivityTags = new()
        {
            new ActivityTag{ActivityId=1, TagId=21},
            new ActivityTag{ActivityId=1, TagId=23},
            new ActivityTag{ActivityId=1, TagId=25},
            new ActivityTag{ActivityId=1, TagId=38},
            new ActivityTag{ActivityId=1, TagId=49},
            new ActivityTag{ActivityId=1, TagId=50},
            new ActivityTag{ActivityId=1, TagId=51},
            new ActivityTag{ActivityId=1, TagId=52},
            new ActivityTag{ActivityId=1, TagId=53},
            new ActivityTag{ActivityId=1, TagId=54},
            new ActivityTag{ActivityId=2, TagId=21},
            new ActivityTag{ActivityId=2, TagId=25},
            new ActivityTag{ActivityId=2, TagId=38},
            new ActivityTag{ActivityId=2, TagId=41},
            new ActivityTag{ActivityId=2, TagId=49},
            new ActivityTag{ActivityId=2, TagId=50},
            new ActivityTag{ActivityId=2, TagId=51},
            new ActivityTag{ActivityId=3, TagId=13},
            new ActivityTag{ActivityId=3, TagId=18},
            new ActivityTag{ActivityId=3, TagId=19},
            new ActivityTag{ActivityId=3, TagId=20},
            new ActivityTag{ActivityId=3, TagId=23},
            new ActivityTag{ActivityId=3, TagId=25},
            new ActivityTag{ActivityId=3, TagId=26},
            new ActivityTag{ActivityId=3, TagId=38},
            new ActivityTag{ActivityId=3, TagId=39},
            new ActivityTag{ActivityId=3, TagId=40},
            new ActivityTag{ActivityId=3, TagId=41},
            new ActivityTag{ActivityId=3, TagId=49},
            new ActivityTag{ActivityId=3, TagId=50},
            new ActivityTag{ActivityId=3, TagId=51},
            new ActivityTag{ActivityId=4, TagId=11},
            new ActivityTag{ActivityId=4, TagId=19},
            new ActivityTag{ActivityId=4, TagId=20},
            new ActivityTag{ActivityId=4, TagId=21},
            new ActivityTag{ActivityId=4, TagId=23},
            new ActivityTag{ActivityId=4, TagId=25},
            new ActivityTag{ActivityId=4, TagId=26},
            new ActivityTag{ActivityId=4, TagId=31},
            new ActivityTag{ActivityId=4, TagId=39},
            new ActivityTag{ActivityId=4, TagId=49},
            new ActivityTag{ActivityId=4, TagId=50},
            new ActivityTag{ActivityId=4, TagId=51},
            new ActivityTag{ActivityId=5, TagId=21},
            new ActivityTag{ActivityId=5, TagId=23},
            new ActivityTag{ActivityId=5, TagId=24},
            new ActivityTag{ActivityId=5, TagId=37},
            new ActivityTag{ActivityId=5, TagId=49},
            new ActivityTag{ActivityId=5, TagId=50},
            new ActivityTag{ActivityId=5, TagId=51},
            new ActivityTag{ActivityId=6, TagId=22},
            new ActivityTag{ActivityId=6, TagId=32},
            new ActivityTag{ActivityId=6, TagId=49},
            new ActivityTag{ActivityId=6, TagId=50},
            new ActivityTag{ActivityId=6, TagId=51},
            new ActivityTag{ActivityId=7, TagId=22},
            new ActivityTag{ActivityId=7, TagId=32},
            new ActivityTag{ActivityId=7, TagId=49},
            new ActivityTag{ActivityId=7, TagId=50},
            new ActivityTag{ActivityId=7, TagId=51},
            new ActivityTag{ActivityId=8, TagId=22},
            new ActivityTag{ActivityId=8, TagId=32},
            new ActivityTag{ActivityId=8, TagId=49},
            new ActivityTag{ActivityId=8, TagId=50},
            new ActivityTag{ActivityId=8, TagId=51},
            new ActivityTag{ActivityId=9, TagId=22},
            new ActivityTag{ActivityId=9, TagId=32},
            new ActivityTag{ActivityId=9, TagId=49},
            new ActivityTag{ActivityId=9, TagId=50},
            new ActivityTag{ActivityId=9, TagId=51},
            new ActivityTag{ActivityId=10, TagId=22},
            new ActivityTag{ActivityId=10, TagId=32},
            new ActivityTag{ActivityId=10, TagId=49},
            new ActivityTag{ActivityId=10, TagId=50},
            new ActivityTag{ActivityId=10, TagId=51},
            new ActivityTag{ActivityId=11, TagId=22},
            new ActivityTag{ActivityId=11, TagId=32},
            new ActivityTag{ActivityId=11, TagId=49},
            new ActivityTag{ActivityId=11, TagId=50},
            new ActivityTag{ActivityId=11, TagId=51},
            new ActivityTag{ActivityId=12, TagId=22},
            new ActivityTag{ActivityId=12, TagId=32},
            new ActivityTag{ActivityId=12, TagId=49},
            new ActivityTag{ActivityId=12, TagId=50},
            new ActivityTag{ActivityId=12, TagId=51},
            new ActivityTag{ActivityId=13, TagId=22},
            new ActivityTag{ActivityId=13, TagId=32},
            new ActivityTag{ActivityId=13, TagId=49},
            new ActivityTag{ActivityId=13, TagId=50},
            new ActivityTag{ActivityId=13, TagId=51},
            new ActivityTag{ActivityId=14, TagId=22},
            new ActivityTag{ActivityId=14, TagId=32},
            new ActivityTag{ActivityId=14, TagId=49},
            new ActivityTag{ActivityId=14, TagId=50},
            new ActivityTag{ActivityId=14, TagId=51},
            new ActivityTag{ActivityId=15, TagId=22},
            new ActivityTag{ActivityId=15, TagId=32},
            new ActivityTag{ActivityId=15, TagId=49},
            new ActivityTag{ActivityId=15, TagId=50},
            new ActivityTag{ActivityId=15, TagId=51},
            new ActivityTag{ActivityId=16, TagId=22},
            new ActivityTag{ActivityId=16, TagId=32},
            new ActivityTag{ActivityId=16, TagId=49},
            new ActivityTag{ActivityId=16, TagId=50},
            new ActivityTag{ActivityId=16, TagId=51},
            new ActivityTag{ActivityId=17, TagId=22},
            new ActivityTag{ActivityId=17, TagId=32},
            new ActivityTag{ActivityId=17, TagId=49},
            new ActivityTag{ActivityId=17, TagId=50},
            new ActivityTag{ActivityId=17, TagId=51},
            new ActivityTag{ActivityId=18, TagId=22},
            new ActivityTag{ActivityId=18, TagId=32},
            new ActivityTag{ActivityId=18, TagId=49},
            new ActivityTag{ActivityId=18, TagId=50},
            new ActivityTag{ActivityId=18, TagId=51},
            new ActivityTag{ActivityId=19, TagId=22},
            new ActivityTag{ActivityId=19, TagId=32},
            new ActivityTag{ActivityId=19, TagId=49},
            new ActivityTag{ActivityId=19, TagId=50},
            new ActivityTag{ActivityId=19, TagId=51},
            new ActivityTag{ActivityId=20, TagId=22},
            new ActivityTag{ActivityId=20, TagId=23},
            new ActivityTag{ActivityId=20, TagId=32},
            new ActivityTag{ActivityId=20, TagId=49},
            new ActivityTag{ActivityId=20, TagId=50},
            new ActivityTag{ActivityId=20, TagId=51},
            new ActivityTag{ActivityId=21, TagId=12},
            new ActivityTag{ActivityId=21, TagId=19},
            new ActivityTag{ActivityId=21, TagId=21},
            new ActivityTag{ActivityId=21, TagId=23},
            new ActivityTag{ActivityId=21, TagId=25},
            new ActivityTag{ActivityId=21, TagId=30},
            new ActivityTag{ActivityId=21, TagId=38},
            new ActivityTag{ActivityId=21, TagId=46},
            new ActivityTag{ActivityId=21, TagId=49},
            new ActivityTag{ActivityId=21, TagId=50},
            new ActivityTag{ActivityId=21, TagId=51},
            new ActivityTag{ActivityId=22, TagId=12},
            new ActivityTag{ActivityId=22, TagId=19},
            new ActivityTag{ActivityId=22, TagId=21},
            new ActivityTag{ActivityId=22, TagId=23},
            new ActivityTag{ActivityId=22, TagId=25},
            new ActivityTag{ActivityId=22, TagId=30},
            new ActivityTag{ActivityId=22, TagId=36},
            new ActivityTag{ActivityId=22, TagId=38},
            new ActivityTag{ActivityId=22, TagId=39},
            new ActivityTag{ActivityId=22, TagId=49},
            new ActivityTag{ActivityId=22, TagId=50},
            new ActivityTag{ActivityId=22, TagId=51},
            new ActivityTag{ActivityId=23, TagId=21},
            new ActivityTag{ActivityId=23, TagId=25},
            new ActivityTag{ActivityId=23, TagId=36},
            new ActivityTag{ActivityId=23, TagId=49},
            new ActivityTag{ActivityId=23, TagId=50},
            new ActivityTag{ActivityId=23, TagId=51},
            new ActivityTag{ActivityId=24, TagId=21},
            new ActivityTag{ActivityId=24, TagId=23},
            new ActivityTag{ActivityId=24, TagId=25},
            new ActivityTag{ActivityId=24, TagId=36},
            new ActivityTag{ActivityId=24, TagId=38},
            new ActivityTag{ActivityId=24, TagId=42},
            new ActivityTag{ActivityId=24, TagId=49},
            new ActivityTag{ActivityId=24, TagId=50},
            new ActivityTag{ActivityId=24, TagId=51},
            new ActivityTag{ActivityId=25, TagId=21},
            new ActivityTag{ActivityId=25, TagId=23},
            new ActivityTag{ActivityId=25, TagId=25},
            new ActivityTag{ActivityId=25, TagId=34},
            new ActivityTag{ActivityId=25, TagId=36},
            new ActivityTag{ActivityId=25, TagId=49},
            new ActivityTag{ActivityId=25, TagId=50},
            new ActivityTag{ActivityId=25, TagId=51},
            new ActivityTag{ActivityId=26, TagId=11},
            new ActivityTag{ActivityId=26, TagId=25},
            new ActivityTag{ActivityId=26, TagId=35},
            new ActivityTag{ActivityId=26, TagId=36},
            new ActivityTag{ActivityId=26, TagId=39},
            new ActivityTag{ActivityId=26, TagId=49},
            new ActivityTag{ActivityId=26, TagId=50},
            new ActivityTag{ActivityId=26, TagId=51},
            new ActivityTag{ActivityId=27, TagId=42},
            new ActivityTag{ActivityId=27, TagId=49},
            new ActivityTag{ActivityId=27, TagId=50},
            new ActivityTag{ActivityId=27, TagId=51},
            new ActivityTag{ActivityId=28, TagId=21},
            new ActivityTag{ActivityId=28, TagId=23},
            new ActivityTag{ActivityId=28, TagId=25},
            new ActivityTag{ActivityId=28, TagId=32},
            new ActivityTag{ActivityId=28, TagId=49},
            new ActivityTag{ActivityId=28, TagId=50},
            new ActivityTag{ActivityId=28, TagId=51},
            new ActivityTag{ActivityId=29, TagId=13},
            new ActivityTag{ActivityId=29, TagId=14},
            new ActivityTag{ActivityId=29, TagId=15},
            new ActivityTag{ActivityId=29, TagId=21},
            new ActivityTag{ActivityId=29, TagId=23},
            new ActivityTag{ActivityId=29, TagId=25},
            new ActivityTag{ActivityId=29, TagId=34},
            new ActivityTag{ActivityId=29, TagId=36},
            new ActivityTag{ActivityId=29, TagId=38},
            new ActivityTag{ActivityId=29, TagId=39},
            new ActivityTag{ActivityId=29, TagId=40},
            new ActivityTag{ActivityId=29, TagId=41},
            new ActivityTag{ActivityId=29, TagId=49},
            new ActivityTag{ActivityId=29, TagId=50},
            new ActivityTag{ActivityId=29, TagId=51},
            new ActivityTag{ActivityId=30, TagId=21},
            new ActivityTag{ActivityId=30, TagId=23},
            new ActivityTag{ActivityId=30, TagId=25},
            new ActivityTag{ActivityId=30, TagId=49},
            new ActivityTag{ActivityId=30, TagId=50},
            new ActivityTag{ActivityId=30, TagId=51},
            new ActivityTag{ActivityId=31, TagId=23},
            new ActivityTag{ActivityId=31, TagId=25},
            new ActivityTag{ActivityId=31, TagId=28},
            new ActivityTag{ActivityId=31, TagId=32},
            new ActivityTag{ActivityId=31, TagId=49},
            new ActivityTag{ActivityId=31, TagId=50},
            new ActivityTag{ActivityId=31, TagId=51},
            new ActivityTag{ActivityId=32, TagId=23},
            new ActivityTag{ActivityId=32, TagId=25},
            new ActivityTag{ActivityId=32, TagId=32},
            new ActivityTag{ActivityId=32, TagId=33},
            new ActivityTag{ActivityId=32, TagId=49},
            new ActivityTag{ActivityId=32, TagId=50},
            new ActivityTag{ActivityId=32, TagId=51},
            new ActivityTag{ActivityId=33, TagId=23},
            new ActivityTag{ActivityId=33, TagId=25},
            new ActivityTag{ActivityId=33, TagId=38},
            new ActivityTag{ActivityId=33, TagId=49},
            new ActivityTag{ActivityId=33, TagId=50},
            new ActivityTag{ActivityId=33, TagId=51},
            new ActivityTag{ActivityId=34, TagId=23},
            new ActivityTag{ActivityId=34, TagId=25},
            new ActivityTag{ActivityId=34, TagId=38},
            new ActivityTag{ActivityId=34, TagId=49},
            new ActivityTag{ActivityId=34, TagId=50},
            new ActivityTag{ActivityId=34, TagId=51},
            new ActivityTag{ActivityId=35, TagId=23},
            new ActivityTag{ActivityId=35, TagId=25},
            new ActivityTag{ActivityId=35, TagId=33},
            new ActivityTag{ActivityId=35, TagId=34},
            new ActivityTag{ActivityId=35, TagId=36},
            new ActivityTag{ActivityId=35, TagId=38},
            new ActivityTag{ActivityId=35, TagId=49},
            new ActivityTag{ActivityId=35, TagId=50},
            new ActivityTag{ActivityId=35, TagId=51},
            new ActivityTag{ActivityId=36, TagId=23},
            new ActivityTag{ActivityId=36, TagId=25},
            new ActivityTag{ActivityId=36, TagId=33},
            new ActivityTag{ActivityId=36, TagId=49},
            new ActivityTag{ActivityId=36, TagId=50},
            new ActivityTag{ActivityId=36, TagId=51},
            new ActivityTag{ActivityId=37, TagId=25},
            new ActivityTag{ActivityId=37, TagId=33},
            new ActivityTag{ActivityId=37, TagId=46},
            new ActivityTag{ActivityId=37, TagId=49},
            new ActivityTag{ActivityId=37, TagId=50},
            new ActivityTag{ActivityId=37, TagId=51},
            new ActivityTag{ActivityId=38, TagId=25},
            new ActivityTag{ActivityId=38, TagId=33},
            new ActivityTag{ActivityId=38, TagId=49},
            new ActivityTag{ActivityId=38, TagId=50},
            new ActivityTag{ActivityId=38, TagId=51},
            new ActivityTag{ActivityId=39, TagId=25},
            new ActivityTag{ActivityId=39, TagId=33},
            new ActivityTag{ActivityId=39, TagId=49},
            new ActivityTag{ActivityId=39, TagId=50},
            new ActivityTag{ActivityId=39, TagId=51},
            new ActivityTag{ActivityId=40, TagId=25},
            new ActivityTag{ActivityId=40, TagId=49},
            new ActivityTag{ActivityId=40, TagId=50},
            new ActivityTag{ActivityId=40, TagId=51},
            new ActivityTag{ActivityId=41, TagId=25},
            new ActivityTag{ActivityId=41, TagId=49},
            new ActivityTag{ActivityId=41, TagId=50},
            new ActivityTag{ActivityId=41, TagId=51},
            new ActivityTag{ActivityId=42, TagId=25},
            new ActivityTag{ActivityId=42, TagId=49},
            new ActivityTag{ActivityId=42, TagId=50},
            new ActivityTag{ActivityId=42, TagId=51},
            new ActivityTag{ActivityId=43, TagId=25},
            new ActivityTag{ActivityId=43, TagId=49},
            new ActivityTag{ActivityId=43, TagId=50},
            new ActivityTag{ActivityId=43, TagId=51},
            new ActivityTag{ActivityId=44, TagId=21},
            new ActivityTag{ActivityId=44, TagId=23},
            new ActivityTag{ActivityId=44, TagId=25},
            new ActivityTag{ActivityId=44, TagId=26},
            new ActivityTag{ActivityId=44, TagId=32},
            new ActivityTag{ActivityId=44, TagId=36},
            new ActivityTag{ActivityId=44, TagId=39},
            new ActivityTag{ActivityId=44, TagId=49},
            new ActivityTag{ActivityId=44, TagId=50},
            new ActivityTag{ActivityId=44, TagId=51},
            new ActivityTag{ActivityId=45, TagId=23},
            new ActivityTag{ActivityId=45, TagId=25},
            new ActivityTag{ActivityId=45, TagId=49},
            new ActivityTag{ActivityId=45, TagId=50},
            new ActivityTag{ActivityId=45, TagId=51},
            new ActivityTag{ActivityId=46, TagId=23},
            new ActivityTag{ActivityId=46, TagId=25},
            new ActivityTag{ActivityId=46, TagId=28},
            new ActivityTag{ActivityId=46, TagId=36},
            new ActivityTag{ActivityId=46, TagId=38},
            new ActivityTag{ActivityId=46, TagId=46},
            new ActivityTag{ActivityId=46, TagId=49},
            new ActivityTag{ActivityId=46, TagId=50},
            new ActivityTag{ActivityId=46, TagId=51},
            new ActivityTag{ActivityId=47, TagId=21},
            new ActivityTag{ActivityId=47, TagId=23},
            new ActivityTag{ActivityId=47, TagId=25},
            new ActivityTag{ActivityId=47, TagId=36},
            new ActivityTag{ActivityId=47, TagId=39},
            new ActivityTag{ActivityId=47, TagId=49},
            new ActivityTag{ActivityId=47, TagId=50},
            new ActivityTag{ActivityId=47, TagId=51},
            new ActivityTag{ActivityId=48, TagId=23},
            new ActivityTag{ActivityId=48, TagId=25},
            new ActivityTag{ActivityId=48, TagId=28},
            new ActivityTag{ActivityId=48, TagId=36},
            new ActivityTag{ActivityId=48, TagId=38},
            new ActivityTag{ActivityId=48, TagId=46},
            new ActivityTag{ActivityId=48, TagId=49},
            new ActivityTag{ActivityId=48, TagId=50},
            new ActivityTag{ActivityId=48, TagId=51},
            new ActivityTag{ActivityId=49, TagId=23},
            new ActivityTag{ActivityId=49, TagId=25},
            new ActivityTag{ActivityId=49, TagId=28},
            new ActivityTag{ActivityId=49, TagId=36},
            new ActivityTag{ActivityId=49, TagId=49},
            new ActivityTag{ActivityId=49, TagId=50},
            new ActivityTag{ActivityId=49, TagId=51},
            new ActivityTag{ActivityId=50, TagId=21},
            new ActivityTag{ActivityId=50, TagId=25},
            new ActivityTag{ActivityId=50, TagId=36},
            new ActivityTag{ActivityId=50, TagId=49},
            new ActivityTag{ActivityId=50, TagId=50},
            new ActivityTag{ActivityId=50, TagId=51},
            new ActivityTag{ActivityId=51, TagId=21},
            new ActivityTag{ActivityId=51, TagId=23},
            new ActivityTag{ActivityId=51, TagId=25},
            new ActivityTag{ActivityId=51, TagId=36},
            new ActivityTag{ActivityId=51, TagId=38},
            new ActivityTag{ActivityId=51, TagId=49},
            new ActivityTag{ActivityId=51, TagId=50},
            new ActivityTag{ActivityId=51, TagId=51},
            new ActivityTag{ActivityId=52, TagId=21},
            new ActivityTag{ActivityId=52, TagId=23},
            new ActivityTag{ActivityId=52, TagId=25},
            new ActivityTag{ActivityId=52, TagId=36},
            new ActivityTag{ActivityId=52, TagId=38},
            new ActivityTag{ActivityId=52, TagId=49},
            new ActivityTag{ActivityId=52, TagId=50},
            new ActivityTag{ActivityId=52, TagId=51},
            new ActivityTag{ActivityId=53, TagId=21},
            new ActivityTag{ActivityId=53, TagId=23},
            new ActivityTag{ActivityId=53, TagId=25},
            new ActivityTag{ActivityId=53, TagId=36},
            new ActivityTag{ActivityId=53, TagId=38},
            new ActivityTag{ActivityId=53, TagId=49},
            new ActivityTag{ActivityId=53, TagId=50},
            new ActivityTag{ActivityId=53, TagId=51},
            new ActivityTag{ActivityId=54, TagId=25},
            new ActivityTag{ActivityId=54, TagId=49},
            new ActivityTag{ActivityId=54, TagId=50},
            new ActivityTag{ActivityId=54, TagId=51},
            new ActivityTag{ActivityId=55, TagId=25},
            new ActivityTag{ActivityId=55, TagId=49},
            new ActivityTag{ActivityId=55, TagId=50},
            new ActivityTag{ActivityId=55, TagId=51},
            new ActivityTag{ActivityId=56, TagId=25},
            new ActivityTag{ActivityId=56, TagId=49},
            new ActivityTag{ActivityId=56, TagId=50},
            new ActivityTag{ActivityId=56, TagId=51},
            new ActivityTag{ActivityId=57, TagId=25},
            new ActivityTag{ActivityId=57, TagId=49},
            new ActivityTag{ActivityId=57, TagId=50},
            new ActivityTag{ActivityId=57, TagId=51},
            new ActivityTag{ActivityId=58, TagId=21},
            new ActivityTag{ActivityId=58, TagId=23},
            new ActivityTag{ActivityId=58, TagId=25},
            new ActivityTag{ActivityId=58, TagId=26},
            new ActivityTag{ActivityId=58, TagId=36},
            new ActivityTag{ActivityId=58, TagId=39},
            new ActivityTag{ActivityId=58, TagId=40},
            new ActivityTag{ActivityId=58, TagId=42},
            new ActivityTag{ActivityId=58, TagId=49},
            new ActivityTag{ActivityId=58, TagId=50},
            new ActivityTag{ActivityId=58, TagId=51},
            new ActivityTag{ActivityId=59, TagId=25},
            new ActivityTag{ActivityId=59, TagId=49},
            new ActivityTag{ActivityId=59, TagId=50},
            new ActivityTag{ActivityId=59, TagId=51},
            new ActivityTag{ActivityId=60, TagId=11},
            new ActivityTag{ActivityId=60, TagId=19},
            new ActivityTag{ActivityId=60, TagId=20},
            new ActivityTag{ActivityId=60, TagId=21},
            new ActivityTag{ActivityId=60, TagId=23},
            new ActivityTag{ActivityId=60, TagId=25},
            new ActivityTag{ActivityId=60, TagId=31},
            new ActivityTag{ActivityId=60, TagId=49},
            new ActivityTag{ActivityId=60, TagId=50},
            new ActivityTag{ActivityId=60, TagId=51},
            new ActivityTag{ActivityId=61, TagId=49},
            new ActivityTag{ActivityId=61, TagId=50},
            new ActivityTag{ActivityId=61, TagId=51},
            new ActivityTag{ActivityId=62, TagId=11},
            new ActivityTag{ActivityId=62, TagId=25},
            new ActivityTag{ActivityId=62, TagId=32},
            new ActivityTag{ActivityId=62, TagId=33},
            new ActivityTag{ActivityId=62, TagId=49},
            new ActivityTag{ActivityId=62, TagId=50},
            new ActivityTag{ActivityId=62, TagId=51},
            new ActivityTag{ActivityId=63, TagId=11},
            new ActivityTag{ActivityId=63, TagId=25},
            new ActivityTag{ActivityId=63, TagId=32},
            new ActivityTag{ActivityId=63, TagId=33},
            new ActivityTag{ActivityId=63, TagId=49},
            new ActivityTag{ActivityId=63, TagId=50},
            new ActivityTag{ActivityId=63, TagId=51},
            new ActivityTag{ActivityId=65, TagId=11},
            new ActivityTag{ActivityId=65, TagId=25},
            new ActivityTag{ActivityId=65, TagId=32},
            new ActivityTag{ActivityId=65, TagId=33},
            new ActivityTag{ActivityId=65, TagId=49},
            new ActivityTag{ActivityId=65, TagId=50},
            new ActivityTag{ActivityId=65, TagId=51},
            new ActivityTag{ActivityId=66, TagId=11},
            new ActivityTag{ActivityId=66, TagId=25},
            new ActivityTag{ActivityId=66, TagId=32},
            new ActivityTag{ActivityId=66, TagId=33},
            new ActivityTag{ActivityId=66, TagId=49},
            new ActivityTag{ActivityId=66, TagId=50},
            new ActivityTag{ActivityId=66, TagId=51},
            new ActivityTag{ActivityId=67, TagId=32},
            new ActivityTag{ActivityId=67, TagId=33},
            new ActivityTag{ActivityId=67, TagId=49},
            new ActivityTag{ActivityId=67, TagId=50},
            new ActivityTag{ActivityId=67, TagId=51},
            new ActivityTag{ActivityId=68, TagId=11},
            new ActivityTag{ActivityId=68, TagId=25},
            new ActivityTag{ActivityId=68, TagId=32},
            new ActivityTag{ActivityId=68, TagId=33},
            new ActivityTag{ActivityId=68, TagId=49},
            new ActivityTag{ActivityId=68, TagId=50},
            new ActivityTag{ActivityId=68, TagId=51},
            new ActivityTag{ActivityId=69, TagId=19},
            new ActivityTag{ActivityId=69, TagId=20},
            new ActivityTag{ActivityId=69, TagId=23},
            new ActivityTag{ActivityId=69, TagId=25},
            new ActivityTag{ActivityId=69, TagId=26},
            new ActivityTag{ActivityId=69, TagId=30},
            new ActivityTag{ActivityId=69, TagId=36},
            new ActivityTag{ActivityId=69, TagId=38},
            new ActivityTag{ActivityId=69, TagId=39},
            new ActivityTag{ActivityId=69, TagId=49},
            new ActivityTag{ActivityId=69, TagId=50},
            new ActivityTag{ActivityId=69, TagId=51},
            new ActivityTag{ActivityId=70, TagId=11},
            new ActivityTag{ActivityId=70, TagId=19},
            new ActivityTag{ActivityId=70, TagId=20},
            new ActivityTag{ActivityId=70, TagId=21},
            new ActivityTag{ActivityId=70, TagId=23},
            new ActivityTag{ActivityId=70, TagId=25},
            new ActivityTag{ActivityId=70, TagId=26},
            new ActivityTag{ActivityId=70, TagId=31},
            new ActivityTag{ActivityId=70, TagId=39},
            new ActivityTag{ActivityId=70, TagId=49},
            new ActivityTag{ActivityId=70, TagId=50},
            new ActivityTag{ActivityId=70, TagId=51},
            new ActivityTag{ActivityId=71, TagId=11},
            new ActivityTag{ActivityId=71, TagId=23},
            new ActivityTag{ActivityId=71, TagId=26},
            new ActivityTag{ActivityId=71, TagId=35},
            new ActivityTag{ActivityId=71, TagId=39},
            new ActivityTag{ActivityId=71, TagId=49},
            new ActivityTag{ActivityId=71, TagId=50},
            new ActivityTag{ActivityId=71, TagId=51},
            new ActivityTag{ActivityId=72, TagId=11},
            new ActivityTag{ActivityId=72, TagId=19},
            new ActivityTag{ActivityId=72, TagId=20},
            new ActivityTag{ActivityId=72, TagId=23},
            new ActivityTag{ActivityId=72, TagId=26},
            new ActivityTag{ActivityId=72, TagId=31},
            new ActivityTag{ActivityId=72, TagId=49},
            new ActivityTag{ActivityId=72, TagId=50},
            new ActivityTag{ActivityId=72, TagId=51},
            new ActivityTag{ActivityId=73, TagId=19},
            new ActivityTag{ActivityId=73, TagId=20},
            new ActivityTag{ActivityId=73, TagId=23},
            new ActivityTag{ActivityId=73, TagId=26},
            new ActivityTag{ActivityId=73, TagId=31},
            new ActivityTag{ActivityId=73, TagId=39},
            new ActivityTag{ActivityId=73, TagId=49},
            new ActivityTag{ActivityId=73, TagId=50},
            new ActivityTag{ActivityId=73, TagId=51},
            new ActivityTag{ActivityId=74, TagId=28},
            new ActivityTag{ActivityId=74, TagId=34},
            new ActivityTag{ActivityId=74, TagId=43},
            new ActivityTag{ActivityId=74, TagId=49},
            new ActivityTag{ActivityId=74, TagId=50},
            new ActivityTag{ActivityId=74, TagId=51},
            new ActivityTag{ActivityId=75, TagId=28},
            new ActivityTag{ActivityId=75, TagId=34},
            new ActivityTag{ActivityId=75, TagId=43},
            new ActivityTag{ActivityId=75, TagId=49},
            new ActivityTag{ActivityId=75, TagId=50},
            new ActivityTag{ActivityId=75, TagId=51},
            new ActivityTag{ActivityId=76, TagId=28},
            new ActivityTag{ActivityId=76, TagId=34},
            new ActivityTag{ActivityId=76, TagId=43},
            new ActivityTag{ActivityId=76, TagId=49},
            new ActivityTag{ActivityId=76, TagId=50},
            new ActivityTag{ActivityId=76, TagId=51},
            new ActivityTag{ActivityId=77, TagId=28},
            new ActivityTag{ActivityId=77, TagId=34},
            new ActivityTag{ActivityId=77, TagId=35},
            new ActivityTag{ActivityId=77, TagId=36},
            new ActivityTag{ActivityId=77, TagId=49},
            new ActivityTag{ActivityId=77, TagId=50},
            new ActivityTag{ActivityId=77, TagId=51},
            new ActivityTag{ActivityId=78, TagId=28},
            new ActivityTag{ActivityId=78, TagId=34},
            new ActivityTag{ActivityId=78, TagId=35},
            new ActivityTag{ActivityId=78, TagId=36},
            new ActivityTag{ActivityId=78, TagId=49},
            new ActivityTag{ActivityId=78, TagId=50},
            new ActivityTag{ActivityId=78, TagId=51},
            new ActivityTag{ActivityId=79, TagId=19},
            new ActivityTag{ActivityId=79, TagId=23},
            new ActivityTag{ActivityId=79, TagId=26},
            new ActivityTag{ActivityId=79, TagId=29},
            new ActivityTag{ActivityId=79, TagId=30},
            new ActivityTag{ActivityId=79, TagId=36},
            new ActivityTag{ActivityId=79, TagId=38},
            new ActivityTag{ActivityId=79, TagId=39},
            new ActivityTag{ActivityId=79, TagId=40},
            new ActivityTag{ActivityId=79, TagId=49},
            new ActivityTag{ActivityId=79, TagId=50},
            new ActivityTag{ActivityId=79, TagId=51},
            new ActivityTag{ActivityId=80, TagId=19},
            new ActivityTag{ActivityId=80, TagId=23},
            new ActivityTag{ActivityId=80, TagId=26},
            new ActivityTag{ActivityId=80, TagId=29},
            new ActivityTag{ActivityId=80, TagId=30},
            new ActivityTag{ActivityId=80, TagId=36},
            new ActivityTag{ActivityId=80, TagId=38},
            new ActivityTag{ActivityId=80, TagId=39},
            new ActivityTag{ActivityId=80, TagId=40},
            new ActivityTag{ActivityId=80, TagId=49},
            new ActivityTag{ActivityId=80, TagId=50},
            new ActivityTag{ActivityId=80, TagId=51},
            new ActivityTag{ActivityId=81, TagId=19},
            new ActivityTag{ActivityId=81, TagId=23},
            new ActivityTag{ActivityId=81, TagId=26},
            new ActivityTag{ActivityId=81, TagId=29},
            new ActivityTag{ActivityId=81, TagId=30},
            new ActivityTag{ActivityId=81, TagId=36},
            new ActivityTag{ActivityId=81, TagId=38},
            new ActivityTag{ActivityId=81, TagId=39},
            new ActivityTag{ActivityId=81, TagId=40},
            new ActivityTag{ActivityId=81, TagId=49},
            new ActivityTag{ActivityId=81, TagId=50},
            new ActivityTag{ActivityId=81, TagId=51},
            new ActivityTag{ActivityId=82, TagId=18},
            new ActivityTag{ActivityId=82, TagId=19},
            new ActivityTag{ActivityId=82, TagId=20},
            new ActivityTag{ActivityId=82, TagId=23},
            new ActivityTag{ActivityId=82, TagId=26},
            new ActivityTag{ActivityId=82, TagId=28},
            new ActivityTag{ActivityId=82, TagId=29},
            new ActivityTag{ActivityId=82, TagId=30},
            new ActivityTag{ActivityId=82, TagId=31},
            new ActivityTag{ActivityId=82, TagId=36},
            new ActivityTag{ActivityId=82, TagId=39},
            new ActivityTag{ActivityId=82, TagId=40},
            new ActivityTag{ActivityId=82, TagId=42},
            new ActivityTag{ActivityId=82, TagId=43},
            new ActivityTag{ActivityId=82, TagId=44},
            new ActivityTag{ActivityId=82, TagId=49},
            new ActivityTag{ActivityId=82, TagId=50},
            new ActivityTag{ActivityId=82, TagId=51},
            new ActivityTag{ActivityId=83, TagId=19},
            new ActivityTag{ActivityId=83, TagId=23},
            new ActivityTag{ActivityId=83, TagId=26},
            new ActivityTag{ActivityId=83, TagId=29},
            new ActivityTag{ActivityId=83, TagId=30},
            new ActivityTag{ActivityId=83, TagId=31},
            new ActivityTag{ActivityId=83, TagId=36},
            new ActivityTag{ActivityId=83, TagId=39},
            new ActivityTag{ActivityId=83, TagId=40},
            new ActivityTag{ActivityId=83, TagId=49},
            new ActivityTag{ActivityId=83, TagId=50},
            new ActivityTag{ActivityId=83, TagId=51},
            new ActivityTag{ActivityId=84, TagId=11},
            new ActivityTag{ActivityId=84, TagId=19},
            new ActivityTag{ActivityId=84, TagId=20},
            new ActivityTag{ActivityId=84, TagId=21},
            new ActivityTag{ActivityId=84, TagId=25},
            new ActivityTag{ActivityId=84, TagId=26},
            new ActivityTag{ActivityId=84, TagId=30},
            new ActivityTag{ActivityId=84, TagId=35},
            new ActivityTag{ActivityId=84, TagId=36},
            new ActivityTag{ActivityId=84, TagId=38},
            new ActivityTag{ActivityId=84, TagId=39},
            new ActivityTag{ActivityId=84, TagId=49},
            new ActivityTag{ActivityId=84, TagId=50},
            new ActivityTag{ActivityId=84, TagId=51},
            new ActivityTag{ActivityId=85, TagId=23},
            new ActivityTag{ActivityId=85, TagId=32},
            new ActivityTag{ActivityId=85, TagId=34},
            new ActivityTag{ActivityId=85, TagId=43},
            new ActivityTag{ActivityId=85, TagId=49},
            new ActivityTag{ActivityId=85, TagId=50},
            new ActivityTag{ActivityId=85, TagId=51},
            new ActivityTag{ActivityId=86, TagId=19},
            new ActivityTag{ActivityId=86, TagId=20},
            new ActivityTag{ActivityId=86, TagId=23},
            new ActivityTag{ActivityId=86, TagId=26},
            new ActivityTag{ActivityId=86, TagId=28},
            new ActivityTag{ActivityId=86, TagId=30},
            new ActivityTag{ActivityId=86, TagId=31},
            new ActivityTag{ActivityId=86, TagId=39},
            new ActivityTag{ActivityId=86, TagId=42},
            new ActivityTag{ActivityId=86, TagId=49},
            new ActivityTag{ActivityId=86, TagId=50},
            new ActivityTag{ActivityId=86, TagId=51},
            new ActivityTag{ActivityId=87, TagId=19},
            new ActivityTag{ActivityId=87, TagId=20},
            new ActivityTag{ActivityId=87, TagId=23},
            new ActivityTag{ActivityId=87, TagId=26},
            new ActivityTag{ActivityId=87, TagId=38},
            new ActivityTag{ActivityId=87, TagId=39},
            new ActivityTag{ActivityId=87, TagId=49},
            new ActivityTag{ActivityId=87, TagId=50},
            new ActivityTag{ActivityId=87, TagId=51},
            new ActivityTag{ActivityId=88, TagId=19},
            new ActivityTag{ActivityId=88, TagId=20},
            new ActivityTag{ActivityId=88, TagId=23},
            new ActivityTag{ActivityId=88, TagId=26},
            new ActivityTag{ActivityId=88, TagId=30},
            new ActivityTag{ActivityId=88, TagId=36},
            new ActivityTag{ActivityId=88, TagId=38},
            new ActivityTag{ActivityId=88, TagId=39},
            new ActivityTag{ActivityId=88, TagId=49},
            new ActivityTag{ActivityId=88, TagId=50},
            new ActivityTag{ActivityId=88, TagId=51},
            new ActivityTag{ActivityId=89, TagId=11},
            new ActivityTag{ActivityId=89, TagId=19},
            new ActivityTag{ActivityId=89, TagId=20},
            new ActivityTag{ActivityId=89, TagId=23},
            new ActivityTag{ActivityId=89, TagId=25},
            new ActivityTag{ActivityId=89, TagId=26},
            new ActivityTag{ActivityId=89, TagId=29},
            new ActivityTag{ActivityId=89, TagId=31},
            new ActivityTag{ActivityId=89, TagId=36},
            new ActivityTag{ActivityId=89, TagId=37},
            new ActivityTag{ActivityId=89, TagId=39},
            new ActivityTag{ActivityId=89, TagId=40},
            new ActivityTag{ActivityId=89, TagId=49},
            new ActivityTag{ActivityId=89, TagId=50},
            new ActivityTag{ActivityId=89, TagId=51},
            new ActivityTag{ActivityId=90, TagId=21},
            new ActivityTag{ActivityId=90, TagId=23},
            new ActivityTag{ActivityId=90, TagId=25},
            new ActivityTag{ActivityId=90, TagId=36},
            new ActivityTag{ActivityId=90, TagId=37},
            new ActivityTag{ActivityId=90, TagId=38},
            new ActivityTag{ActivityId=90, TagId=40},
            new ActivityTag{ActivityId=90, TagId=41},
            new ActivityTag{ActivityId=90, TagId=46},
            new ActivityTag{ActivityId=90, TagId=49},
            new ActivityTag{ActivityId=90, TagId=50},
            new ActivityTag{ActivityId=90, TagId=51},
            new ActivityTag{ActivityId=91, TagId=23},
            new ActivityTag{ActivityId=91, TagId=49},
            new ActivityTag{ActivityId=91, TagId=50},
            new ActivityTag{ActivityId=91, TagId=51},
            new ActivityTag{ActivityId=92, TagId=23},
            new ActivityTag{ActivityId=92, TagId=26},
            new ActivityTag{ActivityId=92, TagId=27},
            new ActivityTag{ActivityId=92, TagId=29},
            new ActivityTag{ActivityId=92, TagId=30},
            new ActivityTag{ActivityId=92, TagId=31},
            new ActivityTag{ActivityId=92, TagId=36},
            new ActivityTag{ActivityId=92, TagId=39},
            new ActivityTag{ActivityId=92, TagId=40},
            new ActivityTag{ActivityId=92, TagId=42},
            new ActivityTag{ActivityId=92, TagId=49},
            new ActivityTag{ActivityId=92, TagId=50},
            new ActivityTag{ActivityId=92, TagId=51},
            new ActivityTag{ActivityId=93, TagId=23},
            new ActivityTag{ActivityId=93, TagId=27},
            new ActivityTag{ActivityId=93, TagId=35},
            new ActivityTag{ActivityId=93, TagId=39},
            new ActivityTag{ActivityId=93, TagId=40},
            new ActivityTag{ActivityId=93, TagId=42},
            new ActivityTag{ActivityId=93, TagId=43},
            new ActivityTag{ActivityId=93, TagId=44},
            new ActivityTag{ActivityId=93, TagId=45},
            new ActivityTag{ActivityId=93, TagId=46},
            new ActivityTag{ActivityId=93, TagId=49},
            new ActivityTag{ActivityId=93, TagId=50},
            new ActivityTag{ActivityId=93, TagId=51},
            new ActivityTag{ActivityId=94, TagId=23},
            new ActivityTag{ActivityId=94, TagId=27},
            new ActivityTag{ActivityId=94, TagId=33},
            new ActivityTag{ActivityId=94, TagId=37},
            new ActivityTag{ActivityId=94, TagId=49},
            new ActivityTag{ActivityId=94, TagId=50},
            new ActivityTag{ActivityId=94, TagId=51},
            new ActivityTag{ActivityId=95, TagId=13},
            new ActivityTag{ActivityId=95, TagId=14},
            new ActivityTag{ActivityId=95, TagId=15},
            new ActivityTag{ActivityId=95, TagId=16},
            new ActivityTag{ActivityId=95, TagId=17},
            new ActivityTag{ActivityId=95, TagId=21},
            new ActivityTag{ActivityId=95, TagId=23},
            new ActivityTag{ActivityId=95, TagId=25},
            new ActivityTag{ActivityId=95, TagId=30},
            new ActivityTag{ActivityId=95, TagId=35},
            new ActivityTag{ActivityId=95, TagId=36},
            new ActivityTag{ActivityId=95, TagId=38},
            new ActivityTag{ActivityId=95, TagId=41},
            new ActivityTag{ActivityId=95, TagId=46},
            new ActivityTag{ActivityId=95, TagId=47},
            new ActivityTag{ActivityId=95, TagId=48},
            new ActivityTag{ActivityId=95, TagId=49},
            new ActivityTag{ActivityId=95, TagId=50},
            new ActivityTag{ActivityId=95, TagId=51},
            new ActivityTag{ActivityId=95, TagId=52},
            new ActivityTag{ActivityId=95, TagId=53},
            new ActivityTag{ActivityId=95, TagId=54},
            new ActivityTag{ActivityId=96, TagId=21},
            new ActivityTag{ActivityId=96, TagId=22},
            new ActivityTag{ActivityId=96, TagId=23},
            new ActivityTag{ActivityId=96, TagId=25},
            new ActivityTag{ActivityId=96, TagId=28},
            new ActivityTag{ActivityId=96, TagId=36},
            new ActivityTag{ActivityId=96, TagId=38},
            new ActivityTag{ActivityId=96, TagId=39},
            new ActivityTag{ActivityId=96, TagId=47},
            new ActivityTag{ActivityId=96, TagId=48},
            new ActivityTag{ActivityId=96, TagId=49},
            new ActivityTag{ActivityId=96, TagId=50},
            new ActivityTag{ActivityId=96, TagId=51},
            new ActivityTag{ActivityId=96, TagId=52},
            new ActivityTag{ActivityId=96, TagId=53},
            new ActivityTag{ActivityId=96, TagId=54},
            new ActivityTag{ActivityId=97, TagId=21},
            new ActivityTag{ActivityId=97, TagId=23},
            new ActivityTag{ActivityId=97, TagId=25},
            new ActivityTag{ActivityId=97, TagId=36},
            new ActivityTag{ActivityId=97, TagId=38},
            new ActivityTag{ActivityId=97, TagId=41},
            new ActivityTag{ActivityId=97, TagId=49},
            new ActivityTag{ActivityId=97, TagId=50},
            new ActivityTag{ActivityId=97, TagId=51},
            new ActivityTag{ActivityId=97, TagId=52},
            new ActivityTag{ActivityId=97, TagId=53},
            new ActivityTag{ActivityId=97, TagId=54},
            new ActivityTag{ActivityId=98, TagId=23},
            new ActivityTag{ActivityId=98, TagId=25},
            new ActivityTag{ActivityId=98, TagId=33},
            new ActivityTag{ActivityId=98, TagId=34},
            new ActivityTag{ActivityId=98, TagId=35},
            new ActivityTag{ActivityId=98, TagId=36},
            new ActivityTag{ActivityId=98, TagId=38},
            new ActivityTag{ActivityId=99, TagId=11},
            new ActivityTag{ActivityId=99, TagId=18},
            new ActivityTag{ActivityId=99, TagId=19},
            new ActivityTag{ActivityId=99, TagId=20},
            new ActivityTag{ActivityId=99, TagId=23},
            new ActivityTag{ActivityId=99, TagId=26},
            new ActivityTag{ActivityId=99, TagId=29},
            new ActivityTag{ActivityId=99, TagId=31},
            new ActivityTag{ActivityId=99, TagId=34},
            new ActivityTag{ActivityId=99, TagId=35},
            new ActivityTag{ActivityId=99, TagId=36},
            new ActivityTag{ActivityId=99, TagId=39},
            new ActivityTag{ActivityId=99, TagId=40},
            new ActivityTag{ActivityId=99, TagId=42},
            new ActivityTag{ActivityId=99, TagId=48},
            new ActivityTag{ActivityId=99, TagId=49},
            new ActivityTag{ActivityId=99, TagId=50},
            new ActivityTag{ActivityId=99, TagId=51},
            new ActivityTag{ActivityId=99, TagId=52},
            new ActivityTag{ActivityId=99, TagId=53},
            new ActivityTag{ActivityId=99, TagId=54},
            new ActivityTag{ActivityId=100, TagId=18},
            new ActivityTag{ActivityId=100, TagId=19},
            new ActivityTag{ActivityId=100, TagId=22},
            new ActivityTag{ActivityId=100, TagId=23},
            new ActivityTag{ActivityId=100, TagId=26},
            new ActivityTag{ActivityId=100, TagId=29},
            new ActivityTag{ActivityId=100, TagId=36},
            new ActivityTag{ActivityId=100, TagId=39},
            new ActivityTag{ActivityId=100, TagId=40},
            new ActivityTag{ActivityId=100, TagId=49},
            new ActivityTag{ActivityId=100, TagId=50},
            new ActivityTag{ActivityId=100, TagId=51},
            new ActivityTag{ActivityId=100, TagId=52},
            new ActivityTag{ActivityId=100, TagId=53},
            new ActivityTag{ActivityId=100, TagId=54},
            new ActivityTag{ActivityId=101, TagId=18},
            new ActivityTag{ActivityId=101, TagId=19},
            new ActivityTag{ActivityId=101, TagId=23},
            new ActivityTag{ActivityId=101, TagId=26},
            new ActivityTag{ActivityId=101, TagId=29},
            new ActivityTag{ActivityId=101, TagId=34},
            new ActivityTag{ActivityId=101, TagId=36},
            new ActivityTag{ActivityId=101, TagId=39},
            new ActivityTag{ActivityId=101, TagId=40},
            new ActivityTag{ActivityId=101, TagId=49},
            new ActivityTag{ActivityId=101, TagId=50},
            new ActivityTag{ActivityId=101, TagId=51},
            new ActivityTag{ActivityId=101, TagId=52},
            new ActivityTag{ActivityId=101, TagId=53},
            new ActivityTag{ActivityId=101, TagId=54},
            new ActivityTag{ActivityId=102, TagId=11},
            new ActivityTag{ActivityId=102, TagId=16},
            new ActivityTag{ActivityId=102, TagId=18},
            new ActivityTag{ActivityId=102, TagId=19},
            new ActivityTag{ActivityId=102, TagId=20},
            new ActivityTag{ActivityId=102, TagId=23},
            new ActivityTag{ActivityId=102, TagId=26},
            new ActivityTag{ActivityId=102, TagId=29},
            new ActivityTag{ActivityId=102, TagId=30},
            new ActivityTag{ActivityId=102, TagId=31},
            new ActivityTag{ActivityId=102, TagId=34},
            new ActivityTag{ActivityId=102, TagId=36},
            new ActivityTag{ActivityId=102, TagId=37},
            new ActivityTag{ActivityId=102, TagId=38},
            new ActivityTag{ActivityId=102, TagId=39},
            new ActivityTag{ActivityId=102, TagId=40},
            new ActivityTag{ActivityId=102, TagId=46},
            new ActivityTag{ActivityId=102, TagId=49},
            new ActivityTag{ActivityId=102, TagId=50},
            new ActivityTag{ActivityId=102, TagId=51},
            new ActivityTag{ActivityId=102, TagId=52},
            new ActivityTag{ActivityId=102, TagId=53},
            new ActivityTag{ActivityId=102, TagId=54},
            new ActivityTag{ActivityId=103, TagId=18},
            new ActivityTag{ActivityId=103, TagId=19},
            new ActivityTag{ActivityId=103, TagId=22},
            new ActivityTag{ActivityId=103, TagId=23},
            new ActivityTag{ActivityId=103, TagId=25},
            new ActivityTag{ActivityId=103, TagId=26},
            new ActivityTag{ActivityId=103, TagId=29},
            new ActivityTag{ActivityId=103, TagId=30},
            new ActivityTag{ActivityId=103, TagId=34},
            new ActivityTag{ActivityId=103, TagId=36},
            new ActivityTag{ActivityId=103, TagId=38},
            new ActivityTag{ActivityId=103, TagId=39},
            new ActivityTag{ActivityId=103, TagId=40},
            new ActivityTag{ActivityId=103, TagId=49},
            new ActivityTag{ActivityId=103, TagId=50},
            new ActivityTag{ActivityId=103, TagId=51},
            new ActivityTag{ActivityId=103, TagId=52},
            new ActivityTag{ActivityId=103, TagId=53},
            new ActivityTag{ActivityId=103, TagId=54},
            new ActivityTag{ActivityId=104, TagId=18},
            new ActivityTag{ActivityId=104, TagId=19},
            new ActivityTag{ActivityId=104, TagId=22},
            new ActivityTag{ActivityId=104, TagId=23},
            new ActivityTag{ActivityId=104, TagId=25},
            new ActivityTag{ActivityId=104, TagId=26},
            new ActivityTag{ActivityId=104, TagId=29},
            new ActivityTag{ActivityId=104, TagId=30},
            new ActivityTag{ActivityId=104, TagId=34},
            new ActivityTag{ActivityId=104, TagId=36},
            new ActivityTag{ActivityId=104, TagId=38},
            new ActivityTag{ActivityId=104, TagId=39},
            new ActivityTag{ActivityId=104, TagId=40},
            new ActivityTag{ActivityId=104, TagId=49},
            new ActivityTag{ActivityId=104, TagId=50},
            new ActivityTag{ActivityId=104, TagId=51},
            new ActivityTag{ActivityId=104, TagId=52},
            new ActivityTag{ActivityId=104, TagId=53},
            new ActivityTag{ActivityId=104, TagId=54},
            new ActivityTag{ActivityId=105, TagId=18},
            new ActivityTag{ActivityId=105, TagId=19},
            new ActivityTag{ActivityId=105, TagId=22},
            new ActivityTag{ActivityId=105, TagId=23},
            new ActivityTag{ActivityId=105, TagId=25},
            new ActivityTag{ActivityId=105, TagId=26},
            new ActivityTag{ActivityId=105, TagId=29},
            new ActivityTag{ActivityId=105, TagId=30},
            new ActivityTag{ActivityId=105, TagId=34},
            new ActivityTag{ActivityId=105, TagId=36},
            new ActivityTag{ActivityId=105, TagId=38},
            new ActivityTag{ActivityId=105, TagId=39},
            new ActivityTag{ActivityId=105, TagId=40},
            new ActivityTag{ActivityId=105, TagId=49},
            new ActivityTag{ActivityId=105, TagId=50},
            new ActivityTag{ActivityId=105, TagId=51},
            new ActivityTag{ActivityId=105, TagId=52},
            new ActivityTag{ActivityId=105, TagId=53},
            new ActivityTag{ActivityId=105, TagId=54},
            new ActivityTag{ActivityId=106, TagId=11},
            new ActivityTag{ActivityId=106, TagId=21},
            new ActivityTag{ActivityId=106, TagId=22},
            new ActivityTag{ActivityId=106, TagId=23},
            new ActivityTag{ActivityId=106, TagId=25},
            new ActivityTag{ActivityId=106, TagId=36},
            new ActivityTag{ActivityId=106, TagId=47},
            new ActivityTag{ActivityId=106, TagId=48},
            new ActivityTag{ActivityId=106, TagId=49},
            new ActivityTag{ActivityId=106, TagId=50},
            new ActivityTag{ActivityId=106, TagId=51},
            new ActivityTag{ActivityId=106, TagId=52},
            new ActivityTag{ActivityId=106, TagId=53},
            new ActivityTag{ActivityId=106, TagId=54},
            new ActivityTag{ActivityId=107, TagId=21},
            new ActivityTag{ActivityId=107, TagId=22},
            new ActivityTag{ActivityId=107, TagId=25},
            new ActivityTag{ActivityId=107, TagId=26},
            new ActivityTag{ActivityId=107, TagId=31},
            new ActivityTag{ActivityId=107, TagId=36},
            new ActivityTag{ActivityId=107, TagId=38},
            new ActivityTag{ActivityId=107, TagId=39},
            new ActivityTag{ActivityId=107, TagId=47},
            new ActivityTag{ActivityId=107, TagId=48},
            new ActivityTag{ActivityId=107, TagId=49},
            new ActivityTag{ActivityId=107, TagId=50},
            new ActivityTag{ActivityId=107, TagId=51},
            new ActivityTag{ActivityId=107, TagId=52},
            new ActivityTag{ActivityId=107, TagId=53},
            new ActivityTag{ActivityId=107, TagId=54}


        };

        public static void Seed(this ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Tag>().HasData(Tags);

            modelBuilder.Entity<Activity>().HasData(Activities);

            modelBuilder.Entity<ActivityTag>().HasData(ActivityTags);
        }
    }

}