namespace FloorballTraining.CoreBusiness.Enums;

/// <summary>
/// Collectible milestone badges (#97). Each tier is its own code; a code is earned once per member,
/// or once per season for season-scoped badges (Iron Man). Stored as int.
/// </summary>
public enum BadgeCode
{
    Attendance10,
    Attendance25,
    Attendance50,
    Attendance100,
    FirstGoal,
    Goals10,
    Goals50,
    Hattrick,
    Assists10,
    Assists25,
    IronMan,
    Loyalty3,

    // Career expansion (10-season plan) — added 2026-08-14.
    Attendance150,
    Attendance250,
    Attendance400,
    Matches25,
    Matches100,
    Matches250,
    Goals100,
    Goals250,
    Goals500,
    FourGoalsInMatch,
    FiveGoalsInMatch,
    Assists50,
    Assists100,
    Points50,
    Points150,
    Points300,
    Points600,
    PlusMinus20,
    PlusMinus50,
    PlusMinus100,
    SeasonAttendance90,
    SeasonAttendance100,
    Loyalty5,
    Loyalty8,
    Loyalty10,
    HomeTraining10,
    HomeTraining50,
    HomeTraining150,
    SkillImprovement1,
    SkillImprovement10,
    SkillImprovement25,
    SkillTarget5,
    SkillTarget15,
    TestRecord1,
    TestRecord10,
    PlayerOfTraining5,
    PlayerOfTraining20,
    FairPlay5,
    FairPlay20,
    FamilyCheered10,
    FamilyCheered50,
    Challenges10,
    Challenges50,
    CareerXp5000,
    CareerXp15000,
    CareerXp30000
}
