name: build and publish to production server

on:
  push:
    branches: [ "master" ]  # Adjust branch name as needed
  workflow_dispatch:  # Allows manual trigger

env:
  SOLUTION_FILE: FloorballTraining.sln  # Replace with your solution file name
  PROJECT_PATH: FloorballTraining.WebApp  # Replace with your project path

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Using windows runner for .NET builds
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust version as needed
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish
    
    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/wwwroot/  # Adjust based on your Blazor app type
        server-dir: /wwwroot/  # Adjust your remote directory path
        dangerous-clean-slate: false  # Optional: removes all files in remote directory first
